// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';
import { assertShape } from '../../../src/utils/schema-assert';

test.describe('Attendance/Attendance Record — get-the-latest-attendance-record', () => {
  test('GET /api/v2/attendance/records/latest responds 200', async ({ attendanceAttendanceRecordApi }) => {
    const response = await attendanceAttendanceRecordApi.getTheLatestAttendanceRecord({});
    expect(response.status()).toBe(200);
    const body = await response.json();
    assertShape(body, {"kind":"object","properties":[{"name":"data","type":"unknown","required":false,"nullable":false},{"name":"meta","type":"unknown","required":false,"nullable":false}]});
  });
});
