// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: buzz_module
// Your own methods belong in BuzzPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/buzz/viewBuzz (also reachable at /web/index.php/buzz/photo/{id}) */
export abstract class BuzzPageGenerated extends BasePage {
  static readonly path = '/web/index.php/buzz/viewBuzz';
  static readonly aliases = ['/web/index.php/buzz/photo/{id}'] as const;

  constructor(page: Page) {
    super(page, BuzzPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);
}
