// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-buzz-viewBuzz
// Your own methods belong in BuzzPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { ImageComponent } from '../../components/ImageComponent';
import { InputComponent } from '../../components/InputComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/buzz/viewBuzz */
export abstract class BuzzPageGenerated extends BasePage {
  static readonly path = '/web/index.php/buzz/viewBuzz';

  constructor(page: Page) {
    super(page, BuzzPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Claim img (image) */
  // UNSTABLE: no accessible name; scoped to nearest named ancestor
  get claimImgImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('link', { name: 'Claim', exact: true }).getByRole('img'), 'Claim img (image)');
  }

  /** Buzz (text) */
  get buzzHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Buzz', exact: true }), 'Buzz (text)');
  }

  /** profile picture (image) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get profilePictureImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('img').nth(2), 'profile picture (image)');
  }

  /** profile picture (image) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get profilePictureImage2(): ImageComponent {
    return new ImageComponent(this.page.getByRole('img').nth(3), 'profile picture (image)');
  }

  /** What's on your mind? (input) */
  get whatSOnYourMindInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'What\'s on your mind?', exact: true }), 'What\'s on your mind? (input)');
  }

  /** Post (button) */
  get postButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Post', exact: true }), 'Post (button)');
  }

  /** Share Photos (button) */
  get sharePhotosButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Share Photos', exact: true }), 'Share Photos (button)');
  }

  /** Share Video (button) */
  get shareVideoButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Share Video', exact: true }), 'Share Video (button)');
  }

  /**  Most Recent Posts (button) */
  get mostRecentPostsButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: ' Most Recent Posts', exact: true }), ' Most Recent Posts (button)');
  }

  /**  Most Liked Posts (button) */
  get mostLikedPostsButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: ' Most Liked Posts', exact: true }), ' Most Liked Posts (button)');
  }

  /**  Most Commented Posts (button) */
  get mostCommentedPostsButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: ' Most Commented Posts', exact: true }), ' Most Commented Posts (button)');
  }

  /** Elements revealed by opening 'mandaa king'. Open the trigger first. */
  readonly mandaaKingOpen = new BuzzPageMandaaKingOpen(this.page);
}

/** Only present while 'mandaa king' is open. */
export class BuzzPageMandaaKingOpen {
  constructor(private readonly page: Page) {}

  /** About (menuItem) */
  get aboutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'About', exact: true }), 'About (menuItem)');
  }

  /** Support (menuItem) */
  get supportMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Support', exact: true }), 'Support (menuItem)');
  }

  /** Change Password (menuItem) */
  get changePasswordMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Change Password', exact: true }), 'Change Password (menuItem)');
  }

  /** Logout (menuItem) */
  get logoutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Logout', exact: true }), 'Logout (menuItem)');
  }
}
