// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('RequestPasswordResetCodePage', () => {
  test('loads', async ({ requestPasswordResetCodePage }) => {
    await requestPasswordResetCodePage.goto();
    await expect(requestPasswordResetCodePage.page).toHaveURL(new RegExp('/web/index\\.php/auth/requestPasswordResetCode'));
  });
});
