// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
//
// Chrome the mapper found on (nearly) every page: the top bar and side menu.

import type { Page } from '@playwright/test';
import { ButtonComponent } from '../ButtonComponent';
import { InputComponent } from '../InputComponent';
import { LinkComponent } from '../LinkComponent';
import { MenuItemComponent } from '../MenuItemComponent';
import { TextComponent } from '../TextComponent';

export class NavigationBar {
  constructor(private readonly page: Page) {}

  /** client brand banner (link) */
  get clientBrandBannerLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'client brand banner', exact: true }), 'client brand banner (link)');
  }

  /** Collapse menu (button) */
  get collapseMenuButton(): ButtonComponent {
    return new ButtonComponent(this.page.locator('button.oxd-main-menu-button'), 'Collapse menu (button)');
  }

  /** Search menu (input) */
  get searchMenuInput(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-main-menu-search input'), 'Search menu (input)');
  }

  /** Admin (link) */
  get adminMenuLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Admin', exact: true }), 'Admin (link)');
  }

  /** PIM (link) */
  get pimMenuLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'PIM', exact: true }), 'PIM (link)');
  }

  /** Leave (link) */
  get leaveMenuLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Leave', exact: true }), 'Leave (link)');
  }

  /** Time (link) */
  get timeMenuLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Time', exact: true }), 'Time (link)');
  }

  /** Recruitment (link) */
  get recruitmentMenuLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Recruitment', exact: true }), 'Recruitment (link)');
  }

  /** My Info (link) */
  get myInfoMenuLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'My Info', exact: true }), 'My Info (link)');
  }

  /** Performance (link) */
  get performanceMenuLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Performance', exact: true }), 'Performance (link)');
  }

  /** Dashboard (link) */
  get dashboardMenuLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Dashboard', exact: true }), 'Dashboard (link)');
  }

  /** Directory (link) */
  get directoryMenuLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Directory', exact: true }), 'Directory (link)');
  }

  /** Maintenance (link) */
  get maintenanceMenuLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Maintenance', exact: true }), 'Maintenance (link)');
  }

  /** Claim (link) */
  get claimMenuLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Claim', exact: true }), 'Claim (link)');
  }

  /** Buzz (link) */
  get buzzMenuLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Buzz', exact: true }), 'Buzz (link)');
  }

  /** Current user (text) */
  get currentUserHeading(): TextComponent {
    return new TextComponent(this.page.locator('.oxd-userdropdown-name'), 'Current user (text)');
  }

  /** Configuration (menuItem) */
  get configurationMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Configuration")'), 'Configuration (menuItem)');
  }
}
