// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: attendance_employee_punch_in_out
// Your own methods belong in ProxyPunchInPunchOutPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/attendance/proxyPunchInPunchOut (also reachable at /web/index.php/attendance/punchIn, /web/index.php/attendance/punchOut) */
export abstract class ProxyPunchInPunchOutPageGenerated extends BasePage {
  static readonly path = '/web/index.php/attendance/proxyPunchInPunchOut';
  static readonly aliases = ['/web/index.php/attendance/punchIn', '/web/index.php/attendance/punchOut'] as const;

  constructor(page: Page) {
    super(page, ProxyPunchInPunchOutPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Time (input) */
  get timeInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Time');
  }

  /** Note (longInput) */
  get noteLongInput(): InputComponent {
    return InputComponent.textareaByLabel(this.page, 'Note');
  }
}
