// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-maintenance-purgeEmployee
// Your own methods belong in PurgeEmployeePage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { InputComponent } from '../../components/InputComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/maintenance/purgeEmployee */
export abstract class PurgeEmployeePageGenerated extends BasePage {
  static readonly path = '/web/index.php/maintenance/purgeEmployee';

  constructor(page: Page) {
    super(page, PurgeEmployeePageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Administrator Access (text) */
  get administratorAccessHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Administrator Access');
  }

  /** Username (input) */
  get usernameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Username');
  }

  /** Password (input) */
  get passwordInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Password');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }

  /** Confirm (button) */
  get confirmButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Confirm');
  }
}
