// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: admin_add_auth_provider
// Your own methods belong in AddAuthProviderPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/admin/addAuthProvider (also reachable at /web/index.php/admin/editAuthProvider/{id}) */
export abstract class AddAuthProviderPageGenerated extends BasePage {
  static readonly path = '/web/index.php/admin/addAuthProvider';
  static readonly aliases = ['/web/index.php/admin/editAuthProvider/{id}'] as const;

  constructor(page: Page) {
    super(page, AddAuthProviderPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Name (input) */
  get nameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Name');
  }

  /** Provider URL (input) */
  get providerUrlInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Provider URL');
  }

  /** Client ID (input) */
  get clientIdInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Client ID');
  }

  /** Client Secret (input) */
  get clientSecretInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Client Secret');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
