// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-admin-addTheme
// Your own methods belong in AddThemePage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { InputComponent } from '../../components/InputComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/admin/addTheme */
export abstract class AddThemePageGenerated extends BasePage {
  static readonly path = '/web/index.php/admin/addTheme';

  constructor(page: Page) {
    super(page, AddThemePageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** User Management (menuItem) */
  get userManagementMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("User Management")'), 'User Management (menuItem)');
  }

  /** Job (menuItem) */
  get jobMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Job")'), 'Job (menuItem)');
  }

  /** Organization (menuItem) */
  get organizationMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Organization")'), 'Organization (menuItem)');
  }

  /** Qualifications (menuItem) */
  get qualificationsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Qualifications")'), 'Qualifications (menuItem)');
  }

  /** Configuration (menuItem) */
  get configurationMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Configuration")'), 'Configuration (menuItem)');
  }

  /** Nationalities (menuItem) */
  get nationalitiesMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Nationalities');
  }

  /** Corporate Branding (menuItem) */
  get corporateBrandingMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Corporate Branding');
  }

  /** Admin (text) */
  get adminHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Admin');
  }

  /** Corporate Branding (text) */
  get corporateBrandingHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Corporate Branding');
  }

  /** Client Logo (input) */
  get clientLogoInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Client Logo');
  }

  /** Client Banner (input) */
  get clientBannerInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Client Banner');
  }

  /** Login Banner (input) */
  get loginBannerInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Login Banner');
  }

  /** Reset to Default (button) */
  get resetToDefaultButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Reset to Default');
  }

  /** Preview (button) */
  get previewButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Preview');
  }

  /** Publish (button) */
  get publishButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Publish');
  }
}
