// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: view_organization_structure
// Your own methods belong in CompanyStructurePage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/admin/viewCompanyStructure */
export abstract class CompanyStructurePageGenerated extends BasePage {
  static readonly path = '/web/index.php/admin/viewCompanyStructure';

  constructor(page: Page) {
    super(page, CompanyStructurePageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Add (button) */
  get addButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Add');
  }

  /** No, Cancel (button) */
  get noCancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'No, Cancel');
  }

  /** Yes, Delete (button) */
  get yesDeleteButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Yes, Delete');
  }

  /** Unit Id (input) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get unitIdInput(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Unit Id")) input'), 'Unit Id (input)');
  }

  /** Name (input) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get nameInput(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Name")) input'), 'Name (input)');
  }

  /** Description (longInput) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get descriptionLongInput(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Description")) textarea'), 'Description (longInput)');
  }

  /** Cancel (button) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get cancelButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Cancel', exact: true }), 'Cancel (button)');
  }

  /** Unit Id (input) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get unitIdInput2(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Unit Id")) input'), 'Unit Id (input)');
  }

  /** Name (input) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get nameInput2(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Name")) input'), 'Name (input)');
  }

  /** Description (longInput) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get descriptionLongInput2(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Description")) textarea'), 'Description (longInput)');
  }

  /** Cancel (button) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get cancelButton2(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Cancel', exact: true }), 'Cancel (button)');
  }
}
