// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: view_employment_status
// Your own methods belong in EmploymentStatusPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/admin/employmentStatus */
export abstract class EmploymentStatusPageGenerated extends BasePage {
  static readonly path = '/web/index.php/admin/employmentStatus';

  constructor(page: Page) {
    super(page, EmploymentStatusPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Add (button) */
  get addButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Add');
  }

  /** Employment Status (table) */
  get employmentStatusTable(): TableComponent {
    return TableComponent.byColumn(this.page, 'Employment Status', ['Employment Status', 'Actions']);
  }

  /** Employment Status (button) */
  get employmentStatusButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Employment Status');
  }

  /** No, Cancel (button) */
  get noCancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'No, Cancel');
  }

  /** Yes, Delete (button) */
  get yesDeleteButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Yes, Delete');
  }
}
