// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: view_qualification_languages
// Your own methods belong in LanguagesPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/admin/viewLanguages */
export abstract class LanguagesPageGenerated extends BasePage {
  static readonly path = '/web/index.php/admin/viewLanguages';

  constructor(page: Page) {
    super(page, LanguagesPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Add (button) */
  get addButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Add');
  }

  /** Name (table) */
  get nameTable(): TableComponent {
    return TableComponent.byColumn(this.page, 'Name', ['Name', 'Actions']);
  }

  /** Languages (button) */
  get languagesButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Languages');
  }

  /** No, Cancel (button) */
  get noCancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'No, Cancel');
  }

  /** Yes, Delete (button) */
  get yesDeleteButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Yes, Delete');
  }
}
