// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: view_qualification_memberships
// Your own methods belong in MembershipPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/admin/membership */
export abstract class MembershipPageGenerated extends BasePage {
  static readonly path = '/web/index.php/admin/membership';

  constructor(page: Page) {
    super(page, MembershipPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Add (button) */
  get addButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Add');
  }

  /** Membership (table) */
  get membershipTable(): TableComponent {
    return TableComponent.byColumn(this.page, 'Membership', ['Membership', 'Actions']);
  }

  /** Memberships (button) */
  get membershipsButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Memberships');
  }

  /** No, Cancel (button) */
  get noCancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'No, Cancel');
  }

  /** Yes, Delete (button) */
  get yesDeleteButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Yes, Delete');
  }
}
