// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: view_pay_grades
// Your own methods belong in PayGradesPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/admin/viewPayGrades */
export abstract class PayGradesPageGenerated extends BasePage {
  static readonly path = '/web/index.php/admin/viewPayGrades';

  constructor(page: Page) {
    super(page, PayGradesPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Add (button) */
  get addButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Add');
  }

  /** Name (table) */
  get nameTable(): TableComponent {
    return TableComponent.byColumn(this.page, 'Name', ['Name', 'Currency', 'Actions']);
  }

  /** Pay Grades (button) */
  get payGradesButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Pay Grades');
  }

  /** No, Cancel (button) */
  get noCancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'No, Cancel');
  }

  /** Yes, Delete (button) */
  get yesDeleteButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Yes, Delete');
  }
}
