// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-admin-saveLocation
// Your own methods belong in SaveLocationPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/admin/saveLocation */
export abstract class SaveLocationPageGenerated extends BasePage {
  static readonly path = '/web/index.php/admin/saveLocation';

  constructor(page: Page) {
    super(page, SaveLocationPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** User Management (menuItem) */
  get userManagementMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("User Management")'), 'User Management (menuItem)');
  }

  /** Job (menuItem) */
  get jobMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Job")'), 'Job (menuItem)');
  }

  /** Organization (menuItem) */
  get organizationMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Organization")'), 'Organization (menuItem)');
  }

  /** Qualifications (menuItem) */
  get qualificationsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Qualifications")'), 'Qualifications (menuItem)');
  }

  /** Configuration (menuItem) */
  get configurationMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Configuration")'), 'Configuration (menuItem)');
  }

  /** Nationalities (menuItem) */
  get nationalitiesMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Nationalities');
  }

  /** Corporate Branding (menuItem) */
  get corporateBrandingMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Corporate Branding');
  }

  /** Admin (text) */
  get adminHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Admin');
  }

  /** Add Location (text) */
  get addLocationHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Add Location');
  }

  /** Name (input) */
  get nameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Name');
  }

  /** City (input) */
  get cityInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'City');
  }

  /** State/Province (input) */
  get stateProvinceInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'State/Province');
  }

  /** Zip/Postal Code (input) */
  get zipPostalCodeInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Zip/Postal Code');
  }

  /** Country (dropdown) */
  get countryDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Country');
  }

  /** Phone (input) */
  get phoneInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Phone');
  }

  /** Fax (input) */
  get faxInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Fax');
  }

  /** Address (longInput) */
  get addressTextArea(): InputComponent {
    return InputComponent.textareaByLabel(this.page, 'Address');
  }

  /** Notes (longInput) */
  get notesTextArea(): InputComponent {
    return InputComponent.textareaByLabel(this.page, 'Notes');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
