// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: edit_system_users
// Your own methods belong in SaveSystemUserPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/admin/saveSystemUser/{id} (also reachable at /web/index.php/admin/saveSystemUser) */
export abstract class SaveSystemUserPageGenerated extends BasePage {
  static readonly path = '/web/index.php/admin/saveSystemUser/{id}';
  static readonly aliases = ['/web/index.php/admin/saveSystemUser'] as const;

  constructor(page: Page) {
    super(page, SaveSystemUserPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** User Role (dropdown) */
  get userRoleDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'User Role');
  }

  /** Status (dropdown) */
  get statusDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Status');
  }

  /** Username (input) */
  get usernameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Username');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }

  /** Employee Name (input) */
  get employeeNameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Employee Name');
  }

  /** Password (input) */
  get passwordInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Password');
  }

  /** Confirm Password (input) */
  get confirmPasswordInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Confirm Password');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
