// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: edit_education
// Your own methods belong in SaveEducationPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/admin/saveEducation/{id} (also reachable at /web/index.php/admin/saveEducation) */
export abstract class SaveEducationPageGenerated extends BasePage {
  static readonly path = '/web/index.php/admin/saveEducation/{id}';
  static readonly aliases = ['/web/index.php/admin/saveEducation'] as const;

  constructor(page: Page) {
    super(page, SaveEducationPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Level (input) */
  get levelInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Level');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
