// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-admin-viewSystemUsers
// Your own methods belong in SystemUsersPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { CheckboxComponent } from '../../components/CheckboxComponent';
import { ImageComponent } from '../../components/ImageComponent';
import { InputComponent } from '../../components/InputComponent';
import { LinkComponent } from '../../components/LinkComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { OptionComponent } from '../../components/OptionComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/admin/viewSystemUsers */
export abstract class SystemUsersPageGenerated extends BasePage {
  static readonly path = '/web/index.php/admin/viewSystemUsers';

  constructor(page: Page) {
    super(page, SystemUsersPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Claim img (image) */
  // UNSTABLE: no accessible name; scoped to nearest named ancestor
  get claimImgImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('link', { name: 'Claim', exact: true }).getByRole('img'), 'Claim img (image)');
  }

  /** Admin (text) */
  get adminHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Admin', exact: true }), 'Admin (text)');
  }

  /** / User Management (text) */
  get userManagementHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: '/ User Management', exact: true }), '/ User Management (text)');
  }

  /** profile picture (image) */
  get profilePictureImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('img', { name: 'profile picture', exact: true }), 'profile picture (image)');
  }

  /** Nationalities (link) */
  get nationalitiesLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Nationalities', exact: true }), 'Nationalities (link)');
  }

  /** Corporate Branding (link) */
  get corporateBrandingLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Corporate Branding', exact: true }), 'Corporate Branding (link)');
  }

  /** System Users (text) */
  get systemUsersHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'System Users', exact: true }), 'System Users (text)');
  }

  /**  (button) */
  get elementButton3(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: '', exact: true }), ' (button)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(1), '(unnamed) (input)');
  }

  /** Type for hints... (input) */
  get typeForHintsInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'Type for hints...', exact: true }), 'Type for hints... (input)');
  }

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Reset', exact: true }), 'Reset (button)');
  }

  /** Search (button) */
  get searchButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Search', exact: true }), 'Search (button)');
  }

  /**  Add (button) */
  get addButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: ' Add', exact: true }), ' Add (button)');
  }

  /** table (table) */
  // UNSTABLE: table has no accessible name; positional index used
  get tableTable(): TableComponent {
    return new TableComponent(this.page.getByRole('table').nth(0), ['', 'Username ', 'User Role ', 'Employee Name ', 'Status ', 'Actions'], 'table (table)');
  }

  /**  (checkbox) */
  get elementCheckbox(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('columnheader', { name: '', exact: true }).getByRole('checkbox', { name: '', exact: true }), ' (checkbox)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox2(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(1), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton4(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(7), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton5(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(8), ' (button)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox3(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(2), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton6(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(9), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton7(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(10), ' (button)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox4(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(3), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton8(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(11), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton9(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(12), ' (button)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox5(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(4), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton10(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(13), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton11(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(14), ' (button)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox6(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(5), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton12(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(15), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton13(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(16), ' (button)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox7(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(6), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton14(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(17), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton15(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(18), ' (button)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox8(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(7), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton16(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(19), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton17(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(20), ' (button)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox9(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(8), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton18(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(21), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton19(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(22), ' (button)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox10(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(9), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton20(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(23), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton21(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(24), ' (button)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox11(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(10), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton22(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(25), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton23(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(26), ' (button)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox12(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(11), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton24(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(27), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton25(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(28), ' (button)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox13(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(12), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton26(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(29), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton27(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(30), ' (button)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox14(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(13), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton28(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(31), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton29(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(32), ' (button)');
  }

  /**  (checkbox) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementCheckbox15(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox').nth(14), ' (checkbox)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton30(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(33), ' (button)');
  }

  /**  (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get elementButton31(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(34), ' (button)');
  }

  /** Elements revealed by opening 'Surya king'. Open the trigger first. */
  readonly suryaKingOpen = new SystemUsersPageSuryaKingOpen(this.page);

  /** Elements revealed by opening '-- Select --'. Open the trigger first. */
  readonly selectOpen = new SystemUsersPageSelectOpen(this.page);

  /** Elements revealed by opening '-- Select --'. Open the trigger first. */
  readonly selectOpen2 = new SystemUsersPageSelectOpen2(this.page);
}

/** Only present while 'Surya king' is open. */
export class SystemUsersPageSuryaKingOpen {
  constructor(private readonly page: Page) {}

  /** About (menuItem) */
  get aboutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'About', exact: true }), 'About (menuItem)');
  }

  /** Support (menuItem) */
  get supportMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Support', exact: true }), 'Support (menuItem)');
  }

  /** Change Password (menuItem) */
  get changePasswordMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Change Password', exact: true }), 'Change Password (menuItem)');
  }

  /** Logout (menuItem) */
  get logoutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Logout', exact: true }), 'Logout (menuItem)');
  }
}

/** Only present while '-- Select --' is open. */
export class SystemUsersPageSelectOpen {
  constructor(private readonly page: Page) {}

  /** -- Select -- (dropdown) */
  get selectOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: '-- Select --', exact: true }), '-- Select -- (dropdown)');
  }

  /** Admin (dropdown) */
  get adminOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Admin', exact: true }), 'Admin (dropdown)');
  }

  /** ESS (dropdown) */
  get eSSOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'ESS', exact: true }), 'ESS (dropdown)');
  }
}

/** Only present while '-- Select --' is open. */
export class SystemUsersPageSelectOpen2 {
  constructor(private readonly page: Page) {}

  /** -- Select -- (dropdown) */
  get selectOption2(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: '-- Select --', exact: true }), '-- Select -- (dropdown)');
  }

  /** Enabled (dropdown) */
  get enabledOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Enabled', exact: true }), 'Enabled (dropdown)');
  }

  /** Disabled (dropdown) */
  get disabledOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Disabled', exact: true }), 'Disabled (dropdown)');
  }
}
