// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('PunchInPage', () => {
  test('loads', async ({ punchInPage }) => {
    await punchInPage.goto();
    await expect(punchInPage.attendanceHeading.locator).toBeVisible();
  });
});
