// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: #{controller}-{action}
// Your own methods belong in ControllerPage2.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /#{controller}/{action} */
export abstract class ControllerPage2Generated extends BasePage {
  static readonly path = '/#{controller}/{action}';

  constructor(page: Page) {
    super(page, ControllerPage2Generated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);
}
