// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: #{controller}-{action}-{options}
// Your own methods belong in ControllerPage3.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /#{controller}/{action}/{options} */
export abstract class ControllerPage3Generated extends BasePage {
  static readonly path = '/#{controller}/{action}/{options}';

  constructor(page: Page) {
    super(page, ControllerPage3Generated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);
}
