// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: #{controller}-related-{id}-{link}
// Your own methods belong in RelatedPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /#{controller}/related/{id}/{link} */
export abstract class RelatedPageGenerated extends BasePage {
  static readonly path = '/#{controller}/related/{id}/{link}';

  constructor(page: Page) {
    super(page, RelatedPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);
}
