// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('Leave/Holiday — delete-holidays', () => {
  test('DELETE /api/v2/leave/holidays responds 200', async ({ leaveHolidayApi }) => {
    const response = await leaveHolidayApi.deleteHolidays();
    expect(response.status()).toBe(200);
  });
});
