// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('ControllerViewPage2', () => {
  test('loads', async ({ controllerViewPage2 }) => {
    test.fixme(true, '\'/#{controller}/view/{id}/{options}\' needs a real record id — call controllerViewPage2.goto({ ... }) from a flow that created one');
    await controllerViewPage2.goto();
    await expect(controllerViewPage2.page).toHaveURL(new RegExp('/#\\{controller\\}/view/\\{id\\}/\\{options\\}'));
  });
});
