// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('ControllerPage3', () => {
  test('loads', async ({ controllerPage3 }) => {
    test.fixme(true, '\'/#{controller}/{action}/{options}\' needs a real record id — call controllerPage3.goto({ ... }) from a flow that created one');
    await controllerPage3.goto();
    await expect(controllerPage3.page).toHaveURL(new RegExp('/#\\{controller\\}/\\{action\\}/\\{options\\}'));
  });
});
