// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: auth_reset_code
// Your own methods belong in ResetPasswordPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/auth/resetPassword/resetCode/{resetCode} */
export abstract class ResetPasswordPageGenerated extends BasePage {
  static readonly path = '/web/index.php/auth/resetPassword/resetCode/{resetCode}';

  constructor(page: Page) {
    super(page, ResetPasswordPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Reset Password (input) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get resetPasswordInput(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Reset Password")) input'), 'Reset Password (input)');
  }

  /** Reset Password (input) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get resetPasswordInput2(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Reset Password")) input'), 'Reset Password (input)');
  }

  /** username (input) */
  get usernameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'username');
  }

  /** New Password (input) */
  get newPasswordInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'New Password');
  }

  /** Confirm Password (input) */
  get confirmPasswordInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Confirm Password');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
