#For Demo Orange HRM use those credentials
baseUrl=https://opensource-demo.orangehrmlive.com
username=Admin
password=admin123

##For XOQ7 Render Orange HRM use those
#baseUrl=https://orangehrm-xoq7.onrender.com
#username=Admin
#password=test


loginPage=/web/index.php/auth/login
adminPage=/web/index.php/admin/viewSystemUsers
directoryPage=/web/index.php/directory/viewDirectory
pimPage=/web/index.php/pim/viewEmployeeList
timePage=/web/index.php/time/viewEmployeeTimesheet
claimAssignPage=/web/index.php/claim/assignClaim
employeeClaimsPage=/web/index.php/claim/viewAssignClaim
leaveAddEntitlementPage=/web/index.php/leave/addLeaveEntitlement
leaveMyEntitlementsPage=/web/index.php/leave/viewMyLeaveEntitlements
leaveTypesPage=/web/index.php/leave/leaveTypeList
