// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('PIM/Termination Reason Configuration — delete-termination-reasons', () => {
  test('DELETE /api/v2/pim/termination-reasons responds 200', async ({ pimTerminationReasonConfigurationApi }) => {
    const response = await pimTerminationReasonConfigurationApi.deleteTerminationReasons();
    expect(response.status()).toBe(200);
  });
});
