// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('PIM/Custom Field — delete-custom-fields', () => {
  test('DELETE /api/v2/pim/custom-fields responds 200', async ({ pimCustomFieldApi }) => {
    const response = await pimCustomFieldApi.deleteCustomFields();
    expect(response.status()).toBe(200);
  });
});
