// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('AddLeaveEntitlementPage', () => {
  test('loads', async ({ addLeaveEntitlementPage }) => {
    await addLeaveEntitlementPage.goto();
    await expect(addLeaveEntitlementPage.page).toHaveURL(new RegExp('/web/index\\.php/leave/addLeaveEntitlement'));
  });
});
