// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('AssignLeavePage', () => {
  test('loads', async ({ assignLeavePage }) => {
    await assignLeavePage.goto();
    await expect(assignLeavePage.page).toHaveURL(new RegExp('/web/index\\.php/leave/assignLeave'));
  });
});
