// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('DefineLeaveTypePage', () => {
  test('loads', async ({ defineLeaveTypePage }) => {
    await defineLeaveTypePage.goto();
    await expect(defineLeaveTypePage.page).toHaveURL(new RegExp('/web/index\\.php/leave/defineLeaveType/\\{id\\}'));
  });
});
