// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('LeaveBalanceReportPage', () => {
  test('loads', async ({ leaveBalanceReportPage }) => {
    await leaveBalanceReportPage.goto();
    await expect(leaveBalanceReportPage.leaveHeading.locator).toBeVisible();
  });
});
