// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';
import { assertShape } from '../../../src/utils/schema-assert';

test.describe('Admin/Nationality — create-a-nationality', () => {
  test('POST /api/v2/admin/nationalities responds 200', async ({ adminNationalityApi }) => {
    // TODO: fill in a valid request body.
    const response = await adminNationalityApi.createANationality({} as never);
    expect(response.status()).toBe(200);
    const body = await response.json();
    assertShape(body, {"kind":"object","properties":[{"name":"data","type":"unknown","required":false,"nullable":false},{"name":"meta","type":"unknown","required":false,"nullable":false}]});
  });
});
