// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('Admin/Nationality — delete-nationalities', () => {
  test('DELETE /api/v2/admin/nationalities responds 200', async ({ adminNationalityApi }) => {
    const response = await adminNationalityApi.deleteNationalities();
    expect(response.status()).toBe(200);
  });
});
