// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('AddCandidatePage', () => {
  test('loads', async ({ addCandidatePage }) => {
    await addCandidatePage.goto();
    await expect(addCandidatePage.page).toHaveURL(new RegExp('/web/index\\.php/recruitment/addCandidate'));
  });
});
