// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('CandidateAttachmentPage', () => {
  test('loads', async ({ candidateAttachmentPage }) => {
    await candidateAttachmentPage.goto();
    await expect(candidateAttachmentPage.page).toHaveURL(new RegExp('/web/index\\.php/recruitment/viewCandidateAttachment/candidateId/\\{candidateId\\}'));
  });
});
