// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('ChangeCandidateVacancyStatusPage', () => {
  test('loads', async ({ changeCandidateVacancyStatusPage }) => {
    await changeCandidateVacancyStatusPage.goto();
    await expect(changeCandidateVacancyStatusPage.page).toHaveURL(new RegExp('/web/index\\.php/recruitment/changeCandidateVacancyStatus'));
  });
});
