// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: #clearCache
// Your own methods belong in ClearCachePage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /#clearCache */
export abstract class ClearCachePageGenerated extends BasePage {
  static readonly path = '/#clearCache';

  constructor(page: Page) {
    super(page, ClearCachePageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);
}
