// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';
import { assertShape } from '../../../src/utils/schema-assert';

test.describe('Dashboard/Widgets — get-my-action-summary', () => {
  test('GET /api/v2/dashboard/employees/action-summary responds 200', async ({ dashboardWidgetsApi }) => {
    const response = await dashboardWidgetsApi.getMyActionSummary();
    expect(response.status()).toBe(200);
    const body = await response.json();
    assertShape(body, {"kind":"object","properties":[{"name":"id","type":"number","required":false,"nullable":false},{"name":"group","type":"string","required":false,"nullable":false},{"name":"pendingActionCount","type":"number","required":false,"nullable":false}]});
  });
});
