// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: recruitment_apply_job_vacancy
// Your own methods belong in ApplyVacancyPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { CheckboxComponent } from '../../components/CheckboxComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/recruitmentApply/applyVacancy/id/{id} */
export abstract class ApplyVacancyPageGenerated extends BasePage {
  static readonly path = '/web/index.php/recruitmentApply/applyVacancy/id/{id}';

  constructor(page: Page) {
    super(page, ApplyVacancyPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** tokenInput (input) */
  get tokenInput(): InputComponent {
    return new InputComponent(this.page.locator('[name="_token"]'), 'tokenInput (input)');
  }

  /** vacancyIdInput (input) */
  get vacancyIdInput(): InputComponent {
    return new InputComponent(this.page.locator('[name="vacancyId"]'), 'vacancyIdInput (input)');
  }

  /** Email (input) */
  get emailInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Email');
  }

  /** Contact Number (input) */
  get contactNumberInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Contact Number');
  }

  /** Resume (input) */
  get resumeInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Resume');
  }

  /** Keywords (input) */
  get keywordsInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Keywords');
  }

  /** Notes (longInput) */
  get notesLongInput(): InputComponent {
    return InputComponent.textareaByLabel(this.page, 'Notes');
  }

  /** Consent to keep data (checkbox) */
  get consentToKeepDataCheckbox(): CheckboxComponent {
    return new CheckboxComponent(this.page.locator('[name="consentToKeepData"]'), 'Consent to keep data (checkbox)');
  }

  /** Back (button) */
  get backButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Back');
  }

  /** firstNameInput (input) */
  get firstNameInput(): InputComponent {
    return new InputComponent(this.page.getByPlaceholder('First name'), 'firstNameInput (input)');
  }

  /** middleNameInput (input) */
  get middleNameInput(): InputComponent {
    return new InputComponent(this.page.locator('[name="middleName"]'), 'middleNameInput (input)');
  }

  /** lastNameInput (input) */
  get lastNameInput(): InputComponent {
    return new InputComponent(this.page.getByPlaceholder('Last Name'), 'lastNameInput (input)');
  }

  /** Submit (button) */
  get submitButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Submit');
  }

  /** Powered By (button) */
  get poweredByButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Powered By');
  }
}
