// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
//
// One fixture per page object, plus `api` for the setup, teardown and
// assertions that do not need a browser, and one typed fixture per api-mapped
// resource. Playwright builds only the ones a test asks for, so declaring all
// of them costs nothing at run time.

import { test as base } from '@playwright/test';
import { ApiClient } from '../api/clients/ApiClient';
import { ControllerPage } from '../pages/controller/ControllerPage';
import { ControllerPage2 } from '../pages/controller/ControllerPage2';
import { ControllerPage3 } from '../pages/controller/ControllerPage3';
import { CreatePage } from '../pages/controller/CreatePage';
import { ControllerEditPage } from '../pages/controller/ControllerEditPage';
import { ControllerEditPage2 } from '../pages/controller/ControllerEditPage2';
import { RelatedPage } from '../pages/controller/RelatedPage';
import { ControllerViewPage } from '../pages/controller/ControllerViewPage';
import { ControllerViewPage2 } from '../pages/controller/ControllerViewPage2';
import { ClearCachePage } from '../pages/clear-cache/ClearCachePage';

export type PageObjects = {
  api: ApiClient;
  controllerPage: ControllerPage;
  controllerPage2: ControllerPage2;
  controllerPage3: ControllerPage3;
  createPage: CreatePage;
  controllerEditPage: ControllerEditPage;
  controllerEditPage2: ControllerEditPage2;
  relatedPage: RelatedPage;
  controllerViewPage: ControllerViewPage;
  controllerViewPage2: ControllerViewPage2;
  clearCachePage: ClearCachePage;
};

export const test = base.extend<PageObjects>({
  api: async ({ request }, use) => { await use(new ApiClient(request)); },
  controllerPage: async ({ page }, use) => { await use(new ControllerPage(page)); },
  controllerPage2: async ({ page }, use) => { await use(new ControllerPage2(page)); },
  controllerPage3: async ({ page }, use) => { await use(new ControllerPage3(page)); },
  createPage: async ({ page }, use) => { await use(new CreatePage(page)); },
  controllerEditPage: async ({ page }, use) => { await use(new ControllerEditPage(page)); },
  controllerEditPage2: async ({ page }, use) => { await use(new ControllerEditPage2(page)); },
  relatedPage: async ({ page }, use) => { await use(new RelatedPage(page)); },
  controllerViewPage: async ({ page }, use) => { await use(new ControllerViewPage(page)); },
  controllerViewPage2: async ({ page }, use) => { await use(new ControllerViewPage2(page)); },
  clearCachePage: async ({ page }, use) => { await use(new ClearCachePage(page)); },
});

export { expect } from '@playwright/test';
