// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-recruitment-addJobVacancy
// Your own methods belong in AddJobVacancyPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/recruitment/addJobVacancy */
export abstract class AddJobVacancyPageGenerated extends BasePage {
  static readonly path = '/web/index.php/recruitment/addJobVacancy';

  constructor(page: Page) {
    super(page, AddJobVacancyPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Candidates (menuItem) */
  get candidatesMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Candidates');
  }

  /** Vacancies (menuItem) */
  get vacanciesMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Vacancies');
  }

  /** Recruitment (text) */
  get recruitmentHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Recruitment');
  }

  /** Add Vacancy (text) */
  get addVacancyHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Add Vacancy');
  }

  /** Vacancy Name (input) */
  get vacancyNameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Vacancy Name');
  }

  /** Job Title (dropdown) */
  get jobTitleDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Job Title');
  }

  /** Description (longInput) */
  get descriptionTextArea(): InputComponent {
    return InputComponent.textareaByLabel(this.page, 'Description');
  }

  /** Hiring Manager (input) */
  get hiringManagerInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Hiring Manager');
  }

  /** Number of Positions (input) */
  get numberOfPositionsInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Number of Positions');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
