// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-recruitment-viewCandidates
// Your own methods belong in CandidatesPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { ImageComponent } from '../../components/ImageComponent';
import { InputComponent } from '../../components/InputComponent';
import { LinkComponent } from '../../components/LinkComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { OptionComponent } from '../../components/OptionComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/recruitment/viewCandidates */
export abstract class CandidatesPageGenerated extends BasePage {
  static readonly path = '/web/index.php/recruitment/viewCandidates';

  constructor(page: Page) {
    super(page, CandidatesPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Claim img (image) */
  // UNSTABLE: no accessible name; scoped to nearest named ancestor
  get claimImgImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('link', { name: 'Claim', exact: true }).getByRole('img'), 'Claim img (image)');
  }

  /** Recruitment (text) */
  get recruitmentHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Recruitment', exact: true }), 'Recruitment (text)');
  }

  /** profile picture (image) */
  get profilePictureImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('img', { name: 'profile picture', exact: true }), 'profile picture (image)');
  }

  /** Candidates (link) */
  get candidatesLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Candidates', exact: true }), 'Candidates (link)');
  }

  /** Vacancies (link) */
  get vacanciesLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Vacancies', exact: true }), 'Vacancies (link)');
  }

  /** Candidates (text) */
  get candidatesHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Candidates', exact: true }), 'Candidates (text)');
  }

  /**  (button) */
  get elementButton3(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: '', exact: true }), ' (button)');
  }

  /** Type for hints... (input) */
  get typeForHintsInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'Type for hints...', exact: true }), 'Type for hints... (input)');
  }

  /** Enter comma seperated words... (input) */
  get enterCommaSeperatedWordsInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'Enter comma seperated words...', exact: true }), 'Enter comma seperated words... (input)');
  }

  /** From (input) */
  get fromInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'From', exact: true }), 'From (input)');
  }

  /** To (input) */
  get toInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'To', exact: true }), 'To (input)');
  }

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Reset', exact: true }), 'Reset (button)');
  }

  /** Search (button) */
  get searchButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Search', exact: true }), 'Search (button)');
  }

  /**  Add (button) */
  get addButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: ' Add', exact: true }), ' Add (button)');
  }

  /** table (table) */
  // UNSTABLE: table has no accessible name; positional index used
  get tableTable(): TableComponent {
    return new TableComponent(this.page.getByRole('table').nth(0), [], 'table (table)');
  }

  /** Elements revealed by opening 'Surya king'. Open the trigger first. */
  readonly suryaKingOpen = new CandidatesPageSuryaKingOpen(this.page);

  /** Elements revealed by opening '-- Select --'. Open the trigger first. */
  readonly selectOpen = new CandidatesPageSelectOpen(this.page);

  /** Elements revealed by opening '-- Select --'. Open the trigger first. */
  readonly selectOpen2 = new CandidatesPageSelectOpen2(this.page);

  /** Elements revealed by opening '-- Select --'. Open the trigger first. */
  readonly selectOpen3 = new CandidatesPageSelectOpen3(this.page);
}

/** Only present while 'Surya king' is open. */
export class CandidatesPageSuryaKingOpen {
  constructor(private readonly page: Page) {}

  /** About (menuItem) */
  get aboutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'About', exact: true }), 'About (menuItem)');
  }

  /** Support (menuItem) */
  get supportMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Support', exact: true }), 'Support (menuItem)');
  }

  /** Change Password (menuItem) */
  get changePasswordMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Change Password', exact: true }), 'Change Password (menuItem)');
  }

  /** Logout (menuItem) */
  get logoutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Logout', exact: true }), 'Logout (menuItem)');
  }

  /** 1 (button) */
  get n1Button(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: '1', exact: true }), '1 (button)');
  }

  /** 2 (button) */
  get n2Button(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: '2', exact: true }), '2 (button)');
  }

  /**  (button) */
  get elementButton125(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: '', exact: true }), ' (button)');
  }
}

/** Only present while '-- Select --' is open. */
export class CandidatesPageSelectOpen {
  constructor(private readonly page: Page) {}

  /** No Records Found (dropdown) */
  get noRecordsFoundOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'No Records Found', exact: true }), 'No Records Found (dropdown)');
  }
}

/** Only present while '-- Select --' is open. */
export class CandidatesPageSelectOpen2 {
  constructor(private readonly page: Page) {}

  /** -- Select -- (dropdown) */
  get selectOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: '-- Select --', exact: true }), '-- Select -- (dropdown)');
  }

  /** Surya king (dropdown) */
  get suryaKingOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Surya king', exact: true }), 'Surya king (dropdown)');
  }
}

/** Only present while '-- Select --' is open. */
export class CandidatesPageSelectOpen3 {
  constructor(private readonly page: Page) {}

  /** -- Select -- (dropdown) */
  get selectOption2(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: '-- Select --', exact: true }), '-- Select -- (dropdown)');
  }

  /** Manual (dropdown) */
  get manualOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Manual', exact: true }), 'Manual (dropdown)');
  }

  /** Online (dropdown) */
  get onlineOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Online', exact: true }), 'Online (dropdown)');
  }
}
