// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: recruitment_candidate_action
// Your own methods belong in ChangeCandidateVacancyStatusPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/recruitment/changeCandidateVacancyStatus */
export abstract class ChangeCandidateVacancyStatusPageGenerated extends BasePage {
  static readonly path = '/web/index.php/recruitment/changeCandidateVacancyStatus';

  constructor(page: Page) {
    super(page, ChangeCandidateVacancyStatusPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Notes (longInput) */
  get notesLongInput(): InputComponent {
    return InputComponent.textareaByLabel(this.page, 'Notes');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }

  /** Candidate (input) */
  get candidateInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Candidate');
  }

  /** Vacancy (input) */
  get vacancyInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Vacancy');
  }

  /** Hiring Manager (input) */
  get hiringManagerInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Hiring Manager');
  }

  /** Current Status (input) */
  get currentStatusInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Current Status');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
