// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: recruitment_view_interview_attachments
// Your own methods belong in InterviewAttachmentsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { InputComponent } from '../../components/InputComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/recruitment/interviewAttachments/{interviewId} */
export abstract class InterviewAttachmentsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/recruitment/interviewAttachments/{interviewId}';

  constructor(page: Page) {
    super(page, InterviewAttachmentsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Add (button) */
  get addButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Add');
  }

  /** File Name (table) */
  get fileNameTable(): TableComponent {
    return TableComponent.byColumn(this.page, 'File Name', ['File Name', 'Size', 'Type', 'Comment', 'Actions']);
  }

  /** Select File (input) */
  get selectFileInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Select File');
  }

  /** Comment (longInput) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get commentLongInput(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Comment")) textarea'), 'Comment (longInput)');
  }

  /** Cancel (button) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get cancelButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Cancel', exact: true }), 'Cancel (button)');
  }

  /** Replace With (input) */
  get replaceWithInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Replace With');
  }

  /** Comment (longInput) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get commentLongInput2(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Comment")) textarea'), 'Comment (longInput)');
  }

  /** Cancel (button) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get cancelButton2(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Cancel', exact: true }), 'Cancel (button)');
  }

  /** Attachments (button) */
  get attachmentsButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Attachments');
  }

  /** No, Cancel (button) */
  get noCancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'No, Cancel');
  }

  /** Yes, Delete (button) */
  get yesDeleteButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Yes, Delete');
  }
}
