// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: recruitment_view_job_vacancy
// Your own methods belong in JobVacancyPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/recruitment/viewJobVacancy */
export abstract class JobVacancyPageGenerated extends BasePage {
  static readonly path = '/web/index.php/recruitment/viewJobVacancy';

  constructor(page: Page) {
    super(page, JobVacancyPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Status (dropdown) */
  get statusDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Status');
  }

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Reset');
  }

  /** Search (button) */
  get searchButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Search');
  }

  /** Add (button) */
  get addButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Add');
  }

  /** Vacancy (table) */
  get vacancyTable(): TableComponent {
    return TableComponent.byColumn(this.page, 'Vacancy', ['Vacancy', 'Job Title', 'Hiring Manager', 'Status', 'Actions']);
  }

  /** Job Title (dropdown) */
  get jobTitleDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Job Title');
  }

  /** Vacancy (dropdown) */
  get vacancyDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Vacancy');
  }

  /** Hiring Manager (dropdown) */
  get hiringManagerDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Hiring Manager');
  }

  /** Delete Selected (button) */
  get deleteSelectedButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Delete Selected');
  }

  /** No, Cancel (button) */
  get noCancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'No, Cancel');
  }

  /** Yes, Delete (button) */
  get yesDeleteButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Yes, Delete');
  }
}
