// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-recruitment-viewJobVacancy
// Your own methods belong in JobVacancyPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/recruitment/viewJobVacancy */
export abstract class JobVacancyPageGenerated extends BasePage {
  static readonly path = '/web/index.php/recruitment/viewJobVacancy';

  constructor(page: Page) {
    super(page, JobVacancyPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Candidates (menuItem) */
  get candidatesMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Candidates');
  }

  /** Vacancies (menuItem) */
  get vacanciesMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Vacancies');
  }

  /** Recruitment (text) */
  get recruitmentHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Recruitment');
  }

  /** Vacancies (text) */
  get vacanciesHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Vacancies');
  }

  /** Job Title (dropdown) */
  get jobTitleDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Job Title');
  }

  /** Vacancy (dropdown) */
  get vacancyDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Vacancy');
  }

  /** Hiring Manager (dropdown) */
  get hiringManagerDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Hiring Manager');
  }

  /** Status (dropdown) */
  get statusDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Status');
  }

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Reset');
  }

  /** Search (button) */
  get searchButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Search');
  }

  /** Add (button) */
  get addButton(): ButtonComponent {
    return new ButtonComponent(this.page.locator('button:text-is("Add")'), 'Add (button)');
  }

  /** Records (table) */
  get recordsTable(): TableComponent {
    return new TableComponent(this.page.locator('.oxd-table:has(.oxd-table-th:text-is("Vacancy"))'), ['Vacancy', 'Job Title', 'Hiring Manager', 'Status', 'Actions'], 'Records (table)');
  }
}
