// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-leave-applyLeave
// Your own methods belong in ApplyLeavePage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/leave/applyLeave */
export abstract class ApplyLeavePageGenerated extends BasePage {
  static readonly path = '/web/index.php/leave/applyLeave';

  constructor(page: Page) {
    super(page, ApplyLeavePageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Entitlements (menuItem) */
  get entitlementsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Entitlements")'), 'Entitlements (menuItem)');
  }

  /** Reports (menuItem) */
  get reportsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Reports")'), 'Reports (menuItem)');
  }

  /** Configure (menuItem) */
  get configureMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Configure")'), 'Configure (menuItem)');
  }

  /** Apply (menuItem) */
  get applyMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Apply');
  }

  /** My Leave (menuItem) */
  get myLeaveMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'My Leave');
  }

  /** Leave List (menuItem) */
  get leaveListMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Leave List');
  }

  /** Assign Leave (menuItem) */
  get assignLeaveMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Assign Leave');
  }

  /** Leave (text) */
  get leaveHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Leave');
  }

  /** Apply Leave (text) */
  get applyLeaveHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Apply Leave');
  }
}
