// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: leave_define_leave_period
// Your own methods belong in DefineLeavePeriodPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/leave/defineLeavePeriod */
export abstract class DefineLeavePeriodPageGenerated extends BasePage {
  static readonly path = '/web/index.php/leave/defineLeavePeriod';

  constructor(page: Page) {
    super(page, DefineLeavePeriodPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Start Month (dropdown) */
  get startMonthDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Start Month');
  }

  /** Start Date (dropdown) */
  get startDateDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Start Date');
  }

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Reset');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
