// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-leave-defineWorkWeek
// Your own methods belong in DefineWorkWeekPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/leave/defineWorkWeek */
export abstract class DefineWorkWeekPageGenerated extends BasePage {
  static readonly path = '/web/index.php/leave/defineWorkWeek';

  constructor(page: Page) {
    super(page, DefineWorkWeekPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Entitlements (menuItem) */
  get entitlementsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Entitlements")'), 'Entitlements (menuItem)');
  }

  /** Reports (menuItem) */
  get reportsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Reports")'), 'Reports (menuItem)');
  }

  /** Configure (menuItem) */
  get configureMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Configure")'), 'Configure (menuItem)');
  }

  /** Apply (menuItem) */
  get applyMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Apply');
  }

  /** My Leave (menuItem) */
  get myLeaveMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'My Leave');
  }

  /** Leave List (menuItem) */
  get leaveListMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Leave List');
  }

  /** Assign Leave (menuItem) */
  get assignLeaveMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Assign Leave');
  }

  /** Leave (text) */
  get leaveHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Leave');
  }

  /** Monday (dropdown) */
  get mondayDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Monday');
  }

  /** Tuesday (dropdown) */
  get tuesdayDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Tuesday');
  }

  /** Wednesday (dropdown) */
  get wednesdayDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Wednesday');
  }

  /** Thursday (dropdown) */
  get thursdayDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Thursday');
  }

  /** Friday (dropdown) */
  get fridayDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Friday');
  }

  /** Saturday (dropdown) */
  get saturdayDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Saturday');
  }

  /** Sunday (dropdown) */
  get sundayDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Sunday');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
