// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-leave-defineLeavePeriod
// Your own methods belong in DefineLeavePeriodPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/leave/defineLeavePeriod */
export abstract class DefineLeavePeriodPageGenerated extends BasePage {
  static readonly path = '/web/index.php/leave/defineLeavePeriod';

  constructor(page: Page) {
    super(page, DefineLeavePeriodPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Entitlements (menuItem) */
  get entitlementsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Entitlements")'), 'Entitlements (menuItem)');
  }

  /** Reports (menuItem) */
  get reportsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Reports")'), 'Reports (menuItem)');
  }

  /** Configure (menuItem) */
  get configureMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Configure")'), 'Configure (menuItem)');
  }

  /** Apply (menuItem) */
  get applyMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Apply');
  }

  /** My Leave (menuItem) */
  get myLeaveMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'My Leave');
  }

  /** Leave List (menuItem) */
  get leaveListMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Leave List');
  }

  /** Assign Leave (menuItem) */
  get assignLeaveMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Assign Leave');
  }

  /** Leave (text) */
  get leaveHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Leave');
  }

  /** Start Month (dropdown) */
  get startMonthDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Start Month');
  }

  /** Start Date (dropdown) */
  get startDateDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Start Date');
  }

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Reset');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
