// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: edit_leave_type
// Your own methods belong in DefineLeaveTypePage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { InputComponent } from '../../components/InputComponent';
import { RadioComponent } from '../../components/RadioComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/leave/defineLeaveType/{id} (also reachable at /web/index.php/leave/defineLeaveType) */
export abstract class DefineLeaveTypePageGenerated extends BasePage {
  static readonly path = '/web/index.php/leave/defineLeaveType/{id}';
  static readonly aliases = ['/web/index.php/leave/defineLeaveType'] as const;

  constructor(page: Page) {
    super(page, DefineLeaveTypePageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Name (input) */
  get nameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Name');
  }

  /** Yes (radio) */
  get yesRadio(): RadioComponent {
    return new RadioComponent(this.page.locator('.oxd-radio-wrapper:has(label:text-is("Yes")) input'), 'Yes (radio)');
  }

  /** No (radio) */
  get noRadio(): RadioComponent {
    return new RadioComponent(this.page.locator('.oxd-radio-wrapper:has(label:text-is("No")) input'), 'No (radio)');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }

  /** Edit Leave Type (button) */
  get editLeaveTypeButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Edit Leave Type');
  }
}
