// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: leave_view_leave_request
// Your own methods belong in LeaveRequestPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { InputComponent } from '../../components/InputComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/leave/viewLeaveRequest/{id} */
export abstract class LeaveRequestPageGenerated extends BasePage {
  static readonly path = '/web/index.php/leave/viewLeaveRequest/{id}';

  constructor(page: Page) {
    super(page, LeaveRequestPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Date (table) */
  get dateTable(): TableComponent {
    return TableComponent.byColumn(this.page, 'Date', ['Date', 'Leave Type', 'Leave Balance (Days)', 'Duration (Hours)', 'Status', 'Comments', 'Actions']);
  }

  /** Back (button) */
  get backButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Back');
  }

  /** Comments (button) */
  get commentsButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Comments');
  }

  /** Delete Selected (button) */
  get deleteSelectedButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Delete Selected');
  }

  /** commentHereLongInput (longInput) */
  get commentHereLongInput(): InputComponent {
    return new InputComponent(this.page.getByPlaceholder('Comment here'), 'commentHereLongInput (longInput)');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }
}
