// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-leave-viewLeaveList
// Your own methods belong in LeaveListPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/leave/viewLeaveList */
export abstract class LeaveListPageGenerated extends BasePage {
  static readonly path = '/web/index.php/leave/viewLeaveList';

  constructor(page: Page) {
    super(page, LeaveListPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Entitlements (menuItem) */
  get entitlementsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Entitlements")'), 'Entitlements (menuItem)');
  }

  /** Reports (menuItem) */
  get reportsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Reports")'), 'Reports (menuItem)');
  }

  /** Configure (menuItem) */
  get configureMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Configure")'), 'Configure (menuItem)');
  }

  /** Apply (menuItem) */
  get applyMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Apply');
  }

  /** My Leave (menuItem) */
  get myLeaveMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'My Leave');
  }

  /** Leave List (menuItem) */
  get leaveListMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Leave List');
  }

  /** Assign Leave (menuItem) */
  get assignLeaveMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Assign Leave');
  }

  /** Leave (text) */
  get leaveHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Leave');
  }

  /** Leave List (text) */
  get leaveListHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Leave List');
  }

  /** From Date (input) */
  get fromDateInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'From Date');
  }

  /** To Date (input) */
  get toDateInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'To Date');
  }

  /** Show Leave with Status (dropdown) */
  get showLeaveWithStatusDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Show Leave with Status');
  }

  /** Leave Type (dropdown) */
  get leaveTypeDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Leave Type');
  }

  /** Employee Name (input) */
  get employeeNameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Employee Name');
  }

  /** Sub Unit (dropdown) */
  get subUnitDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Sub Unit');
  }

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Reset');
  }

  /** Search (button) */
  get searchButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Search');
  }

  /** Records (table) */
  get recordsTable(): TableComponent {
    return new TableComponent(this.page.locator('.oxd-table:has(.oxd-table-th:text-is("Date"))'), ['Date', 'Employee Name', 'Leave Type', 'Leave Balance (Days)', 'Number of Days', 'Status', 'Comments', 'Actions'], 'Records (table)');
  }
}
