// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-leave-viewMyLeaveList
// Your own methods belong in MyLeaveListPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { ImageComponent } from '../../components/ImageComponent';
import { InputComponent } from '../../components/InputComponent';
import { LinkComponent } from '../../components/LinkComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { OptionComponent } from '../../components/OptionComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/leave/viewMyLeaveList */
export abstract class MyLeaveListPageGenerated extends BasePage {
  static readonly path = '/web/index.php/leave/viewMyLeaveList';

  constructor(page: Page) {
    super(page, MyLeaveListPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Claim img (image) */
  // UNSTABLE: no accessible name; scoped to nearest named ancestor
  get claimImgImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('link', { name: 'Claim', exact: true }).getByRole('img'), 'Claim img (image)');
  }

  /** Leave (text) */
  get leaveHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Leave', exact: true }), 'Leave (text)');
  }

  /** profile picture (image) */
  get profilePictureImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('img', { name: 'profile picture', exact: true }), 'profile picture (image)');
  }

  /** Apply (link) */
  get applyLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Apply', exact: true }), 'Apply (link)');
  }

  /** My Leave (link) */
  get myLeaveLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'My Leave', exact: true }), 'My Leave (link)');
  }

  /** Leave List (link) */
  get leaveListLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Leave List', exact: true }), 'Leave List (link)');
  }

  /** Assign Leave (link) */
  get assignLeaveLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Assign Leave', exact: true }), 'Assign Leave (link)');
  }

  /** My Leave List (text) */
  get myLeaveListHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'My Leave List', exact: true }), 'My Leave List (text)');
  }

  /**  (button) */
  get elementButton3(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: '', exact: true }), ' (button)');
  }

  /** yyyy-dd-mm (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get yyyyDdMmInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(1), 'yyyy-dd-mm (input)');
  }

  /** yyyy-dd-mm (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get yyyyDdMmInput2(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(2), 'yyyy-dd-mm (input)');
  }

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Reset', exact: true }), 'Reset (button)');
  }

  /** Search (button) */
  get searchButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Search', exact: true }), 'Search (button)');
  }

  /** table (table) */
  // UNSTABLE: table has no accessible name; positional index used
  get tableTable(): TableComponent {
    return new TableComponent(this.page.getByRole('table').nth(0), [], 'table (table)');
  }

  /** Elements revealed by opening 'mandaa king'. Open the trigger first. */
  readonly mandaaKingOpen = new MyLeaveListPageMandaaKingOpen(this.page);

  /** Elements revealed by opening 'Select'. Open the trigger first. */
  readonly selectOpen = new MyLeaveListPageSelectOpen(this.page);

  /** Elements revealed by opening '-- Select --'. Open the trigger first. */
  readonly selectOpen2 = new MyLeaveListPageSelectOpen2(this.page);
}

/** Only present while 'mandaa king' is open. */
export class MyLeaveListPageMandaaKingOpen {
  constructor(private readonly page: Page) {}

  /** About (menuItem) */
  get aboutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'About', exact: true }), 'About (menuItem)');
  }

  /** Support (menuItem) */
  get supportMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Support', exact: true }), 'Support (menuItem)');
  }

  /** Change Password (menuItem) */
  get changePasswordMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Change Password', exact: true }), 'Change Password (menuItem)');
  }

  /** Logout (menuItem) */
  get logoutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Logout', exact: true }), 'Logout (menuItem)');
  }
}

/** Only present while 'Select' is open. */
export class MyLeaveListPageSelectOpen {
  constructor(private readonly page: Page) {}

  /** Rejected (dropdown) */
  get rejectedOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Rejected', exact: true }), 'Rejected (dropdown)');
  }

  /** Cancelled (dropdown) */
  get cancelledOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Cancelled', exact: true }), 'Cancelled (dropdown)');
  }

  /** Pending Approval (dropdown) */
  get pendingApprovalOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Pending Approval', exact: true }), 'Pending Approval (dropdown)');
  }

  /** Scheduled (dropdown) */
  get scheduledOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Scheduled', exact: true }), 'Scheduled (dropdown)');
  }

  /** Taken (dropdown) */
  get takenOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Taken', exact: true }), 'Taken (dropdown)');
  }
}

/** Only present while '-- Select --' is open. */
export class MyLeaveListPageSelectOpen2 {
  constructor(private readonly page: Page) {}

  /** -- Select -- (dropdown) */
  get selectOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: '-- Select --', exact: true }), '-- Select -- (dropdown)');
  }

  /** CAN - Bereavement (dropdown) */
  get cANBereavementOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'CAN - Bereavement', exact: true }), 'CAN - Bereavement (dropdown)');
  }

  /** US - Bereavement (dropdown) */
  get uSBereavementOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'US - Bereavement', exact: true }), 'US - Bereavement (dropdown)');
  }

  /** US - FMLA (dropdown) */
  get uSFMLAOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'US - FMLA', exact: true }), 'US - FMLA (dropdown)');
  }

  /** US - Personal (dropdown) */
  get uSPersonalOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'US - Personal', exact: true }), 'US - Personal (dropdown)');
  }

  /** US - Vacation (dropdown) */
  get uSVacationOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'US - Vacation', exact: true }), 'US - Vacation (dropdown)');
  }
}
