// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: leave_view_my_leave_entitlement
// Your own methods belong in MyLeaveEntitlementsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/leave/viewMyLeaveEntitlements */
export abstract class MyLeaveEntitlementsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/leave/viewMyLeaveEntitlements';

  constructor(page: Page) {
    super(page, MyLeaveEntitlementsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Search (button) */
  get searchButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Search');
  }

  /** Add (button) */
  get addButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Add');
  }

  /** Leave Type (dropdown) */
  get leaveTypeDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Leave Type');
  }

  /** Leave Period (dropdown) */
  get leavePeriodDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Leave Period');
  }
}
