// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('DirectoryPage', () => {
  test('loads', async ({ directoryPage }) => {
    await directoryPage.goto();
    await expect(directoryPage.page).toHaveURL(new RegExp('/web/index\\.php/directory/viewDirectory'));
  });
});
