// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('DisplayProjectReportCriteriaPage', () => {
  test('loads', async ({ displayProjectReportCriteriaPage }) => {
    await displayProjectReportCriteriaPage.goto();
    await expect(displayProjectReportCriteriaPage.timeHeading.locator).toBeVisible();
  });
});
