// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('SaveEventsPage', () => {
  test('loads', async ({ saveEventsPage }) => {
    await saveEventsPage.goto();
    await expect(saveEventsPage.page).toHaveURL(new RegExp('/web/index\\.php/claim/saveEvents/\\{id\\}'));
  });
});
