// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';
import { assertShape } from '../../../src/utils/schema-assert';

test.describe('Leave/Leave Balance — get-leave-balance-for-a-leave-type', () => {
  test('GET /api/v2/leave/leave-balance/leave-type/{leaveTypeId} responds 200', async ({ leaveLeaveBalanceApi }) => {
    const response = await leaveLeaveBalanceApi.getLeaveBalanceForALeaveType('REPLACE_ME' as never, {});
    expect(response.status()).toBe(200);
    const body = await response.json();
    assertShape(body, {"kind":"object","properties":[{"name":"data","type":"unknown","required":false,"nullable":false},{"name":"meta","type":"unknown","required":false,"nullable":false}]});
  });
});
