// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-claim-assignClaim
// Your own methods belong in AssignClaimPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { ImageComponent } from '../../components/ImageComponent';
import { InputComponent } from '../../components/InputComponent';
import { LinkComponent } from '../../components/LinkComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { OptionComponent } from '../../components/OptionComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/claim/assignClaim */
export abstract class AssignClaimPageGenerated extends BasePage {
  static readonly path = '/web/index.php/claim/assignClaim';

  constructor(page: Page) {
    super(page, AssignClaimPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Claim img (image) */
  // UNSTABLE: no accessible name; scoped to nearest named ancestor
  get claimImgImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('link', { name: 'Claim', exact: true }).getByRole('img'), 'Claim img (image)');
  }

  /** Claim (text) */
  get claimHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Claim', exact: true }), 'Claim (text)');
  }

  /** profile picture (image) */
  get profilePictureImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('img', { name: 'profile picture', exact: true }), 'profile picture (image)');
  }

  /** Submit Claim (link) */
  get submitClaimLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Submit Claim', exact: true }), 'Submit Claim (link)');
  }

  /** My Claims (link) */
  get myClaimsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'My Claims', exact: true }), 'My Claims (link)');
  }

  /** Employee Claims (link) */
  get employeeClaimsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Employee Claims', exact: true }), 'Employee Claims (link)');
  }

  /** Assign Claim (link) */
  get assignClaimLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Assign Claim', exact: true }), 'Assign Claim (link)');
  }

  /** Create Claim Request (text) */
  get createClaimRequestHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Create Claim Request', exact: true }), 'Create Claim Request (text)');
  }

  /** Type for hints... (input) */
  get typeForHintsInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'Type for hints...', exact: true }), 'Type for hints... (input)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(2), '(unnamed) (input)');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Cancel', exact: true }), 'Cancel (button)');
  }

  /** Create (button) */
  get createButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Create', exact: true }), 'Create (button)');
  }

  /** Elements revealed by opening 'Surya king'. Open the trigger first. */
  readonly suryaKingOpen = new AssignClaimPageSuryaKingOpen(this.page);

  /** Elements revealed by opening '-- Select --'. Open the trigger first. */
  readonly selectOpen = new AssignClaimPageSelectOpen(this.page);

  /** Elements revealed by opening '-- Select --'. Open the trigger first. */
  readonly selectOpen2 = new AssignClaimPageSelectOpen2(this.page);
}

/** Only present while 'Surya king' is open. */
export class AssignClaimPageSuryaKingOpen {
  constructor(private readonly page: Page) {}

  /** About (menuItem) */
  get aboutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'About', exact: true }), 'About (menuItem)');
  }

  /** Support (menuItem) */
  get supportMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Support', exact: true }), 'Support (menuItem)');
  }

  /** Change Password (menuItem) */
  get changePasswordMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Change Password', exact: true }), 'Change Password (menuItem)');
  }

  /** Logout (menuItem) */
  get logoutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Logout', exact: true }), 'Logout (menuItem)');
  }
}

/** Only present while '-- Select --' is open. */
export class AssignClaimPageSelectOpen {
  constructor(private readonly page: Page) {}

  /** -- Select -- (dropdown) */
  get selectOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: '-- Select --', exact: true }), '-- Select -- (dropdown)');
  }

  /** Accommodation (dropdown) */
  get accommodationOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Accommodation', exact: true }), 'Accommodation (dropdown)');
  }

  /** Medical Reimbursement (dropdown) */
  get medicalReimbursementOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Medical Reimbursement', exact: true }), 'Medical Reimbursement (dropdown)');
  }

  /** Travel Allowance (dropdown) */
  get travelAllowanceOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Travel Allowance', exact: true }), 'Travel Allowance (dropdown)');
  }
}

/** Only present while '-- Select --' is open. */
export class AssignClaimPageSelectOpen2 {
  constructor(private readonly page: Page) {}

  /** -- Select -- (dropdown) */
  get selectOption2(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: '-- Select --', exact: true }), '-- Select -- (dropdown)');
  }

  /** Afghanistan Afghani (dropdown) */
  get afghanistanAfghaniOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Afghanistan Afghani', exact: true }), 'Afghanistan Afghani (dropdown)');
  }

  /** Albanian Lek (dropdown) */
  get albanianLekOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Albanian Lek', exact: true }), 'Albanian Lek (dropdown)');
  }

  /** Algerian Dinar (dropdown) */
  get algerianDinarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Algerian Dinar', exact: true }), 'Algerian Dinar (dropdown)');
  }

  /** Angolan New Kwanza (dropdown) */
  get angolanNewKwanzaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Angolan New Kwanza', exact: true }), 'Angolan New Kwanza (dropdown)');
  }

  /** Argentina Pesos (dropdown) */
  get argentinaPesosOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Argentina Pesos', exact: true }), 'Argentina Pesos (dropdown)');
  }

  /** Argentine Peso (dropdown) */
  get argentinePesoOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Argentine Peso', exact: true }), 'Argentine Peso (dropdown)');
  }

  /** Aruban Florin (dropdown) */
  get arubanFlorinOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Aruban Florin', exact: true }), 'Aruban Florin (dropdown)');
  }

  /** Australian Dollar (dropdown) */
  get australianDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Australian Dollar', exact: true }), 'Australian Dollar (dropdown)');
  }

  /** Bahamian Dollar (dropdown) */
  get bahamianDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bahamian Dollar', exact: true }), 'Bahamian Dollar (dropdown)');
  }

  /** Bahraini Dinar (dropdown) */
  get bahrainiDinarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bahraini Dinar', exact: true }), 'Bahraini Dinar (dropdown)');
  }

  /** Bangladeshi Taka (dropdown) */
  get bangladeshiTakaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bangladeshi Taka', exact: true }), 'Bangladeshi Taka (dropdown)');
  }

  /** Barbados Dollar (dropdown) */
  get barbadosDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Barbados Dollar', exact: true }), 'Barbados Dollar (dropdown)');
  }

  /** Belize Dollar (dropdown) */
  get belizeDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Belize Dollar', exact: true }), 'Belize Dollar (dropdown)');
  }

  /** Bermudian Dollar (dropdown) */
  get bermudianDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bermudian Dollar', exact: true }), 'Bermudian Dollar (dropdown)');
  }

  /** Bhutan Ngultrum (dropdown) */
  get bhutanNgultrumOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bhutan Ngultrum', exact: true }), 'Bhutan Ngultrum (dropdown)');
  }

  /** Bolivian Boliviano (dropdown) */
  get bolivianBolivianoOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bolivian Boliviano', exact: true }), 'Bolivian Boliviano (dropdown)');
  }

  /** Botswana Pula (dropdown) */
  get botswanaPulaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Botswana Pula', exact: true }), 'Botswana Pula (dropdown)');
  }

  /** Brazilian Real (dropdown) */
  get brazilianRealOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Brazilian Real', exact: true }), 'Brazilian Real (dropdown)');
  }

  /** Brunei Dollar (dropdown) */
  get bruneiDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Brunei Dollar', exact: true }), 'Brunei Dollar (dropdown)');
  }

  /** Bulgarian Lev (dropdown) */
  get bulgarianLevOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bulgarian Lev', exact: true }), 'Bulgarian Lev (dropdown)');
  }

  /** Burundi Franc (dropdown) */
  get burundiFrancOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Burundi Franc', exact: true }), 'Burundi Franc (dropdown)');
  }

  /** Canadian Dollar (dropdown) */
  get canadianDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Canadian Dollar', exact: true }), 'Canadian Dollar (dropdown)');
  }

  /** Cape Verde Escudo (dropdown) */
  get capeVerdeEscudoOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Cape Verde Escudo', exact: true }), 'Cape Verde Escudo (dropdown)');
  }

  /** Cayman Islands Dollar (dropdown) */
  get caymanIslandsDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Cayman Islands Dollar', exact: true }), 'Cayman Islands Dollar (dropdown)');
  }

  /** CFA Franc BCEAO (dropdown) */
  get cFAFrancBCEAOOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'CFA Franc BCEAO', exact: true }), 'CFA Franc BCEAO (dropdown)');
  }

  /** CFA Franc BEAC (dropdown) */
  get cFAFrancBEACOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'CFA Franc BEAC', exact: true }), 'CFA Franc BEAC (dropdown)');
  }

  /** CFP Franc (dropdown) */
  get cFPFrancOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'CFP Franc', exact: true }), 'CFP Franc (dropdown)');
  }

  /** Chilean Peso (dropdown) */
  get chileanPesoOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Chilean Peso', exact: true }), 'Chilean Peso (dropdown)');
  }

  /** Chinese Yuan Renminbi (dropdown) */
  get chineseYuanRenminbiOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Chinese Yuan Renminbi', exact: true }), 'Chinese Yuan Renminbi (dropdown)');
  }

  /** Colombian Peso (dropdown) */
  get colombianPesoOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Colombian Peso', exact: true }), 'Colombian Peso (dropdown)');
  }

  /** Comoros Franc (dropdown) */
  get comorosFrancOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Comoros Franc', exact: true }), 'Comoros Franc (dropdown)');
  }

  /** Costa Rican Colon (dropdown) */
  get costaRicanColonOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Costa Rican Colon', exact: true }), 'Costa Rican Colon (dropdown)');
  }

  /** Croatian Kuna (dropdown) */
  get croatianKunaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Croatian Kuna', exact: true }), 'Croatian Kuna (dropdown)');
  }

  /** Cuban Peso (dropdown) */
  get cubanPesoOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Cuban Peso', exact: true }), 'Cuban Peso (dropdown)');
  }

  /** Cyprus Pound (dropdown) */
  get cyprusPoundOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Cyprus Pound', exact: true }), 'Cyprus Pound (dropdown)');
  }

  /** Czech Koruna (dropdown) */
  get czechKorunaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Czech Koruna', exact: true }), 'Czech Koruna (dropdown)');
  }

  /** Danish Krona (dropdown) */
  get danishKronaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Danish Krona', exact: true }), 'Danish Krona (dropdown)');
  }

  /** Djibouti Franc (dropdown) */
  get djiboutiFrancOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Djibouti Franc', exact: true }), 'Djibouti Franc (dropdown)');
  }

  /** Dominican Peso (dropdown) */
  get dominicanPesoOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Dominican Peso', exact: true }), 'Dominican Peso (dropdown)');
  }

  /** Eastern Caribbean Dollars (dropdown) */
  get easternCaribbeanDollarsOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Eastern Caribbean Dollars', exact: true }), 'Eastern Caribbean Dollars (dropdown)');
  }

  /** Ecuador Sucre (dropdown) */
  get ecuadorSucreOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Ecuador Sucre', exact: true }), 'Ecuador Sucre (dropdown)');
  }

  /** Egyptian Pound (dropdown) */
  get egyptianPoundOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Egyptian Pound', exact: true }), 'Egyptian Pound (dropdown)');
  }

  /** El Salvador Colon (dropdown) */
  get elSalvadorColonOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'El Salvador Colon', exact: true }), 'El Salvador Colon (dropdown)');
  }

  /** Estonian Krona (dropdown) */
  get estonianKronaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Estonian Krona', exact: true }), 'Estonian Krona (dropdown)');
  }

  /** Ethiopian Birr (dropdown) */
  get ethiopianBirrOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Ethiopian Birr', exact: true }), 'Ethiopian Birr (dropdown)');
  }

  /** Euro (dropdown) */
  get euroOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Euro', exact: true }), 'Euro (dropdown)');
  }

  /** Falkland Islands Pound (dropdown) */
  get falklandIslandsPoundOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Falkland Islands Pound', exact: true }), 'Falkland Islands Pound (dropdown)');
  }

  /** Fiji Dollar (dropdown) */
  get fijiDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Fiji Dollar', exact: true }), 'Fiji Dollar (dropdown)');
  }

  /** Gambian Dalasi (dropdown) */
  get gambianDalasiOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Gambian Dalasi', exact: true }), 'Gambian Dalasi (dropdown)');
  }

  /** Ghanaian Cedi (dropdown) */
  get ghanaianCediOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Ghanaian Cedi', exact: true }), 'Ghanaian Cedi (dropdown)');
  }

  /** Gibraltar Pound (dropdown) */
  get gibraltarPoundOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Gibraltar Pound', exact: true }), 'Gibraltar Pound (dropdown)');
  }

  /** Gold (oz.) (dropdown) */
  get goldOzOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Gold (oz.)', exact: true }), 'Gold (oz.) (dropdown)');
  }

  /** Guatemalan Quetzal (dropdown) */
  get guatemalanQuetzalOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Guatemalan Quetzal', exact: true }), 'Guatemalan Quetzal (dropdown)');
  }

  /** Guinea Franc (dropdown) */
  get guineaFrancOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Guinea Franc', exact: true }), 'Guinea Franc (dropdown)');
  }

  /** Guyanan Dollar (dropdown) */
  get guyananDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Guyanan Dollar', exact: true }), 'Guyanan Dollar (dropdown)');
  }

  /** Haitian Gourde (dropdown) */
  get haitianGourdeOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Haitian Gourde', exact: true }), 'Haitian Gourde (dropdown)');
  }

  /** Honduran Lempira (dropdown) */
  get honduranLempiraOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Honduran Lempira', exact: true }), 'Honduran Lempira (dropdown)');
  }

  /** Hong Kong Dollar (dropdown) */
  get hongKongDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Hong Kong Dollar', exact: true }), 'Hong Kong Dollar (dropdown)');
  }

  /** Hungarian Forint (dropdown) */
  get hungarianForintOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Hungarian Forint', exact: true }), 'Hungarian Forint (dropdown)');
  }

  /** Iceland Krona (dropdown) */
  get icelandKronaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Iceland Krona', exact: true }), 'Iceland Krona (dropdown)');
  }

  /** IMF Special Drawing Right (dropdown) */
  get iMFSpecialDrawingRightOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'IMF Special Drawing Right', exact: true }), 'IMF Special Drawing Right (dropdown)');
  }

  /** Indian Rupee (dropdown) */
  get indianRupeeOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Indian Rupee', exact: true }), 'Indian Rupee (dropdown)');
  }

  /** Indonesian Rupiah (dropdown) */
  get indonesianRupiahOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Indonesian Rupiah', exact: true }), 'Indonesian Rupiah (dropdown)');
  }

  /** Iranian Rial (dropdown) */
  get iranianRialOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Iranian Rial', exact: true }), 'Iranian Rial (dropdown)');
  }

  /** Iraqi Dinar (dropdown) */
  get iraqiDinarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Iraqi Dinar', exact: true }), 'Iraqi Dinar (dropdown)');
  }

  /** Israeli New Shekel (dropdown) */
  get israeliNewShekelOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Israeli New Shekel', exact: true }), 'Israeli New Shekel (dropdown)');
  }

  /** Jamaican Dollar (dropdown) */
  get jamaicanDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Jamaican Dollar', exact: true }), 'Jamaican Dollar (dropdown)');
  }

  /** Japanese Yen (dropdown) */
  get japaneseYenOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Japanese Yen', exact: true }), 'Japanese Yen (dropdown)');
  }

  /** Jordanian Dinar (dropdown) */
  get jordanianDinarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Jordanian Dinar', exact: true }), 'Jordanian Dinar (dropdown)');
  }

  /** Kampuchean Riel (dropdown) */
  get kampucheanRielOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Kampuchean Riel', exact: true }), 'Kampuchean Riel (dropdown)');
  }

  /** Kazakhstan Tenge (dropdown) */
  get kazakhstanTengeOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Kazakhstan Tenge', exact: true }), 'Kazakhstan Tenge (dropdown)');
  }

  /** Kenyan Shilling (dropdown) */
  get kenyanShillingOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Kenyan Shilling', exact: true }), 'Kenyan Shilling (dropdown)');
  }

  /** Korean Won (dropdown) */
  get koreanWonOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Korean Won', exact: true }), 'Korean Won (dropdown)');
  }

  /** Kuwaiti Dinar (dropdown) */
  get kuwaitiDinarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Kuwaiti Dinar', exact: true }), 'Kuwaiti Dinar (dropdown)');
  }

  /** Lao Kip (dropdown) */
  get laoKipOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Lao Kip', exact: true }), 'Lao Kip (dropdown)');
  }

  /** Latvian Lats (dropdown) */
  get latvianLatsOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Latvian Lats', exact: true }), 'Latvian Lats (dropdown)');
  }

  /** Lebanese Pound (dropdown) */
  get lebanesePoundOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Lebanese Pound', exact: true }), 'Lebanese Pound (dropdown)');
  }

  /** Lesotho Loti (dropdown) */
  get lesothoLotiOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Lesotho Loti', exact: true }), 'Lesotho Loti (dropdown)');
  }

  /** Liberian Dollar (dropdown) */
  get liberianDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Liberian Dollar', exact: true }), 'Liberian Dollar (dropdown)');
  }

  /** Libyan Dinar (dropdown) */
  get libyanDinarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Libyan Dinar', exact: true }), 'Libyan Dinar (dropdown)');
  }

  /** Lithuanian Litas (dropdown) */
  get lithuanianLitasOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Lithuanian Litas', exact: true }), 'Lithuanian Litas (dropdown)');
  }

  /** Macau Pataca (dropdown) */
  get macauPatacaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Macau Pataca', exact: true }), 'Macau Pataca (dropdown)');
  }

  /** Malagasy Franc (dropdown) */
  get malagasyFrancOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Malagasy Franc', exact: true }), 'Malagasy Franc (dropdown)');
  }

  /** Malawi Kwacha (dropdown) */
  get malawiKwachaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Malawi Kwacha', exact: true }), 'Malawi Kwacha (dropdown)');
  }

  /** Malaysian Ringgit (dropdown) */
  get malaysianRinggitOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Malaysian Ringgit', exact: true }), 'Malaysian Ringgit (dropdown)');
  }

  /** Maldive Rufiyaa (dropdown) */
  get maldiveRufiyaaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Maldive Rufiyaa', exact: true }), 'Maldive Rufiyaa (dropdown)');
  }

  /** Maltese Lira (dropdown) */
  get malteseLiraOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Maltese Lira', exact: true }), 'Maltese Lira (dropdown)');
  }

  /** Mauritanian Ouguiya (dropdown) */
  get mauritanianOuguiyaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Mauritanian Ouguiya', exact: true }), 'Mauritanian Ouguiya (dropdown)');
  }

  /** Mauritius Rupee (dropdown) */
  get mauritiusRupeeOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Mauritius Rupee', exact: true }), 'Mauritius Rupee (dropdown)');
  }

  /** Mexican New Peso (dropdown) */
  get mexicanNewPesoOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Mexican New Peso', exact: true }), 'Mexican New Peso (dropdown)');
  }

  /** Mexican Peso (dropdown) */
  get mexicanPesoOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Mexican Peso', exact: true }), 'Mexican Peso (dropdown)');
  }

  /** Mongolian Tugrik (dropdown) */
  get mongolianTugrikOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Mongolian Tugrik', exact: true }), 'Mongolian Tugrik (dropdown)');
  }

  /** Moroccan Dirham (dropdown) */
  get moroccanDirhamOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Moroccan Dirham', exact: true }), 'Moroccan Dirham (dropdown)');
  }

  /** Mozambique Metical (dropdown) */
  get mozambiqueMeticalOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Mozambique Metical', exact: true }), 'Mozambique Metical (dropdown)');
  }

  /** Myanmar Kyat (dropdown) */
  get myanmarKyatOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Myanmar Kyat', exact: true }), 'Myanmar Kyat (dropdown)');
  }

  /** Namibia Dollar (dropdown) */
  get namibiaDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Namibia Dollar', exact: true }), 'Namibia Dollar (dropdown)');
  }

  /** Nepalese Rupee (dropdown) */
  get nepaleseRupeeOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Nepalese Rupee', exact: true }), 'Nepalese Rupee (dropdown)');
  }

  /** New Zaire (dropdown) */
  get newZaireOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'New Zaire', exact: true }), 'New Zaire (dropdown)');
  }

  /** New Zealand Dollar (dropdown) */
  get newZealandDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'New Zealand Dollar', exact: true }), 'New Zealand Dollar (dropdown)');
  }

  /** Nicaraguan Cordoba Oro (dropdown) */
  get nicaraguanCordobaOroOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Nicaraguan Cordoba Oro', exact: true }), 'Nicaraguan Cordoba Oro (dropdown)');
  }

  /** Nigerian Naira (dropdown) */
  get nigerianNairaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Nigerian Naira', exact: true }), 'Nigerian Naira (dropdown)');
  }

  /** NL Antillian Guilder (dropdown) */
  get nLAntillianGuilderOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'NL Antillian Guilder', exact: true }), 'NL Antillian Guilder (dropdown)');
  }

  /** North Korean Won (dropdown) */
  get northKoreanWonOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'North Korean Won', exact: true }), 'North Korean Won (dropdown)');
  }

  /** Norwegian Krona (dropdown) */
  get norwegianKronaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Norwegian Krona', exact: true }), 'Norwegian Krona (dropdown)');
  }

  /** Omani Rial (dropdown) */
  get omaniRialOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Omani Rial', exact: true }), 'Omani Rial (dropdown)');
  }

  /** Pakistan Rupee (dropdown) */
  get pakistanRupeeOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Pakistan Rupee', exact: true }), 'Pakistan Rupee (dropdown)');
  }

  /** Palladium (oz.) (dropdown) */
  get palladiumOzOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Palladium (oz.)', exact: true }), 'Palladium (oz.) (dropdown)');
  }

  /** Panamanian Balboa (dropdown) */
  get panamanianBalboaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Panamanian Balboa', exact: true }), 'Panamanian Balboa (dropdown)');
  }

  /** Papua New Guinea Kina (dropdown) */
  get papuaNewGuineaKinaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Papua New Guinea Kina', exact: true }), 'Papua New Guinea Kina (dropdown)');
  }

  /** Paraguay Guarani (dropdown) */
  get paraguayGuaraniOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Paraguay Guarani', exact: true }), 'Paraguay Guarani (dropdown)');
  }

  /** Peruvian Nuevo Sol (dropdown) */
  get peruvianNuevoSolOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Peruvian Nuevo Sol', exact: true }), 'Peruvian Nuevo Sol (dropdown)');
  }

  /** Philippine Peso (dropdown) */
  get philippinePesoOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Philippine Peso', exact: true }), 'Philippine Peso (dropdown)');
  }

  /** Platinum (oz.) (dropdown) */
  get platinumOzOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Platinum (oz.)', exact: true }), 'Platinum (oz.) (dropdown)');
  }

  /** Polish Zloty (dropdown) */
  get polishZlotyOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Polish Zloty', exact: true }), 'Polish Zloty (dropdown)');
  }

  /** Pound Sterling (dropdown) */
  get poundSterlingOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Pound Sterling', exact: true }), 'Pound Sterling (dropdown)');
  }

  /** Qatari Rial (dropdown) */
  get qatariRialOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Qatari Rial', exact: true }), 'Qatari Rial (dropdown)');
  }

  /** Romanian Leu (dropdown) */
  get romanianLeuOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Romanian Leu', exact: true }), 'Romanian Leu (dropdown)');
  }

  /** Russia Rubles (dropdown) */
  get russiaRublesOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Russia Rubles', exact: true }), 'Russia Rubles (dropdown)');
  }

  /** Russian Rouble (dropdown) */
  get russianRoubleOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Russian Rouble', exact: true }), 'Russian Rouble (dropdown)');
  }

  /** Samoan Tala (dropdown) */
  get samoanTalaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Samoan Tala', exact: true }), 'Samoan Tala (dropdown)');
  }

  /** Sao Tome/Principe Dobra (dropdown) */
  get saoTomePrincipeDobraOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Sao Tome/Principe Dobra', exact: true }), 'Sao Tome/Principe Dobra (dropdown)');
  }

  /** Saudi Arabia Riyal (dropdown) */
  get saudiArabiaRiyalOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Saudi Arabia Riyal', exact: true }), 'Saudi Arabia Riyal (dropdown)');
  }

  /** Seychelles Rupee (dropdown) */
  get seychellesRupeeOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Seychelles Rupee', exact: true }), 'Seychelles Rupee (dropdown)');
  }

  /** Sierra Leone Leone (dropdown) */
  get sierraLeoneLeoneOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Sierra Leone Leone', exact: true }), 'Sierra Leone Leone (dropdown)');
  }

  /** Silver (oz.) (dropdown) */
  get silverOzOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Silver (oz.)', exact: true }), 'Silver (oz.) (dropdown)');
  }

  /** Singapore Dollar (dropdown) */
  get singaporeDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Singapore Dollar', exact: true }), 'Singapore Dollar (dropdown)');
  }

  /** Slovak Koruna (dropdown) */
  get slovakKorunaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Slovak Koruna', exact: true }), 'Slovak Koruna (dropdown)');
  }

  /** Solomon Islands Dollar (dropdown) */
  get solomonIslandsDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Solomon Islands Dollar', exact: true }), 'Solomon Islands Dollar (dropdown)');
  }

  /** Somali Shilling (dropdown) */
  get somaliShillingOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Somali Shilling', exact: true }), 'Somali Shilling (dropdown)');
  }

  /** South African Rand (dropdown) */
  get southAfricanRandOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'South African Rand', exact: true }), 'South African Rand (dropdown)');
  }

  /** Sri Lanka Rupee (dropdown) */
  get sriLankaRupeeOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Sri Lanka Rupee', exact: true }), 'Sri Lanka Rupee (dropdown)');
  }

  /** St. Helena Pound (dropdown) */
  get stHelenaPoundOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'St. Helena Pound', exact: true }), 'St. Helena Pound (dropdown)');
  }

  /** Sudanese Dinar (dropdown) */
  get sudaneseDinarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Sudanese Dinar', exact: true }), 'Sudanese Dinar (dropdown)');
  }

  /** Sudanese Pound (dropdown) */
  get sudanesePoundOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Sudanese Pound', exact: true }), 'Sudanese Pound (dropdown)');
  }

  /** Surinamese Dollar (dropdown) */
  get surinameseDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Surinamese Dollar', exact: true }), 'Surinamese Dollar (dropdown)');
  }

  /** Swaziland Lilangeni (dropdown) */
  get swazilandLilangeniOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Swaziland Lilangeni', exact: true }), 'Swaziland Lilangeni (dropdown)');
  }

  /** Swedish Krona (dropdown) */
  get swedishKronaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Swedish Krona', exact: true }), 'Swedish Krona (dropdown)');
  }

  /** Swiss Franc (dropdown) */
  get swissFrancOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Swiss Franc', exact: true }), 'Swiss Franc (dropdown)');
  }

  /** Syrian Pound (dropdown) */
  get syrianPoundOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Syrian Pound', exact: true }), 'Syrian Pound (dropdown)');
  }

  /** Taiwan Dollar (dropdown) */
  get taiwanDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Taiwan Dollar', exact: true }), 'Taiwan Dollar (dropdown)');
  }

  /** Tanzanian Shilling (dropdown) */
  get tanzanianShillingOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Tanzanian Shilling', exact: true }), 'Tanzanian Shilling (dropdown)');
  }

  /** Thai Baht (dropdown) */
  get thaiBahtOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Thai Baht', exact: true }), 'Thai Baht (dropdown)');
  }

  /** Tongan Pa'anga (dropdown) */
  get tonganPaAngaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Tongan Pa\'anga', exact: true }), 'Tongan Pa\'anga (dropdown)');
  }

  /** Trinidad/Tobago Dollar (dropdown) */
  get trinidadTobagoDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Trinidad/Tobago Dollar', exact: true }), 'Trinidad/Tobago Dollar (dropdown)');
  }

  /** Tunisian Dinar (dropdown) */
  get tunisianDinarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Tunisian Dinar', exact: true }), 'Tunisian Dinar (dropdown)');
  }

  /** Turkish Lira (dropdown) */
  get turkishLiraOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Turkish Lira', exact: true }), 'Turkish Lira (dropdown)');
  }

  /** Uganda Shilling (dropdown) */
  get ugandaShillingOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Uganda Shilling', exact: true }), 'Uganda Shilling (dropdown)');
  }

  /** Ukraine Hryvnia (dropdown) */
  get ukraineHryvniaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Ukraine Hryvnia', exact: true }), 'Ukraine Hryvnia (dropdown)');
  }

  /** United States Dollar (dropdown) */
  get unitedStatesDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'United States Dollar', exact: true }), 'United States Dollar (dropdown)');
  }

  /** Uruguayan Peso (dropdown) */
  get uruguayanPesoOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Uruguayan Peso', exact: true }), 'Uruguayan Peso (dropdown)');
  }

  /** Utd. Arab Emir. Dirham (dropdown) */
  get utdArabEmirDirhamOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Utd. Arab Emir. Dirham', exact: true }), 'Utd. Arab Emir. Dirham (dropdown)');
  }

  /** Vanuatu Vatu (dropdown) */
  get vanuatuVatuOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Vanuatu Vatu', exact: true }), 'Vanuatu Vatu (dropdown)');
  }

  /** Venezuelan Bolivar (dropdown) */
  get venezuelanBolivarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Venezuelan Bolivar', exact: true }), 'Venezuelan Bolivar (dropdown)');
  }

  /** Vietnamese Dong (dropdown) */
  get vietnameseDongOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Vietnamese Dong', exact: true }), 'Vietnamese Dong (dropdown)');
  }

  /** Yemeni Riyal (dropdown) */
  get yemeniRiyalOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Yemeni Riyal', exact: true }), 'Yemeni Riyal (dropdown)');
  }

  /** Yugoslav Dinar (dropdown) */
  get yugoslavDinarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Yugoslav Dinar', exact: true }), 'Yugoslav Dinar (dropdown)');
  }

  /** Yugoslavian Dinar (dropdown) */
  get yugoslavianDinarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Yugoslavian Dinar', exact: true }), 'Yugoslavian Dinar (dropdown)');
  }

  /** Zambian Kwacha (dropdown) */
  get zambianKwachaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Zambian Kwacha', exact: true }), 'Zambian Kwacha (dropdown)');
  }

  /** Zimbabwe Dollar (dropdown) */
  get zimbabweDollarOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Zimbabwe Dollar', exact: true }), 'Zimbabwe Dollar (dropdown)');
  }
}
