// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-claim-viewAssignClaim
// Your own methods belong in ClaimAssignClaimPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { ImageComponent } from '../../components/ImageComponent';
import { InputComponent } from '../../components/InputComponent';
import { LinkComponent } from '../../components/LinkComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { OptionComponent } from '../../components/OptionComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/claim/viewAssignClaim */
export abstract class ClaimAssignClaimPageGenerated extends BasePage {
  static readonly path = '/web/index.php/claim/viewAssignClaim';

  constructor(page: Page) {
    super(page, ClaimAssignClaimPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Claim img (image) */
  // UNSTABLE: no accessible name; scoped to nearest named ancestor
  get claimImgImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('link', { name: 'Claim', exact: true }).getByRole('img'), 'Claim img (image)');
  }

  /** Claim (text) */
  get claimHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Claim', exact: true }), 'Claim (text)');
  }

  /** profile picture (image) */
  get profilePictureImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('img', { name: 'profile picture', exact: true }), 'profile picture (image)');
  }

  /** Submit Claim (link) */
  get submitClaimLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Submit Claim', exact: true }), 'Submit Claim (link)');
  }

  /** My Claims (link) */
  get myClaimsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'My Claims', exact: true }), 'My Claims (link)');
  }

  /** Employee Claims (link) */
  get employeeClaimsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Employee Claims', exact: true }), 'Employee Claims (link)');
  }

  /** Assign Claim (link) */
  get assignClaimLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Assign Claim', exact: true }), 'Assign Claim (link)');
  }

  /** Employee Claims (text) */
  get employeeClaimsHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Employee Claims', exact: true }), 'Employee Claims (text)');
  }

  /**  (button) */
  get elementButton3(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: '', exact: true }), ' (button)');
  }

  /** Type for hints... (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get typeForHintsInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(1), 'Type for hints... (input)');
  }

  /** Type for hints... (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get typeForHintsInput2(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(2), 'Type for hints... (input)');
  }

  /** yyyy-dd-mm (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get yyyyDdMmInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(3), 'yyyy-dd-mm (input)');
  }

  /** yyyy-dd-mm (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get yyyyDdMmInput2(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(4), 'yyyy-dd-mm (input)');
  }

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Reset', exact: true }), 'Reset (button)');
  }

  /** Search (button) */
  get searchButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Search', exact: true }), 'Search (button)');
  }

  /**  Assign Claim (button) */
  get assignClaimButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: ' Assign Claim', exact: true }), ' Assign Claim (button)');
  }

  /** table (table) */
  // UNSTABLE: table has no accessible name; positional index used
  get tableTable(): TableComponent {
    return new TableComponent(this.page.getByRole('table').nth(0), [], 'table (table)');
  }

  /** Elements revealed by opening 'mandaa king'. Open the trigger first. */
  readonly mandaaKingOpen = new ClaimAssignClaimPageMandaaKingOpen(this.page);

  /** Elements revealed by opening '-- Select --'. Open the trigger first. */
  readonly selectOpen = new ClaimAssignClaimPageSelectOpen(this.page);

  /** Elements revealed by opening '-- Select --'. Open the trigger first. */
  readonly selectOpen2 = new ClaimAssignClaimPageSelectOpen2(this.page);

  /** Elements revealed by opening 'Current Employees Only'. Open the trigger first. */
  readonly currentEmployeesOnlyOpen = new ClaimAssignClaimPageCurrentEmployeesOnlyOpen(this.page);
}

/** Only present while 'mandaa king' is open. */
export class ClaimAssignClaimPageMandaaKingOpen {
  constructor(private readonly page: Page) {}

  /** About (menuItem) */
  get aboutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'About', exact: true }), 'About (menuItem)');
  }

  /** Support (menuItem) */
  get supportMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Support', exact: true }), 'Support (menuItem)');
  }

  /** Change Password (menuItem) */
  get changePasswordMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Change Password', exact: true }), 'Change Password (menuItem)');
  }

  /** Logout (menuItem) */
  get logoutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Logout', exact: true }), 'Logout (menuItem)');
  }
}

/** Only present while '-- Select --' is open. */
export class ClaimAssignClaimPageSelectOpen {
  constructor(private readonly page: Page) {}

  /** No Records Found (dropdown) */
  get noRecordsFoundOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'No Records Found', exact: true }), 'No Records Found (dropdown)');
  }
}

/** Only present while '-- Select --' is open. */
export class ClaimAssignClaimPageSelectOpen2 {
  constructor(private readonly page: Page) {}

  /** -- Select -- (dropdown) */
  get selectOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: '-- Select --', exact: true }), '-- Select -- (dropdown)');
  }

  /** Initiated (dropdown) */
  get initiatedOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Initiated', exact: true }), 'Initiated (dropdown)');
  }

  /** Submitted (dropdown) */
  get submittedOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Submitted', exact: true }), 'Submitted (dropdown)');
  }

  /** Approved (dropdown) */
  get approvedOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Approved', exact: true }), 'Approved (dropdown)');
  }

  /** Rejected (dropdown) */
  get rejectedOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Rejected', exact: true }), 'Rejected (dropdown)');
  }

  /** Cancelled (dropdown) */
  get cancelledOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Cancelled', exact: true }), 'Cancelled (dropdown)');
  }

  /** Paid (dropdown) */
  get paidOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Paid', exact: true }), 'Paid (dropdown)');
  }
}

/** Only present while 'Current Employees Only' is open. */
export class ClaimAssignClaimPageCurrentEmployeesOnlyOpen {
  constructor(private readonly page: Page) {}

  /** Current Employees Only (dropdown) */
  get currentEmployeesOnlyOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Current Employees Only', exact: true }), 'Current Employees Only (dropdown)');
  }

  /** Current and Past Employees (dropdown) */
  get currentAndPastEmployeesOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Current and Past Employees', exact: true }), 'Current and Past Employees (dropdown)');
  }

  /** Past Employees Only (dropdown) */
  get pastEmployeesOnlyOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Past Employees Only', exact: true }), 'Past Employees Only (dropdown)');
  }
}
