// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-claim-viewAssignClaim
// Your own methods belong in ClaimAssignClaimPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/claim/viewAssignClaim */
export abstract class ClaimAssignClaimPageGenerated extends BasePage {
  static readonly path = '/web/index.php/claim/viewAssignClaim';

  constructor(page: Page) {
    super(page, ClaimAssignClaimPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Submit Claim (menuItem) */
  get submitClaimMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Submit Claim');
  }

  /** My Claims (menuItem) */
  get myClaimsMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'My Claims');
  }

  /** Employee Claims (menuItem) */
  get employeeClaimsMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Employee Claims');
  }

  /** Assign Claim (menuItem) */
  get assignClaimMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Assign Claim');
  }

  /** Employee Claims (text) */
  get employeeClaimsHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Employee Claims');
  }

  /** Assign Claim (button) */
  get assignClaimButton(): ButtonComponent {
    return new ButtonComponent(this.page.locator('.orangehrm-header-container button:has-text("Assign Claim")'), 'Assign Claim (button)');
  }

  /** Employee Name (input) */
  get employeeNameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Employee Name');
  }

  /** Reference Id (input) */
  get referenceIdInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Reference Id');
  }

  /** Event Name (dropdown) */
  get eventNameDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Event Name');
  }

  /** Status (dropdown) */
  get statusDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Status');
  }

  /** From Date (input) */
  get fromDateInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'From Date');
  }

  /** To Date (input) */
  get toDateInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'To Date');
  }

  /** Include (dropdown) */
  get includeDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Include');
  }

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Reset');
  }

  /** Search (button) */
  get searchButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Search');
  }

  /** Records Found (text) */
  get recordsFoundHeading(): TextComponent {
    return new TextComponent(this.page.locator('.orangehrm-horizontal-padding > .oxd-text:has-text("Records Found")'), 'Records Found (text)');
  }

  /** Employee Claims (table) */
  get employeeClaimsTable(): TableComponent {
    return new TableComponent(this.page.locator('.oxd-table'), ['Reference Id', 'Employee Name', 'Event Name', 'Description', 'Currency', 'Submitted Date', 'Status', 'Amount', 'Actions'], 'Employee Claims (table)');
  }
}
