// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-claim-viewEvents
// Your own methods belong in EventsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { CheckboxComponent } from '../../components/CheckboxComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/claim/viewEvents */
export abstract class EventsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/claim/viewEvents';

  constructor(page: Page) {
    super(page, EventsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Submit Claim (menuItem) */
  get submitClaimMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Submit Claim');
  }

  /** My Claims (menuItem) */
  get myClaimsMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'My Claims');
  }

  /** Employee Claims (menuItem) */
  get employeeClaimsMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Employee Claims');
  }

  /** Assign Claim (menuItem) */
  get assignClaimMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Assign Claim');
  }

  /** Events (text) */
  get eventsHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Events');
  }

  /** Add (button) */
  get addButton(): ButtonComponent {
    return new ButtonComponent(this.page.locator('.orangehrm-header-container button:has-text("Add")'), 'Add (button)');
  }

  /** Event Name (input) */
  get eventNameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Event Name');
  }

  /** Status (dropdown) */
  get statusDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Status');
  }

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Reset');
  }

  /** Search (button) */
  get searchButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Search');
  }

  /** Records Found (text) */
  get recordsFoundHeading(): TextComponent {
    return new TextComponent(this.page.locator('.orangehrm-horizontal-padding > .oxd-text:has-text("Records Found")'), 'Records Found (text)');
  }

  /** Select all (checkbox) */
  get selectAllCheckbox(): CheckboxComponent {
    return new CheckboxComponent(this.page.locator('.oxd-table-header .oxd-checkbox-input'), 'Select all (checkbox)');
  }

  /** Events (table) */
  get eventsTable(): TableComponent {
    return new TableComponent(this.page.locator('.oxd-table'), ['Event Name', 'Status', 'Actions'], 'Events (table)');
  }
}
