// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: claim_attachment
// Your own methods belong in RequestsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/claim/requests/{requestId}/attachId/{attachId} (also reachable at /web/index.php/claim/viewClaimModule) */
export abstract class RequestsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/claim/requests/{requestId}/attachId/{attachId}';
  static readonly aliases = ['/web/index.php/claim/viewClaimModule'] as const;

  constructor(page: Page) {
    super(page, RequestsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);
}
