// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: claim_edit_claim_events
// Your own methods belong in SaveEventsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/claim/saveEvents/{id} (also reachable at /web/index.php/claim/saveEvents) */
export abstract class SaveEventsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/claim/saveEvents/{id}';
  static readonly aliases = ['/web/index.php/claim/saveEvents'] as const;

  constructor(page: Page) {
    super(page, SaveEventsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Event Name (input) */
  get eventNameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Event Name');
  }

  /** Description (longInput) */
  get descriptionLongInput(): InputComponent {
    return InputComponent.textareaByLabel(this.page, 'Description');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
