// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-claim-submitClaim
// Your own methods belong in SubmitClaimPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/claim/submitClaim */
export abstract class SubmitClaimPageGenerated extends BasePage {
  static readonly path = '/web/index.php/claim/submitClaim';

  constructor(page: Page) {
    super(page, SubmitClaimPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Configuration (menuItem) */
  get configurationMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Configuration")'), 'Configuration (menuItem)');
  }

  /** Submit Claim (menuItem) */
  get submitClaimMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Submit Claim');
  }

  /** My Claims (menuItem) */
  get myClaimsMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'My Claims');
  }

  /** Employee Claims (menuItem) */
  get employeeClaimsMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Employee Claims');
  }

  /** Assign Claim (menuItem) */
  get assignClaimMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Assign Claim');
  }

  /** Create Claim Request (text) */
  get createClaimRequestHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Create Claim Request');
  }

  /** Event (dropdown) */
  get eventDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Event');
  }

  /** Currency (dropdown) */
  get currencyDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Currency');
  }

  /** Remarks (longInput) */
  get remarksTextArea(): InputComponent {
    return InputComponent.textareaByLabel(this.page, 'Remarks');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }

  /** Create (button) */
  get createButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Create');
  }

  /** Claim (text) */
  get claimHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Claim');
  }
}
