// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: claim_submit_claim
// Your own methods belong in SubmitClaimPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/claim/submitClaim */
export abstract class SubmitClaimPageGenerated extends BasePage {
  static readonly path = '/web/index.php/claim/submitClaim';

  constructor(page: Page) {
    super(page, SubmitClaimPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Currency (dropdown) */
  get currencyDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Currency');
  }

  /** Remarks (longInput) */
  get remarksLongInput(): InputComponent {
    return InputComponent.textareaByLabel(this.page, 'Remarks');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }

  /** Event (dropdown) */
  get eventDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Event');
  }

  /** Create (button) */
  get createButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Create');
  }
}
