// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('DefinePredefinedReportPage', () => {
  test('loads', async ({ definePredefinedReportPage }) => {
    await definePredefinedReportPage.goto();
    await expect(definePredefinedReportPage.page).toHaveURL(new RegExp('/web/index\\.php/pim/definePredefinedReport/\\{id\\}'));
  });
});
