// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('DefinedPredefinedReportsPage', () => {
  test('loads', async ({ definedPredefinedReportsPage }) => {
    await definedPredefinedReportsPage.goto();
    await expect(definedPredefinedReportsPage.employeeReportsHeading.locator).toBeVisible();
  });
});
