// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('DependentsPage', () => {
  test('loads', async ({ dependentsPage }) => {
    await dependentsPage.goto();
    await expect(dependentsPage.page).toHaveURL(new RegExp('/web/index\\.php/pim/viewDependents/empNumber/\\{empNumber\\}'));
  });
});
