// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('ReviewEvaluatePage', () => {
  test('loads', async ({ reviewEvaluatePage }) => {
    await reviewEvaluatePage.goto();
    await expect(reviewEvaluatePage.page).toHaveURL(new RegExp('/web/index\\.php/performance/reviewEvaluate/id/\\{id\\}'));
  });
});
