// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('SearchPerformanceReviewPage', () => {
  test('loads', async ({ searchPerformanceReviewPage }) => {
    await searchPerformanceReviewPage.goto();
    await expect(searchPerformanceReviewPage.performanceHeading.locator).toBeVisible();
  });
});
