// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: performance_employee_tracker
// Your own methods belong in EmployeePerformanceTrackerListPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/performance/viewEmployeePerformanceTrackerList */
export abstract class EmployeePerformanceTrackerListPageGenerated extends BasePage {
  static readonly path = '/web/index.php/performance/viewEmployeePerformanceTrackerList';

  constructor(page: Page) {
    super(page, EmployeePerformanceTrackerListPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Reset');
  }

  /** Search (button) */
  get searchButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Search');
  }

  /** Employee Name (table) */
  get employeeNameTable(): TableComponent {
    return TableComponent.byColumn(this.page, 'Employee Name', ['Employee Name', 'Trackers', 'Added Date', 'Modified Date', 'Actions']);
  }

  /** Employee Name (input) */
  get employeeNameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Employee Name');
  }

  /** Include (dropdown) */
  get includeDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Include');
  }

  /** Delete Selected (button) */
  get deleteSelectedButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Delete Selected');
  }
}
