// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: performance_my_trackers
// Your own methods belong in MyPerformanceTrackerListPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/performance/viewMyPerformanceTrackerList */
export abstract class MyPerformanceTrackerListPageGenerated extends BasePage {
  static readonly path = '/web/index.php/performance/viewMyPerformanceTrackerList';

  constructor(page: Page) {
    super(page, MyPerformanceTrackerListPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Tracker (table) */
  get trackerTable(): TableComponent {
    return TableComponent.byColumn(this.page, 'Tracker', ['Tracker', 'Added Date', 'Modified Date', 'Actions']);
  }

  /** My Performance Trackers (button) */
  get myPerformanceTrackersButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'My Performance Trackers');
  }
}
