// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: performance_kpi_edit
// Your own methods belong in SaveKpiPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/performance/saveKpi/{id} (also reachable at /web/index.php/performance/saveKpi) */
export abstract class SaveKpiPageGenerated extends BasePage {
  static readonly path = '/web/index.php/performance/saveKpi/{id}';
  static readonly aliases = ['/web/index.php/performance/saveKpi'] as const;

  constructor(page: Page) {
    super(page, SaveKpiPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Key Performance Indicator (input) */
  get keyPerformanceIndicatorInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Key Performance Indicator');
  }

  /** Minimum Rating (input) */
  get minimumRatingInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Minimum Rating');
  }

  /** Maximum Rating (input) */
  get maximumRatingInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Maximum Rating');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }

  /** Job Title (dropdown) */
  get jobTitleDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Job Title');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
