// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: performance_review_edit
// Your own methods belong in SaveReviewPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/performance/saveReview/{id} (also reachable at /web/index.php/performance/saveReview) */
export abstract class SaveReviewPageGenerated extends BasePage {
  static readonly path = '/web/index.php/performance/saveReview/{id}';
  static readonly aliases = ['/web/index.php/performance/saveReview'] as const;

  constructor(page: Page) {
    super(page, SaveReviewPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }

  /** Activate (button) */
  get activateButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Activate');
  }

  /** Employee Name (input) */
  get employeeNameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Employee Name');
  }

  /** Review Period Start Date (input) */
  get reviewPeriodStartDateInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Review Period Start Date');
  }

  /** Review Period End Date (input) */
  get reviewPeriodEndDateInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Review Period End Date');
  }

  /** Due Date (input) */
  get dueDateInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Due Date');
  }
}
