// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-performance-searchEvaluatePerformanceReview
// Your own methods belong in SearchEvaluatePerformanceReviewPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/performance/searchEvaluatePerformanceReview */
export abstract class SearchEvaluatePerformanceReviewPageGenerated extends BasePage {
  static readonly path = '/web/index.php/performance/searchEvaluatePerformanceReview';

  constructor(page: Page) {
    super(page, SearchEvaluatePerformanceReviewPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Configure (menuItem) */
  get configureMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Configure")'), 'Configure (menuItem)');
  }

  /** Manage Reviews (menuItem) */
  get manageReviewsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Manage Reviews")'), 'Manage Reviews (menuItem)');
  }

  /** My Trackers (menuItem) */
  get myTrackersMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'My Trackers');
  }

  /** Employee Trackers (menuItem) */
  get employeeTrackersMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Employee Trackers');
  }

  /** Performance (text) */
  get performanceHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Performance');
  }

  /** Employee Reviews (text) */
  get employeeReviewsHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Employee Reviews');
  }

  /** Employee Name (input) */
  get employeeNameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Employee Name');
  }

  /** Job Title (dropdown) */
  get jobTitleDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Job Title');
  }

  /** Sub Unit (dropdown) */
  get subUnitDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Sub Unit');
  }

  /** Include (dropdown) */
  get includeDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Include');
  }

  /** Review Status (dropdown) */
  get reviewStatusDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Review Status');
  }

  /** From Date (input) */
  get fromDateInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'From Date');
  }

  /** To Date (input) */
  get toDateInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'To Date');
  }

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Reset');
  }

  /** Search (button) */
  get searchButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Search');
  }

  /** Records (table) */
  get recordsTable(): TableComponent {
    return new TableComponent(this.page.locator('.oxd-table:has(.oxd-table-th:text-is("Employee"))'), ['Employee', 'Job Title', 'Sub Unit', 'Review Period', 'Due Date', 'Review Status', 'Actions'], 'Records (table)');
  }
}
