// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';
import { assertShape } from '../../../src/utils/schema-assert';

test.describe('PIM/Employee Licenses — add-a-license-to-an-employee', () => {
  test('POST /api/v2/pim/employees/{empNumber}/licenses responds 200', async ({ pimEmployeeLicensesApi }) => {
    // TODO: fill in a valid request body.
    const response = await pimEmployeeLicensesApi.addALicenseToAnEmployee('REPLACE_ME' as never, {} as never);
    expect(response.status()).toBe(200);
    const body = await response.json();
    assertShape(body, {"kind":"object","properties":[{"name":"data","type":"unknown","required":false,"nullable":false},{"name":"empNumber","type":"number","required":false,"nullable":false}]});
  });
});
