// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';
import { assertShape } from '../../../src/utils/schema-assert';

test.describe('PIM/Employee Licenses — get-an-employees-license', () => {
  test('GET /api/v2/pim/employees/{empNumber}/licenses/{id} responds 200', async ({ pimEmployeeLicensesApi }) => {
    const response = await pimEmployeeLicensesApi.getAnEmployeesLicense('REPLACE_ME' as never, 'REPLACE_ME' as never);
    expect(response.status()).toBe(200);
    const body = await response.json();
    assertShape(body, {"kind":"object","properties":[{"name":"data","type":"unknown","required":false,"nullable":false},{"name":"meta","type":"unknown","required":false,"nullable":false}]});
  });
});
