// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';
import { assertShape } from '../../../src/utils/schema-assert';

test.describe('Attendance/Employee Attendance — create-an-employees-attendance-record', () => {
  test('POST /api/v2/attendance/employees/{empNumber}/records responds 200', async ({ attendanceEmployeeAttendanceApi }) => {
    // TODO: fill in a valid request body.
    const response = await attendanceEmployeeAttendanceApi.createAnEmployeesAttendanceRecord('REPLACE_ME' as never, {} as never);
    expect(response.status()).toBe(200);
    const body = await response.json();
    assertShape(body, {"kind":"object","properties":[{"name":"data","type":"unknown","required":false,"nullable":false},{"name":"meta","type":"unknown","required":false,"nullable":false}]});
  });
});
