// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';
import { assertShape } from '../../../src/utils/schema-assert';

test.describe('Maintenance/Purge Employee — purge-employee', () => {
  test('DELETE /api/v2/maintenance/purge responds 200', async ({ maintenancePurgeEmployeeApi }) => {
    // TODO: fill in a valid request body.
    const response = await maintenancePurgeEmployeeApi.purgeEmployee({} as never);
    expect(response.status()).toBe(200);
    const body = await response.json();
    assertShape(body, {"kind":"object","properties":[{"name":"data","type":"unknown","required":false,"nullable":false},{"name":"meta","type":"unknown","required":false,"nullable":false}]});
  });
});
