// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('AuthPage', () => {
  test('loads', async ({ authPage }) => {
    await authPage.goto();
    await expect(authPage.page).toHaveURL(new RegExp('/web/index\\.php/functional-testing/auth/validate'));
  });
});
