// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-pim-configurePim
// Your own methods belong in ConfigurePimPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/configurePim */
export abstract class ConfigurePimPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/configurePim';

  constructor(page: Page) {
    super(page, ConfigurePimPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Configuration (menuItem) */
  get configurationMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Configuration")'), 'Configuration (menuItem)');
  }

  /** Employee List (menuItem) */
  get employeeListMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Employee List');
  }

  /** Add Employee (menuItem) */
  get addEmployeeMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Add Employee');
  }

  /** Reports (menuItem) */
  get reportsMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Reports');
  }

  /** PIM (text) */
  get pimHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'PIM');
  }

  /** Show Deprecated Fields (text) */
  get showDeprecatedFieldsHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Show Deprecated Fields');
  }

  /** Country Specific Information (text) */
  get countrySpecificInformationHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Country Specific Information');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
