// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-pim-contactDetails-empNumber-7
// Your own methods belong in ContactDetailsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { CheckboxComponent } from '../../components/CheckboxComponent';
import { ImageComponent } from '../../components/ImageComponent';
import { InputComponent } from '../../components/InputComponent';
import { LinkComponent } from '../../components/LinkComponent';
import { RadioComponent } from '../../components/RadioComponent';
import { TabComponent } from '../../components/TabComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/contactDetails/empNumber/7 */
export abstract class ContactDetailsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/contactDetails/empNumber/7';

  constructor(page: Page) {
    super(page, ContactDetailsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Claim img (image) */
  // UNSTABLE: no accessible name; scoped to nearest named ancestor
  get claimImgImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('link', { name: 'Claim', exact: true }).getByRole('img'), 'Claim img (image)');
  }

  /** PIM (text) */
  get pIMHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'PIM', exact: true }), 'PIM (text)');
  }

  /** profile picture (image) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get profilePictureImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('img').nth(2), 'profile picture (image)');
  }

  /** gb yasuser (text) */
  get gbYasuserHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'gb yasuser', exact: true }), 'gb yasuser (text)');
  }

  /** profile picture (image) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get profilePictureImage2(): ImageComponent {
    return new ImageComponent(this.page.getByRole('img').nth(3), 'profile picture (image)');
  }

  /** Personal Details (tab) */
  get personalDetailsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Personal Details', exact: true }), 'Personal Details (tab)');
  }

  /** Personal Details (link) */
  get personalDetailsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Personal Details', exact: true }), 'Personal Details (link)');
  }

  /** Contact Details (tab) */
  get contactDetailsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Contact Details', exact: true }), 'Contact Details (tab)');
  }

  /** Contact Details (link) */
  get contactDetailsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Contact Details', exact: true }), 'Contact Details (link)');
  }

  /** Emergency Contacts (tab) */
  get emergencyContactsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Emergency Contacts', exact: true }), 'Emergency Contacts (tab)');
  }

  /** Emergency Contacts (link) */
  get emergencyContactsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Emergency Contacts', exact: true }), 'Emergency Contacts (link)');
  }

  /** Dependents (tab) */
  get dependentsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Dependents', exact: true }), 'Dependents (tab)');
  }

  /** Dependents (link) */
  get dependentsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Dependents', exact: true }), 'Dependents (link)');
  }

  /** Immigration (tab) */
  get immigrationTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Immigration', exact: true }), 'Immigration (tab)');
  }

  /** Immigration (link) */
  get immigrationLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Immigration', exact: true }), 'Immigration (link)');
  }

  /** Job (tab) */
  get jobTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Job', exact: true }), 'Job (tab)');
  }

  /** Job (link) */
  get jobLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Job', exact: true }), 'Job (link)');
  }

  /** Salary (tab) */
  get salaryTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Salary', exact: true }), 'Salary (tab)');
  }

  /** Salary (link) */
  get salaryLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Salary', exact: true }), 'Salary (link)');
  }

  /** Report-to (tab) */
  get reportToTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Report-to', exact: true }), 'Report-to (tab)');
  }

  /** Report-to (link) */
  get reportToLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Report-to', exact: true }), 'Report-to (link)');
  }

  /** Qualifications (tab) */
  get qualificationsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Qualifications', exact: true }), 'Qualifications (tab)');
  }

  /** Qualifications (link) */
  get qualificationsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Qualifications', exact: true }), 'Qualifications (link)');
  }

  /** Memberships (tab) */
  get membershipsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Memberships', exact: true }), 'Memberships (tab)');
  }

  /** Memberships (link) */
  get membershipsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Memberships', exact: true }), 'Memberships (link)');
  }

  /** Contact Details (text) */
  get contactDetailsHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Contact Details', exact: true }), 'Contact Details (text)');
  }

  /** Address (text) */
  get addressHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Address', exact: true }), 'Address (text)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(1), '(unnamed) (input)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput2(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(2), '(unnamed) (input)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput3(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(3), '(unnamed) (input)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput4(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(4), '(unnamed) (input)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput5(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(5), '(unnamed) (input)');
  }

  /** Telephone (text) */
  get telephoneHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Telephone', exact: true }), 'Telephone (text)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput6(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(6), '(unnamed) (input)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput7(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(7), '(unnamed) (input)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput8(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(8), '(unnamed) (input)');
  }

  /** Email (text) */
  get emailHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Email', exact: true }), 'Email (text)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput9(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(9), '(unnamed) (input)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput10(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(10), '(unnamed) (input)');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Save', exact: true }), 'Save (button)');
  }

  /** Attachments (text) */
  get attachmentsHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Attachments', exact: true }), 'Attachments (text)');
  }

  /**  Add (button) */
  get addButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: ' Add', exact: true }), ' Add (button)');
  }

  /** Table (, File Name, Description, Size, Type, Date Added, Added By, Actions; 1 row(s)) (table) */
  // UNSTABLE: table has no accessible name; positional index used
  get tableTable(): TableComponent {
    return new TableComponent(this.page.getByRole('table').nth(0), ['', 'File Name', 'Description', 'Size', 'Type', 'Date Added', 'Added By', 'Actions'], 'Table (, File Name, Description, Size, Type, Date Added, Added By, Actions; 1 row(s)) (table)');
  }

  /**  (checkbox) */
  get elementCheckbox(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('checkbox', { name: '', exact: true }), ' (checkbox)');
  }

  /** Elements revealed by opening 'Personal Details'. Open the trigger first. */
  readonly personalDetailsOpen = new ContactDetailsPagePersonalDetailsOpen(this.page);

  /** Elements revealed by opening 'Emergency Contacts'. Open the trigger first. */
  readonly emergencyContactsOpen = new ContactDetailsPageEmergencyContactsOpen(this.page);

  /** Elements revealed by opening 'Salary'. Open the trigger first. */
  readonly salaryOpen = new ContactDetailsPageSalaryOpen(this.page);

  /** Elements revealed by opening 'Memberships'. Open the trigger first. */
  readonly membershipsOpen = new ContactDetailsPageMembershipsOpen(this.page);
}

/** Only present while 'Personal Details' is open. */
export class ContactDetailsPagePersonalDetailsOpen {
  constructor(private readonly page: Page) {}

  /** Personal Details (text) */
  get personalDetailsHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Personal Details', exact: true }), 'Personal Details (text)');
  }

  /** First Name (input) */
  get firstNameInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'First Name', exact: true }), 'First Name (input)');
  }

  /** Middle Name (input) */
  get middleNameInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'Middle Name', exact: true }), 'Middle Name (input)');
  }

  /** Last Name (input) */
  get lastNameInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'Last Name', exact: true }), 'Last Name (input)');
  }

  /** Male (radio) */
  get maleRadio(): RadioComponent {
    return new RadioComponent(this.page.getByRole('radio', { name: 'Male', exact: true }), 'Male (radio)');
  }

  /** Female (radio) */
  get femaleRadio(): RadioComponent {
    return new RadioComponent(this.page.getByRole('radio', { name: 'Female', exact: true }), 'Female (radio)');
  }
}

/** Only present while 'Emergency Contacts' is open. */
export class ContactDetailsPageEmergencyContactsOpen {
  constructor(private readonly page: Page) {}

  /** Assigned Emergency Contacts (text) */
  get assignedEmergencyContactsHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Assigned Emergency Contacts', exact: true }), 'Assigned Emergency Contacts (text)');
  }
}

/** Only present while 'Salary' is open. */
export class ContactDetailsPageSalaryOpen {
  constructor(private readonly page: Page) {}

  /** Assigned Salary Components (text) */
  get assignedSalaryComponentsHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Assigned Salary Components', exact: true }), 'Assigned Salary Components (text)');
  }
}

/** Only present while 'Memberships' is open. */
export class ContactDetailsPageMembershipsOpen {
  constructor(private readonly page: Page) {}

  /** Assigned Memberships (text) */
  get assignedMembershipsHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Assigned Memberships', exact: true }), 'Assigned Memberships (text)');
  }
}
