// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-pim-contactDetails-empNumber-id
// Your own methods belong in ContactDetailsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TabComponent } from '../../components/TabComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/contactDetails/empNumber/{id} */
export abstract class ContactDetailsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/contactDetails/empNumber/{id}';

  constructor(page: Page) {
    super(page, ContactDetailsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Employee List (menuItem) */
  get employeeListMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Employee List');
  }

  /** Add Employee (menuItem) */
  get addEmployeeMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Add Employee');
  }

  /** Reports (menuItem) */
  get reportsMenuItem(): MenuItemComponent {
    return MenuItemComponent.byLabel(this.page, 'Reports');
  }

  /** Personal Details (tab) */
  get personalDetailsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('link', { name: 'Personal Details', exact: true }), 'Personal Details (tab)');
  }

  /** Contact Details (tab) */
  get contactDetailsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('link', { name: 'Contact Details', exact: true }), 'Contact Details (tab)');
  }

  /** Emergency Contacts (tab) */
  get emergencyContactsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('link', { name: 'Emergency Contacts', exact: true }), 'Emergency Contacts (tab)');
  }

  /** Dependents (tab) */
  get dependentsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('link', { name: 'Dependents', exact: true }), 'Dependents (tab)');
  }

  /** Immigration (tab) */
  get immigrationTab(): TabComponent {
    return new TabComponent(this.page.getByRole('link', { name: 'Immigration', exact: true }), 'Immigration (tab)');
  }

  /** Job (tab) */
  get jobTab(): TabComponent {
    return new TabComponent(this.page.getByRole('link', { name: 'Job', exact: true }), 'Job (tab)');
  }

  /** Salary (tab) */
  get salaryTab(): TabComponent {
    return new TabComponent(this.page.getByRole('link', { name: 'Salary', exact: true }), 'Salary (tab)');
  }

  /** Report-to (tab) */
  get reportToTab(): TabComponent {
    return new TabComponent(this.page.getByRole('link', { name: 'Report-to', exact: true }), 'Report-to (tab)');
  }

  /** Qualifications (tab) */
  get qualificationsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('link', { name: 'Qualifications', exact: true }), 'Qualifications (tab)');
  }

  /** Memberships (tab) */
  get membershipsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('link', { name: 'Memberships', exact: true }), 'Memberships (tab)');
  }

  /** Employee name (text) */
  get employeeNameHeading(): TextComponent {
    return new TextComponent(this.page.locator('.orangehrm-edit-employee-name h6'), 'Employee name (text)');
  }

  /** Contact Details (text) */
  get contactDetailsHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Contact Details');
  }

  /** Street 1 (input) */
  get street1Input(): InputComponent {
    return InputComponent.byLabel(this.page, 'Street 1');
  }

  /** Street 2 (input) */
  get street2Input(): InputComponent {
    return InputComponent.byLabel(this.page, 'Street 2');
  }

  /** City (input) */
  get cityInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'City');
  }

  /** State/Province (input) */
  get stateProvinceInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'State/Province');
  }

  /** Zip/Postal Code (input) */
  get zipPostalCodeInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Zip/Postal Code');
  }

  /** Country (dropdown) */
  get countryDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Country');
  }

  /** Home (input) */
  get homeInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Home');
  }

  /** Mobile (input) */
  get mobileInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Mobile');
  }

  /** Work (input) */
  get workInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Work');
  }

  /** Work Email (input) */
  get workEmailInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Work Email');
  }

  /** Other Email (input) */
  get otherEmailInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Other Email');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }

  /** Add attachment (button) */
  get addAttachmentButton(): ButtonComponent {
    return new ButtonComponent(this.page.locator('.orangehrm-horizontal-padding:has(h6:text-is("Attachments")) button'), 'Add attachment (button)');
  }

  /** Attachments (table) */
  get attachmentsTable(): TableComponent {
    return new TableComponent(this.page.locator('.oxd-table:has(.oxd-table-th:text-is("File Name"))'), ['File Name', 'Description', 'Size', 'Type', 'Date Added', 'Added By', 'Actions'], 'Attachments (table)');
  }
}
