// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-pim-viewDependents-empNumber-id
// Your own methods belong in DependentsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { ImageComponent } from '../../components/ImageComponent';
import { LinkComponent } from '../../components/LinkComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/viewDependents/empNumber/{id} */
export abstract class DependentsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/viewDependents/empNumber/{id}';

  constructor(page: Page) {
    super(page, DependentsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Claim img (image) */
  // UNSTABLE: no accessible name; scoped to nearest named ancestor
  get claimImgImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('link', { name: 'Claim', exact: true }).getByRole('img'), 'Claim img (image)');
  }

  /** PIM (text) */
  get pIMHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'PIM', exact: true }), 'PIM (text)');
  }

  /** Personal Details (link) */
  get personalDetailsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Personal Details', exact: true }), 'Personal Details (link)');
  }

  /** Contact Details (link) */
  get contactDetailsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Contact Details', exact: true }), 'Contact Details (link)');
  }

  /** Emergency Contacts (link) */
  get emergencyContactsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Emergency Contacts', exact: true }), 'Emergency Contacts (link)');
  }

  /** Dependents (link) */
  get dependentsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Dependents', exact: true }), 'Dependents (link)');
  }

  /** Immigration (link) */
  get immigrationLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Immigration', exact: true }), 'Immigration (link)');
  }

  /** Job (link) */
  get jobLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Job', exact: true }), 'Job (link)');
  }

  /** Salary (link) */
  get salaryLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Salary', exact: true }), 'Salary (link)');
  }

  /** Report-to (link) */
  get reportToLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Report-to', exact: true }), 'Report-to (link)');
  }

  /** Qualifications (link) */
  get qualificationsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Qualifications', exact: true }), 'Qualifications (link)');
  }

  /** Memberships (link) */
  get membershipsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Memberships', exact: true }), 'Memberships (link)');
  }

  /** Assigned Dependents (text) */
  get assignedDependentsHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Assigned Dependents', exact: true }), 'Assigned Dependents (text)');
  }

  /** Add Dependents (button) */
  get addDependentsButton(): ButtonComponent {
    return new ButtonComponent(this.page.locator('.orangehrm-horizontal-padding:has(h6:text-is("Assigned Dependents")) button'), 'Add Dependents (button)');
  }

  /** Assigned Dependents (table) */
  get assignedDependentsTable(): TableComponent {
    return new TableComponent(this.page.locator('div:has(> .orangehrm-horizontal-padding:has(h6:text-is("Assigned Dependents"))) > .orangehrm-container .oxd-table'), ['Name', 'Relationship', 'Date of Birth', 'Actions'], 'Assigned Dependents (table)');
  }

  /** Attachments (text) */
  get attachmentsHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Attachments', exact: true }), 'Attachments (text)');
  }

  /** Add Attachment (button) */
  get addAttachmentButton(): ButtonComponent {
    return new ButtonComponent(this.page.locator('.orangehrm-horizontal-padding:has(h6:text-is("Attachments")) button'), 'Add Attachment (button)');
  }
}
