// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: pim_display_employee_report
// Your own methods belong in DisplayPredefinedReportPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/displayPredefinedReport/{id} (also reachable at /web/index.php/pim/viewAttachment/empNumber/{empNumber}/attachId/{attachId}, /web/index.php/pim/viewPhoto/empNumber/{empNumber}, /web/index.php/pim/sampleCsvDownload, /web/index.php/pim/viewPimModule, /web/index.php/pim/viewMyDetails, /web/index.php/pim/viewReportToDetails/empNumber/{empNumber}, /web/index.php/pim/viewDefinedPredefinedReports) */
export abstract class DisplayPredefinedReportPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/displayPredefinedReport/{id}';
  static readonly aliases = ['/web/index.php/pim/viewAttachment/empNumber/{empNumber}/attachId/{attachId}', '/web/index.php/pim/viewPhoto/empNumber/{empNumber}', '/web/index.php/pim/sampleCsvDownload', '/web/index.php/pim/viewPimModule', '/web/index.php/pim/viewMyDetails', '/web/index.php/pim/viewReportToDetails/empNumber/{empNumber}', '/web/index.php/pim/viewDefinedPredefinedReports'] as const;

  constructor(page: Page) {
    super(page, DisplayPredefinedReportPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);
}
