// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-pim-viewEmployeeList
// Your own methods belong in EmployeeListPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { CheckboxComponent } from '../../components/CheckboxComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { ImageComponent } from '../../components/ImageComponent';
import { InputComponent } from '../../components/InputComponent';
import { LinkComponent } from '../../components/LinkComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/viewEmployeeList */
export abstract class EmployeeListPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/viewEmployeeList';

  constructor(page: Page) {
    super(page, EmployeeListPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Claim img (image) */
  // UNSTABLE: no accessible name; scoped to nearest named ancestor
  get claimImgImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('link', { name: 'Claim', exact: true }).getByRole('img'), 'Claim img (image)');
  }

  /** PIM (text) */
  get pIMHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'PIM', exact: true }), 'PIM (text)');
  }

  /** Employee List (link) */
  get employeeListLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Employee List', exact: true }), 'Employee List (link)');
  }

  /** Add Employee (link) */
  get addEmployeeLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Add Employee', exact: true }), 'Add Employee (link)');
  }

  /** Reports (link) */
  get reportsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Reports', exact: true }), 'Reports (link)');
  }

  /** Employee Information (text) */
  get employeeInformationHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Employee Information', exact: true }), 'Employee Information (text)');
  }

  /** Employee Name (input) */
  get employeeNameInput(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Employee Name")) input'), 'Employee Name (input)');
  }

  /** Employee Id (input) */
  get employeeIdInput(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Employee Id")) input'), 'Employee Id (input)');
  }

  /** Employment Status (dropdown) */
  get employmentStatusDropdown(): DropdownComponent {
    return new DropdownComponent(this.page.locator('.oxd-input-group:has(label:text-is("Employment Status")) .oxd-select-text'), 'Employment Status (dropdown)');
  }

  /** Include (dropdown) */
  get includeDropdown(): DropdownComponent {
    return new DropdownComponent(this.page.locator('.oxd-input-group:has(label:text-is("Include")) .oxd-select-text'), 'Include (dropdown)');
  }

  /** Supervisor Name (input) */
  get supervisorNameInput(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Supervisor Name")) input'), 'Supervisor Name (input)');
  }

  /** Job Title (dropdown) */
  get jobTitleDropdown(): DropdownComponent {
    return new DropdownComponent(this.page.locator('.oxd-input-group:has(label:text-is("Job Title")) .oxd-select-text'), 'Job Title (dropdown)');
  }

  /** Sub Unit (dropdown) */
  get subUnitDropdown(): DropdownComponent {
    return new DropdownComponent(this.page.locator('.oxd-input-group:has(label:text-is("Sub Unit")) .oxd-select-text'), 'Sub Unit (dropdown)');
  }

  /** Reset (button) */
  get resetButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Reset', exact: true }), 'Reset (button)');
  }

  /** Search (button) */
  get searchButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Search', exact: true }), 'Search (button)');
  }

  /** Add (button) */
  get addButton(): ButtonComponent {
    return new ButtonComponent(this.page.locator('.orangehrm-header-container button:has-text("Add")'), 'Add (button)');
  }

  /** Select All (checkbox) */
  get selectAllCheckbox(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('columnheader').getByRole('checkbox'), 'Select All (checkbox)');
  }

  /** Employee (table) */
  get employeeTable(): TableComponent {
    return new TableComponent(this.page.getByRole('table'), ['Id', 'First (& Middle) Name', 'Last Name', 'Job Title', 'Employment Status', 'Sub Unit', 'Supervisor', 'Actions'], 'Employee (table)');
  }
}
