// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: pim_employee_job
// Your own methods belong in JobDetailsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { RadioComponent } from '../../components/RadioComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/viewJobDetails/empNumber/{empNumber} */
export abstract class JobDetailsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/viewJobDetails/empNumber/{empNumber}';

  constructor(page: Page) {
    super(page, JobDetailsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Job Title (dropdown) */
  get jobTitleDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Job Title');
  }

  /** Job Category (dropdown) */
  get jobCategoryDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Job Category');
  }

  /** Sub Unit (dropdown) */
  get subUnitDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Sub Unit');
  }

  /** Location (dropdown) */
  get locationDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Location');
  }

  /** Employment Status (dropdown) */
  get employmentStatusDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Employment Status');
  }

  /** Joined Date (input) */
  get joinedDateInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Joined Date');
  }

  /** Contract Start Date (input) */
  get contractStartDateInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Contract Start Date');
  }

  /** Contract End Date (input) */
  get contractEndDateInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Contract End Date');
  }

  /** Keep Current (radio) */
  get keepCurrentRadio(): RadioComponent {
    return new RadioComponent(this.page.locator('.oxd-radio-wrapper:has(label:text-is("Keep Current")) input'), 'Keep Current (radio)');
  }

  /** Delete Current (radio) */
  get deleteCurrentRadio(): RadioComponent {
    return new RadioComponent(this.page.locator('.oxd-radio-wrapper:has(label:text-is("Delete Current")) input'), 'Delete Current (radio)');
  }

  /** Replace Current (radio) */
  get replaceCurrentRadio(): RadioComponent {
    return new RadioComponent(this.page.locator('.oxd-radio-wrapper:has(label:text-is("Replace Current")) input'), 'Replace Current (radio)');
  }

  /** noFileSelectedInput (input) */
  get noFileSelectedInput(): InputComponent {
    return new InputComponent(this.page.getByPlaceholder('No file selected'), 'noFileSelectedInput (input)');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }

  /** Add (button) */
  get addButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Add');
  }

  /** Termination Reason (dropdown) */
  get terminationReasonDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Termination Reason');
  }

  /** Note (longInput) */
  get noteLongInput(): InputComponent {
    return InputComponent.textareaByLabel(this.page, 'Note');
  }

  /** Cancel (button) */
  get cancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Cancel');
  }
}
