// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: view_custom_fields
// Your own methods belong in ListCustomFieldsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/listCustomFields */
export abstract class ListCustomFieldsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/listCustomFields';

  constructor(page: Page) {
    super(page, ListCustomFieldsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Add (button) */
  get addButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Add');
  }

  /** Custom Field Name (table) */
  get customFieldNameTable(): TableComponent {
    return TableComponent.byColumn(this.page, 'Custom Field Name', ['Custom Field Name', 'Screen', 'Field Type', 'Actions']);
  }

  /** Custom Fields (button) */
  get customFieldsButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Custom Fields');
  }

  /** No, Cancel (button) */
  get noCancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'No, Cancel');
  }

  /** Yes, Delete (button) */
  get yesDeleteButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Yes, Delete');
  }
}
