// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: pim_employee_membership
// Your own methods belong in MembershipsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/viewMemberships/empNumber/{empNumber} */
export abstract class MembershipsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/viewMemberships/empNumber/{empNumber}';

  constructor(page: Page) {
    super(page, MembershipsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Membership (table) */
  get membershipTable(): TableComponent {
    return TableComponent.byColumn(this.page, 'Membership', ['Membership', 'Subscription Paid By', 'Subscription Amount', 'Currency', 'Subscription Commence Date', 'Subscription Renewal Date', 'Actions']);
  }

  /** Membership (dropdown) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get membershipDropdown(): DropdownComponent {
    return new DropdownComponent(this.page.locator('.oxd-input-group:has(label:text-is("Membership")) .oxd-select-text'), 'Membership (dropdown)');
  }

  /** Subscription Paid By (dropdown) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get subscriptionPaidByDropdown(): DropdownComponent {
    return new DropdownComponent(this.page.locator('.oxd-input-group:has(label:text-is("Subscription Paid By")) .oxd-select-text'), 'Subscription Paid By (dropdown)');
  }

  /** Subscription Amount (input) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get subscriptionAmountInput(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Subscription Amount")) input'), 'Subscription Amount (input)');
  }

  /** Currency (dropdown) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get currencyDropdown(): DropdownComponent {
    return new DropdownComponent(this.page.locator('.oxd-input-group:has(label:text-is("Currency")) .oxd-select-text'), 'Currency (dropdown)');
  }

  /** Cancel (button) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get cancelButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Cancel', exact: true }), 'Cancel (button)');
  }

  /** Membership (dropdown) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get membershipDropdown2(): DropdownComponent {
    return new DropdownComponent(this.page.locator('.oxd-input-group:has(label:text-is("Membership")) .oxd-select-text'), 'Membership (dropdown)');
  }

  /** Subscription Paid By (dropdown) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get subscriptionPaidByDropdown2(): DropdownComponent {
    return new DropdownComponent(this.page.locator('.oxd-input-group:has(label:text-is("Subscription Paid By")) .oxd-select-text'), 'Subscription Paid By (dropdown)');
  }

  /** Subscription Amount (input) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get subscriptionAmountInput2(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Subscription Amount")) input'), 'Subscription Amount (input)');
  }

  /** Currency (dropdown) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get currencyDropdown2(): DropdownComponent {
    return new DropdownComponent(this.page.locator('.oxd-input-group:has(label:text-is("Currency")) .oxd-select-text'), 'Currency (dropdown)');
  }

  /** Cancel (button) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get cancelButton2(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Cancel', exact: true }), 'Cancel (button)');
  }

  /** Add (button) */
  get addButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Add');
  }

  /** Assigned Memberships (button) */
  get assignedMembershipsButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Assigned Memberships');
  }

  /** No, Cancel (button) */
  get noCancelButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'No, Cancel');
  }

  /** Yes, Delete (button) */
  get yesDeleteButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Yes, Delete');
  }
}
