// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-pim-viewMyDetails
// Your own methods belong in MyDetailsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { CheckboxComponent } from '../../components/CheckboxComponent';
import { ImageComponent } from '../../components/ImageComponent';
import { InputComponent } from '../../components/InputComponent';
import { LinkComponent } from '../../components/LinkComponent';
import { OptionComponent } from '../../components/OptionComponent';
import { RadioComponent } from '../../components/RadioComponent';
import { TabComponent } from '../../components/TabComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/viewMyDetails (also reachable at /web/index.php/pim/viewPersonalDetails/empNumber/7) */
export abstract class MyDetailsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/viewMyDetails';
  static readonly aliases = ['/web/index.php/pim/viewPersonalDetails/empNumber/7'] as const;

  constructor(page: Page) {
    super(page, MyDetailsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Claim img (image) */
  // UNSTABLE: no accessible name; scoped to nearest named ancestor
  get claimImgImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('link', { name: 'Claim', exact: true }).getByRole('img'), 'Claim img (image)');
  }

  /** PIM (text) */
  get pIMHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'PIM', exact: true }), 'PIM (text)');
  }

  /** profile picture (image) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get profilePictureImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('img').nth(2), 'profile picture (image)');
  }

  /** gb yasuser (text) */
  get gbYasuserHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'gb yasuser', exact: true }), 'gb yasuser (text)');
  }

  /** profile picture (image) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get profilePictureImage2(): ImageComponent {
    return new ImageComponent(this.page.getByRole('img').nth(3), 'profile picture (image)');
  }

  /** Personal Details (tab) */
  get personalDetailsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Personal Details', exact: true }), 'Personal Details (tab)');
  }

  /** Personal Details (link) */
  get personalDetailsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Personal Details', exact: true }), 'Personal Details (link)');
  }

  /** Contact Details (tab) */
  get contactDetailsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Contact Details', exact: true }), 'Contact Details (tab)');
  }

  /** Contact Details (link) */
  get contactDetailsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Contact Details', exact: true }), 'Contact Details (link)');
  }

  /** Emergency Contacts (tab) */
  get emergencyContactsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Emergency Contacts', exact: true }), 'Emergency Contacts (tab)');
  }

  /** Emergency Contacts (link) */
  get emergencyContactsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Emergency Contacts', exact: true }), 'Emergency Contacts (link)');
  }

  /** Dependents (tab) */
  get dependentsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Dependents', exact: true }), 'Dependents (tab)');
  }

  /** Dependents (link) */
  get dependentsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Dependents', exact: true }), 'Dependents (link)');
  }

  /** Immigration (tab) */
  get immigrationTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Immigration', exact: true }), 'Immigration (tab)');
  }

  /** Immigration (link) */
  get immigrationLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Immigration', exact: true }), 'Immigration (link)');
  }

  /** Job (tab) */
  get jobTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Job', exact: true }), 'Job (tab)');
  }

  /** Job (link) */
  get jobLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Job', exact: true }), 'Job (link)');
  }

  /** Salary (tab) */
  get salaryTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Salary', exact: true }), 'Salary (tab)');
  }

  /** Salary (link) */
  get salaryLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Salary', exact: true }), 'Salary (link)');
  }

  /** Report-to (tab) */
  get reportToTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Report-to', exact: true }), 'Report-to (tab)');
  }

  /** Report-to (link) */
  get reportToLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Report-to', exact: true }), 'Report-to (link)');
  }

  /** Qualifications (tab) */
  get qualificationsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Qualifications', exact: true }), 'Qualifications (tab)');
  }

  /** Qualifications (link) */
  get qualificationsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Qualifications', exact: true }), 'Qualifications (link)');
  }

  /** Memberships (tab) */
  get membershipsTab(): TabComponent {
    return new TabComponent(this.page.getByRole('tab', { name: 'Memberships', exact: true }), 'Memberships (tab)');
  }

  /** Memberships (link) */
  get membershipsLink(): LinkComponent {
    return new LinkComponent(this.page.getByRole('link', { name: 'Memberships', exact: true }), 'Memberships (link)');
  }

  /** Personal Details (text) */
  get personalDetailsHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Personal Details', exact: true }), 'Personal Details (text)');
  }

  /** First Name (input) */
  get firstNameInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'First Name', exact: true }), 'First Name (input)');
  }

  /** Middle Name (input) */
  get middleNameInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'Middle Name', exact: true }), 'Middle Name (input)');
  }

  /** Last Name (input) */
  get lastNameInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'Last Name', exact: true }), 'Last Name (input)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(4), '(unnamed) (input)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput2(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(5), '(unnamed) (input)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput3(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(6), '(unnamed) (input)');
  }

  /** yyyy-dd-mm (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get yyyyDdMmInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(7), 'yyyy-dd-mm (input)');
  }

  /** yyyy-dd-mm (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get yyyyDdMmInput2(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(8), 'yyyy-dd-mm (input)');
  }

  /** Male (radio) */
  get maleRadio(): RadioComponent {
    return new RadioComponent(this.page.getByRole('radio', { name: 'Male', exact: true }), 'Male (radio)');
  }

  /** Female (radio) */
  get femaleRadio(): RadioComponent {
    return new RadioComponent(this.page.getByRole('radio', { name: 'Female', exact: true }), 'Female (radio)');
  }

  /** Save (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get saveButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(3), 'Save (button)');
  }

  /** Custom Fields (text) */
  get customFieldsHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Custom Fields', exact: true }), 'Custom Fields (text)');
  }

  /** (unnamed) (input) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get textboxInput4(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox').nth(9), '(unnamed) (input)');
  }

  /** Save (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get saveButton2(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(4), 'Save (button)');
  }

  /** Attachments (text) */
  get attachmentsHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Attachments', exact: true }), 'Attachments (text)');
  }

  /**  Add (button) */
  get addButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: ' Add', exact: true }), ' Add (button)');
  }

  /** Table (, File Name, Description, Size, Type, Date Added, Added By, Actions; 2 row(s)) (table) */
  // UNSTABLE: table has no accessible name; positional index used
  get tableTable(): TableComponent {
    return new TableComponent(this.page.getByRole('table').nth(0), ['', 'File Name', 'Description', 'Size', 'Type', 'Date Added', 'Added By', 'Actions'], 'Table (, File Name, Description, Size, Type, Date Added, Added By, Actions; 2 row(s)) (table)');
  }

  /**  (checkbox) */
  get elementCheckbox(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('columnheader', { name: '', exact: true }).getByRole('checkbox', { name: '', exact: true }), ' (checkbox)');
  }

  /**  (checkbox) */
  get elementCheckbox2(): CheckboxComponent {
    return new CheckboxComponent(this.page.getByRole('cell', { name: '', exact: true }).getByRole('checkbox', { name: '', exact: true }), ' (checkbox)');
  }

  /**  (button) */
  get elementButton3(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: '', exact: true }), ' (button)');
  }

  /**  (button) */
  get elementButton4(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: '', exact: true }), ' (button)');
  }

  /**  (button) */
  get elementButton5(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: '', exact: true }), ' (button)');
  }

  /** Elements revealed by opening 'American'. Open the trigger first. */
  readonly americanOpen = new MyDetailsPageAmericanOpen(this.page);

  /** Elements revealed by opening 'Single'. Open the trigger first. */
  readonly singleOpen = new MyDetailsPageSingleOpen(this.page);

  /** Elements revealed by opening 'A+'. Open the trigger first. */
  readonly aOpen = new MyDetailsPageAOpen(this.page);
}

/** Only present while 'American' is open. */
export class MyDetailsPageAmericanOpen {
  constructor(private readonly page: Page) {}

  /** -- Select -- (dropdown) */
  get selectOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: '-- Select --', exact: true }), '-- Select -- (dropdown)');
  }

  /** Afghan (dropdown) */
  get afghanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Afghan', exact: true }), 'Afghan (dropdown)');
  }

  /** Albanian (dropdown) */
  get albanianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Albanian', exact: true }), 'Albanian (dropdown)');
  }

  /** Algerian (dropdown) */
  get algerianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Algerian', exact: true }), 'Algerian (dropdown)');
  }

  /** American (dropdown) */
  get americanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'American', exact: true }), 'American (dropdown)');
  }

  /** Andorran (dropdown) */
  get andorranOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Andorran', exact: true }), 'Andorran (dropdown)');
  }

  /** Angolan (dropdown) */
  get angolanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Angolan', exact: true }), 'Angolan (dropdown)');
  }

  /** Antiguans (dropdown) */
  get antiguansOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Antiguans', exact: true }), 'Antiguans (dropdown)');
  }

  /** Argentinean (dropdown) */
  get argentineanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Argentinean', exact: true }), 'Argentinean (dropdown)');
  }

  /** Armenian (dropdown) */
  get armenianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Armenian', exact: true }), 'Armenian (dropdown)');
  }

  /** Australian (dropdown) */
  get australianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Australian', exact: true }), 'Australian (dropdown)');
  }

  /** Austrian (dropdown) */
  get austrianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Austrian', exact: true }), 'Austrian (dropdown)');
  }

  /** Azerbaijani (dropdown) */
  get azerbaijaniOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Azerbaijani', exact: true }), 'Azerbaijani (dropdown)');
  }

  /** Bahamian (dropdown) */
  get bahamianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bahamian', exact: true }), 'Bahamian (dropdown)');
  }

  /** Bahraini (dropdown) */
  get bahrainiOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bahraini', exact: true }), 'Bahraini (dropdown)');
  }

  /** Bangladeshi (dropdown) */
  get bangladeshiOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bangladeshi', exact: true }), 'Bangladeshi (dropdown)');
  }

  /** Barbadian (dropdown) */
  get barbadianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Barbadian', exact: true }), 'Barbadian (dropdown)');
  }

  /** Barbudans (dropdown) */
  get barbudansOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Barbudans', exact: true }), 'Barbudans (dropdown)');
  }

  /** Batswana (dropdown) */
  get batswanaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Batswana', exact: true }), 'Batswana (dropdown)');
  }

  /** Belarusian (dropdown) */
  get belarusianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Belarusian', exact: true }), 'Belarusian (dropdown)');
  }

  /** Belgian (dropdown) */
  get belgianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Belgian', exact: true }), 'Belgian (dropdown)');
  }

  /** Belizean (dropdown) */
  get belizeanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Belizean', exact: true }), 'Belizean (dropdown)');
  }

  /** Beninese (dropdown) */
  get benineseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Beninese', exact: true }), 'Beninese (dropdown)');
  }

  /** Bhutanese (dropdown) */
  get bhutaneseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bhutanese', exact: true }), 'Bhutanese (dropdown)');
  }

  /** Bolivian (dropdown) */
  get bolivianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bolivian', exact: true }), 'Bolivian (dropdown)');
  }

  /** Bosnian (dropdown) */
  get bosnianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bosnian', exact: true }), 'Bosnian (dropdown)');
  }

  /** Brazilian (dropdown) */
  get brazilianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Brazilian', exact: true }), 'Brazilian (dropdown)');
  }

  /** British (dropdown) */
  get britishOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'British', exact: true }), 'British (dropdown)');
  }

  /** Bruneian (dropdown) */
  get bruneianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bruneian', exact: true }), 'Bruneian (dropdown)');
  }

  /** Bulgarian (dropdown) */
  get bulgarianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Bulgarian', exact: true }), 'Bulgarian (dropdown)');
  }

  /** Burkinabe (dropdown) */
  get burkinabeOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Burkinabe', exact: true }), 'Burkinabe (dropdown)');
  }

  /** Burmese (dropdown) */
  get burmeseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Burmese', exact: true }), 'Burmese (dropdown)');
  }

  /** Burundian (dropdown) */
  get burundianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Burundian', exact: true }), 'Burundian (dropdown)');
  }

  /** Cambodian (dropdown) */
  get cambodianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Cambodian', exact: true }), 'Cambodian (dropdown)');
  }

  /** Cameroonian (dropdown) */
  get cameroonianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Cameroonian', exact: true }), 'Cameroonian (dropdown)');
  }

  /** Canadian (dropdown) */
  get canadianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Canadian', exact: true }), 'Canadian (dropdown)');
  }

  /** Cape Verdean (dropdown) */
  get capeVerdeanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Cape Verdean', exact: true }), 'Cape Verdean (dropdown)');
  }

  /** Central African (dropdown) */
  get centralAfricanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Central African', exact: true }), 'Central African (dropdown)');
  }

  /** Chadian (dropdown) */
  get chadianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Chadian', exact: true }), 'Chadian (dropdown)');
  }

  /** Chilean (dropdown) */
  get chileanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Chilean', exact: true }), 'Chilean (dropdown)');
  }

  /** Chinese (dropdown) */
  get chineseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Chinese', exact: true }), 'Chinese (dropdown)');
  }

  /** Colombian (dropdown) */
  get colombianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Colombian', exact: true }), 'Colombian (dropdown)');
  }

  /** Comoran (dropdown) */
  get comoranOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Comoran', exact: true }), 'Comoran (dropdown)');
  }

  /** Congolese (dropdown) */
  get congoleseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Congolese', exact: true }), 'Congolese (dropdown)');
  }

  /** Costa Rican (dropdown) */
  get costaRicanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Costa Rican', exact: true }), 'Costa Rican (dropdown)');
  }

  /** Croatian (dropdown) */
  get croatianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Croatian', exact: true }), 'Croatian (dropdown)');
  }

  /** Cuban (dropdown) */
  get cubanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Cuban', exact: true }), 'Cuban (dropdown)');
  }

  /** Cypriot (dropdown) */
  get cypriotOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Cypriot', exact: true }), 'Cypriot (dropdown)');
  }

  /** Czech (dropdown) */
  get czechOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Czech', exact: true }), 'Czech (dropdown)');
  }

  /** Danish (dropdown) */
  get danishOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Danish', exact: true }), 'Danish (dropdown)');
  }

  /** Djibouti (dropdown) */
  get djiboutiOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Djibouti', exact: true }), 'Djibouti (dropdown)');
  }

  /** Dominican (dropdown) */
  get dominicanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Dominican', exact: true }), 'Dominican (dropdown)');
  }

  /** Dutch (dropdown) */
  get dutchOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Dutch', exact: true }), 'Dutch (dropdown)');
  }

  /** East Timorese (dropdown) */
  get eastTimoreseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'East Timorese', exact: true }), 'East Timorese (dropdown)');
  }

  /** Ecuadorean (dropdown) */
  get ecuadoreanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Ecuadorean', exact: true }), 'Ecuadorean (dropdown)');
  }

  /** Egyptian (dropdown) */
  get egyptianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Egyptian', exact: true }), 'Egyptian (dropdown)');
  }

  /** Emirian (dropdown) */
  get emirianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Emirian', exact: true }), 'Emirian (dropdown)');
  }

  /** Equatorial Guinean (dropdown) */
  get equatorialGuineanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Equatorial Guinean', exact: true }), 'Equatorial Guinean (dropdown)');
  }

  /** Eritrean (dropdown) */
  get eritreanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Eritrean', exact: true }), 'Eritrean (dropdown)');
  }

  /** Estonian (dropdown) */
  get estonianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Estonian', exact: true }), 'Estonian (dropdown)');
  }

  /** Ethiopian (dropdown) */
  get ethiopianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Ethiopian', exact: true }), 'Ethiopian (dropdown)');
  }

  /** Fijian (dropdown) */
  get fijianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Fijian', exact: true }), 'Fijian (dropdown)');
  }

  /** Filipino (dropdown) */
  get filipinoOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Filipino', exact: true }), 'Filipino (dropdown)');
  }

  /** Finnish (dropdown) */
  get finnishOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Finnish', exact: true }), 'Finnish (dropdown)');
  }

  /** French (dropdown) */
  get frenchOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'French', exact: true }), 'French (dropdown)');
  }

  /** Gabonese (dropdown) */
  get gaboneseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Gabonese', exact: true }), 'Gabonese (dropdown)');
  }

  /** Gambian (dropdown) */
  get gambianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Gambian', exact: true }), 'Gambian (dropdown)');
  }

  /** Georgian (dropdown) */
  get georgianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Georgian', exact: true }), 'Georgian (dropdown)');
  }

  /** German (dropdown) */
  get germanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'German', exact: true }), 'German (dropdown)');
  }

  /** Ghanaian (dropdown) */
  get ghanaianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Ghanaian', exact: true }), 'Ghanaian (dropdown)');
  }

  /** Greek (dropdown) */
  get greekOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Greek', exact: true }), 'Greek (dropdown)');
  }

  /** Grenadian (dropdown) */
  get grenadianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Grenadian', exact: true }), 'Grenadian (dropdown)');
  }

  /** Guatemalan (dropdown) */
  get guatemalanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Guatemalan', exact: true }), 'Guatemalan (dropdown)');
  }

  /** Guinea-Bissauan (dropdown) */
  get guineaBissauanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Guinea-Bissauan', exact: true }), 'Guinea-Bissauan (dropdown)');
  }

  /** Guinean (dropdown) */
  get guineanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Guinean', exact: true }), 'Guinean (dropdown)');
  }

  /** Guyanese (dropdown) */
  get guyaneseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Guyanese', exact: true }), 'Guyanese (dropdown)');
  }

  /** Haitian (dropdown) */
  get haitianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Haitian', exact: true }), 'Haitian (dropdown)');
  }

  /** Herzegovinian (dropdown) */
  get herzegovinianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Herzegovinian', exact: true }), 'Herzegovinian (dropdown)');
  }

  /** Honduran (dropdown) */
  get honduranOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Honduran', exact: true }), 'Honduran (dropdown)');
  }

  /** Hungarian (dropdown) */
  get hungarianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Hungarian', exact: true }), 'Hungarian (dropdown)');
  }

  /** I-Kiribati (dropdown) */
  get iKiribatiOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'I-Kiribati', exact: true }), 'I-Kiribati (dropdown)');
  }

  /** Icelander (dropdown) */
  get icelanderOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Icelander', exact: true }), 'Icelander (dropdown)');
  }

  /** Indian (dropdown) */
  get indianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Indian', exact: true }), 'Indian (dropdown)');
  }

  /** Indonesian (dropdown) */
  get indonesianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Indonesian', exact: true }), 'Indonesian (dropdown)');
  }

  /** Iranian (dropdown) */
  get iranianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Iranian', exact: true }), 'Iranian (dropdown)');
  }

  /** Iraqi (dropdown) */
  get iraqiOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Iraqi', exact: true }), 'Iraqi (dropdown)');
  }

  /** Irish (dropdown) */
  get irishOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Irish', exact: true }), 'Irish (dropdown)');
  }

  /** Israeli (dropdown) */
  get israeliOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Israeli', exact: true }), 'Israeli (dropdown)');
  }

  /** Italian (dropdown) */
  get italianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Italian', exact: true }), 'Italian (dropdown)');
  }

  /** Ivorian (dropdown) */
  get ivorianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Ivorian', exact: true }), 'Ivorian (dropdown)');
  }

  /** Jamaican (dropdown) */
  get jamaicanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Jamaican', exact: true }), 'Jamaican (dropdown)');
  }

  /** Japanese (dropdown) */
  get japaneseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Japanese', exact: true }), 'Japanese (dropdown)');
  }

  /** Jordanian (dropdown) */
  get jordanianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Jordanian', exact: true }), 'Jordanian (dropdown)');
  }

  /** Kazakhstani (dropdown) */
  get kazakhstaniOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Kazakhstani', exact: true }), 'Kazakhstani (dropdown)');
  }

  /** Kenyan (dropdown) */
  get kenyanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Kenyan', exact: true }), 'Kenyan (dropdown)');
  }

  /** Kittian and Nevisian (dropdown) */
  get kittianAndNevisianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Kittian and Nevisian', exact: true }), 'Kittian and Nevisian (dropdown)');
  }

  /** Kuwaiti (dropdown) */
  get kuwaitiOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Kuwaiti', exact: true }), 'Kuwaiti (dropdown)');
  }

  /** Kyrgyz (dropdown) */
  get kyrgyzOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Kyrgyz', exact: true }), 'Kyrgyz (dropdown)');
  }

  /** Laotian (dropdown) */
  get laotianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Laotian', exact: true }), 'Laotian (dropdown)');
  }

  /** Latvian (dropdown) */
  get latvianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Latvian', exact: true }), 'Latvian (dropdown)');
  }

  /** Lebanese (dropdown) */
  get lebaneseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Lebanese', exact: true }), 'Lebanese (dropdown)');
  }

  /** Liberian (dropdown) */
  get liberianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Liberian', exact: true }), 'Liberian (dropdown)');
  }

  /** Libyan (dropdown) */
  get libyanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Libyan', exact: true }), 'Libyan (dropdown)');
  }

  /** Liechtensteiner (dropdown) */
  get liechtensteinerOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Liechtensteiner', exact: true }), 'Liechtensteiner (dropdown)');
  }

  /** Lithuanian (dropdown) */
  get lithuanianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Lithuanian', exact: true }), 'Lithuanian (dropdown)');
  }

  /** Luxembourger (dropdown) */
  get luxembourgerOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Luxembourger', exact: true }), 'Luxembourger (dropdown)');
  }

  /** Macedonian (dropdown) */
  get macedonianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Macedonian', exact: true }), 'Macedonian (dropdown)');
  }

  /** Malagasy (dropdown) */
  get malagasyOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Malagasy', exact: true }), 'Malagasy (dropdown)');
  }

  /** Malawian (dropdown) */
  get malawianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Malawian', exact: true }), 'Malawian (dropdown)');
  }

  /** Malaysian (dropdown) */
  get malaysianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Malaysian', exact: true }), 'Malaysian (dropdown)');
  }

  /** Maldivan (dropdown) */
  get maldivanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Maldivan', exact: true }), 'Maldivan (dropdown)');
  }

  /** Malian (dropdown) */
  get malianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Malian', exact: true }), 'Malian (dropdown)');
  }

  /** Maltese (dropdown) */
  get malteseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Maltese', exact: true }), 'Maltese (dropdown)');
  }

  /** Marshallese (dropdown) */
  get marshalleseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Marshallese', exact: true }), 'Marshallese (dropdown)');
  }

  /** Mauritanian (dropdown) */
  get mauritanianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Mauritanian', exact: true }), 'Mauritanian (dropdown)');
  }

  /** Mauritian (dropdown) */
  get mauritianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Mauritian', exact: true }), 'Mauritian (dropdown)');
  }

  /** Mexican (dropdown) */
  get mexicanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Mexican', exact: true }), 'Mexican (dropdown)');
  }

  /** Micronesian (dropdown) */
  get micronesianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Micronesian', exact: true }), 'Micronesian (dropdown)');
  }

  /** Moldovan (dropdown) */
  get moldovanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Moldovan', exact: true }), 'Moldovan (dropdown)');
  }

  /** Monacan (dropdown) */
  get monacanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Monacan', exact: true }), 'Monacan (dropdown)');
  }

  /** Mongolian (dropdown) */
  get mongolianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Mongolian', exact: true }), 'Mongolian (dropdown)');
  }

  /** Moroccan (dropdown) */
  get moroccanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Moroccan', exact: true }), 'Moroccan (dropdown)');
  }

  /** Mosotho (dropdown) */
  get mosothoOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Mosotho', exact: true }), 'Mosotho (dropdown)');
  }

  /** Motswana (dropdown) */
  get motswanaOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Motswana', exact: true }), 'Motswana (dropdown)');
  }

  /** Mozambican (dropdown) */
  get mozambicanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Mozambican', exact: true }), 'Mozambican (dropdown)');
  }

  /** Namibian (dropdown) */
  get namibianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Namibian', exact: true }), 'Namibian (dropdown)');
  }

  /** Nauruan (dropdown) */
  get nauruanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Nauruan', exact: true }), 'Nauruan (dropdown)');
  }

  /** Nepalese (dropdown) */
  get nepaleseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Nepalese', exact: true }), 'Nepalese (dropdown)');
  }

  /** New Zealander (dropdown) */
  get newZealanderOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'New Zealander', exact: true }), 'New Zealander (dropdown)');
  }

  /** Nicaraguan (dropdown) */
  get nicaraguanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Nicaraguan', exact: true }), 'Nicaraguan (dropdown)');
  }

  /** Nigerian (dropdown) */
  get nigerianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Nigerian', exact: true }), 'Nigerian (dropdown)');
  }

  /** Nigerien (dropdown) */
  get nigerienOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Nigerien', exact: true }), 'Nigerien (dropdown)');
  }

  /** North Korean (dropdown) */
  get northKoreanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'North Korean', exact: true }), 'North Korean (dropdown)');
  }

  /** Northern Irish (dropdown) */
  get northernIrishOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Northern Irish', exact: true }), 'Northern Irish (dropdown)');
  }

  /** Norwegian (dropdown) */
  get norwegianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Norwegian', exact: true }), 'Norwegian (dropdown)');
  }

  /** Omani (dropdown) */
  get omaniOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Omani', exact: true }), 'Omani (dropdown)');
  }

  /** Pakistani (dropdown) */
  get pakistaniOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Pakistani', exact: true }), 'Pakistani (dropdown)');
  }

  /** Palauan (dropdown) */
  get palauanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Palauan', exact: true }), 'Palauan (dropdown)');
  }

  /** Panamanian (dropdown) */
  get panamanianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Panamanian', exact: true }), 'Panamanian (dropdown)');
  }

  /** Papua New Guinean (dropdown) */
  get papuaNewGuineanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Papua New Guinean', exact: true }), 'Papua New Guinean (dropdown)');
  }

  /** Paraguayan (dropdown) */
  get paraguayanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Paraguayan', exact: true }), 'Paraguayan (dropdown)');
  }

  /** Peruvian (dropdown) */
  get peruvianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Peruvian', exact: true }), 'Peruvian (dropdown)');
  }

  /** Polish (dropdown) */
  get polishOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Polish', exact: true }), 'Polish (dropdown)');
  }

  /** Portuguese (dropdown) */
  get portugueseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Portuguese', exact: true }), 'Portuguese (dropdown)');
  }

  /** Qatari (dropdown) */
  get qatariOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Qatari', exact: true }), 'Qatari (dropdown)');
  }

  /** Romanian (dropdown) */
  get romanianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Romanian', exact: true }), 'Romanian (dropdown)');
  }

  /** Russian (dropdown) */
  get russianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Russian', exact: true }), 'Russian (dropdown)');
  }

  /** Rwandan (dropdown) */
  get rwandanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Rwandan', exact: true }), 'Rwandan (dropdown)');
  }

  /** Saint Lucian (dropdown) */
  get saintLucianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Saint Lucian', exact: true }), 'Saint Lucian (dropdown)');
  }

  /** Salvadoran (dropdown) */
  get salvadoranOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Salvadoran', exact: true }), 'Salvadoran (dropdown)');
  }

  /** Samoan (dropdown) */
  get samoanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Samoan', exact: true }), 'Samoan (dropdown)');
  }

  /** San Marinese (dropdown) */
  get sanMarineseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'San Marinese', exact: true }), 'San Marinese (dropdown)');
  }

  /** Sao Tomean (dropdown) */
  get saoTomeanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Sao Tomean', exact: true }), 'Sao Tomean (dropdown)');
  }

  /** Saudi (dropdown) */
  get saudiOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Saudi', exact: true }), 'Saudi (dropdown)');
  }

  /** Scottish (dropdown) */
  get scottishOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Scottish', exact: true }), 'Scottish (dropdown)');
  }

  /** Senegalese (dropdown) */
  get senegaleseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Senegalese', exact: true }), 'Senegalese (dropdown)');
  }

  /** Serbian (dropdown) */
  get serbianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Serbian', exact: true }), 'Serbian (dropdown)');
  }

  /** Seychellois (dropdown) */
  get seychelloisOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Seychellois', exact: true }), 'Seychellois (dropdown)');
  }

  /** Sierra Leonean (dropdown) */
  get sierraLeoneanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Sierra Leonean', exact: true }), 'Sierra Leonean (dropdown)');
  }

  /** Singaporean (dropdown) */
  get singaporeanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Singaporean', exact: true }), 'Singaporean (dropdown)');
  }

  /** Slovakian (dropdown) */
  get slovakianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Slovakian', exact: true }), 'Slovakian (dropdown)');
  }

  /** Slovenian (dropdown) */
  get slovenianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Slovenian', exact: true }), 'Slovenian (dropdown)');
  }

  /** Solomon Islander (dropdown) */
  get solomonIslanderOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Solomon Islander', exact: true }), 'Solomon Islander (dropdown)');
  }

  /** Somali (dropdown) */
  get somaliOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Somali', exact: true }), 'Somali (dropdown)');
  }

  /** South African (dropdown) */
  get southAfricanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'South African', exact: true }), 'South African (dropdown)');
  }

  /** South Korean (dropdown) */
  get southKoreanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'South Korean', exact: true }), 'South Korean (dropdown)');
  }

  /** Spanish (dropdown) */
  get spanishOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Spanish', exact: true }), 'Spanish (dropdown)');
  }

  /** Sri Lankan (dropdown) */
  get sriLankanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Sri Lankan', exact: true }), 'Sri Lankan (dropdown)');
  }

  /** Sudanese (dropdown) */
  get sudaneseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Sudanese', exact: true }), 'Sudanese (dropdown)');
  }

  /** Surinamer (dropdown) */
  get surinamerOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Surinamer', exact: true }), 'Surinamer (dropdown)');
  }

  /** Swazi (dropdown) */
  get swaziOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Swazi', exact: true }), 'Swazi (dropdown)');
  }

  /** Swedish (dropdown) */
  get swedishOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Swedish', exact: true }), 'Swedish (dropdown)');
  }

  /** Swiss (dropdown) */
  get swissOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Swiss', exact: true }), 'Swiss (dropdown)');
  }

  /** Syrian (dropdown) */
  get syrianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Syrian', exact: true }), 'Syrian (dropdown)');
  }

  /** Taiwanese (dropdown) */
  get taiwaneseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Taiwanese', exact: true }), 'Taiwanese (dropdown)');
  }

  /** Tajik (dropdown) */
  get tajikOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Tajik', exact: true }), 'Tajik (dropdown)');
  }

  /** Tanzanian (dropdown) */
  get tanzanianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Tanzanian', exact: true }), 'Tanzanian (dropdown)');
  }

  /** Thai (dropdown) */
  get thaiOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Thai', exact: true }), 'Thai (dropdown)');
  }

  /** Togolese (dropdown) */
  get togoleseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Togolese', exact: true }), 'Togolese (dropdown)');
  }

  /** Tongan (dropdown) */
  get tonganOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Tongan', exact: true }), 'Tongan (dropdown)');
  }

  /** Trinidadian or Tobagonian (dropdown) */
  get trinidadianOrTobagonianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Trinidadian or Tobagonian', exact: true }), 'Trinidadian or Tobagonian (dropdown)');
  }

  /** Tunisian (dropdown) */
  get tunisianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Tunisian', exact: true }), 'Tunisian (dropdown)');
  }

  /** Turkish (dropdown) */
  get turkishOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Turkish', exact: true }), 'Turkish (dropdown)');
  }

  /** Tuvaluan (dropdown) */
  get tuvaluanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Tuvaluan', exact: true }), 'Tuvaluan (dropdown)');
  }

  /** Ugandan (dropdown) */
  get ugandanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Ugandan', exact: true }), 'Ugandan (dropdown)');
  }

  /** Ukrainian (dropdown) */
  get ukrainianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Ukrainian', exact: true }), 'Ukrainian (dropdown)');
  }

  /** Uruguayan (dropdown) */
  get uruguayanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Uruguayan', exact: true }), 'Uruguayan (dropdown)');
  }

  /** Uzbekistani (dropdown) */
  get uzbekistaniOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Uzbekistani', exact: true }), 'Uzbekistani (dropdown)');
  }

  /** Venezuelan (dropdown) */
  get venezuelanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Venezuelan', exact: true }), 'Venezuelan (dropdown)');
  }

  /** Vietnamese (dropdown) */
  get vietnameseOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Vietnamese', exact: true }), 'Vietnamese (dropdown)');
  }

  /** Welsh (dropdown) */
  get welshOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Welsh', exact: true }), 'Welsh (dropdown)');
  }

  /** Yemenite (dropdown) */
  get yemeniteOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Yemenite', exact: true }), 'Yemenite (dropdown)');
  }

  /** Zambian (dropdown) */
  get zambianOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Zambian', exact: true }), 'Zambian (dropdown)');
  }

  /** Zimbabwean (dropdown) */
  get zimbabweanOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Zimbabwean', exact: true }), 'Zimbabwean (dropdown)');
  }
}

/** Only present while 'Single' is open. */
export class MyDetailsPageSingleOpen {
  constructor(private readonly page: Page) {}

  /** -- Select -- (dropdown) */
  get selectOption2(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: '-- Select --', exact: true }), '-- Select -- (dropdown)');
  }

  /** Single (dropdown) */
  get singleOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Single', exact: true }), 'Single (dropdown)');
  }

  /** Married (dropdown) */
  get marriedOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Married', exact: true }), 'Married (dropdown)');
  }

  /** Other (dropdown) */
  get otherOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'Other', exact: true }), 'Other (dropdown)');
  }
}

/** Only present while 'A+' is open. */
export class MyDetailsPageAOpen {
  constructor(private readonly page: Page) {}

  /** -- Select -- (dropdown) */
  get selectOption3(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: '-- Select --', exact: true }), '-- Select -- (dropdown)');
  }

  /** A+ (dropdown) */
  get aOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'A+', exact: true }), 'A+ (dropdown)');
  }

  /** A- (dropdown) */
  get aOption2(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'A-', exact: true }), 'A- (dropdown)');
  }

  /** B+ (dropdown) */
  get bOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'B+', exact: true }), 'B+ (dropdown)');
  }

  /** B- (dropdown) */
  get bOption2(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'B-', exact: true }), 'B- (dropdown)');
  }

  /** O+ (dropdown) */
  get oOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'O+', exact: true }), 'O+ (dropdown)');
  }

  /** O- (dropdown) */
  get oOption2(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'O-', exact: true }), 'O- (dropdown)');
  }

  /** AB+ (dropdown) */
  get aBOption(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'AB+', exact: true }), 'AB+ (dropdown)');
  }

  /** AB- (dropdown) */
  get aBOption2(): OptionComponent {
    return new OptionComponent(this.page.getByRole('option', { name: 'AB-', exact: true }), 'AB- (dropdown)');
  }
}
