// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-pim-viewPhotograph-empNumber-id
// Your own methods belong in PhotographPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/viewPhotograph/empNumber/{id} */
export abstract class PhotographPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/viewPhotograph/empNumber/{id}';

  constructor(page: Page) {
    super(page, PhotographPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** PIM (text) */
  get pimHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'PIM');
  }

  /** Automation QE (text) */
  get automationQeHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Automation QE');
  }

  /** Change Profile Picture (text) */
  get changeProfilePictureHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Change Profile Picture');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
