// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: pim_employee_qualifications
// Your own methods belong in QualificationsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { TableComponent } from '../../components/tables/TableComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/viewQualifications/empNumber/{empNumber} */
export abstract class QualificationsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/viewQualifications/empNumber/{empNumber}';

  constructor(page: Page) {
    super(page, QualificationsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Qualifications (table) */
  // UNSTABLE: 5 elements on this page resolve to this same locator — it needs scoping to one of them
  get qualificationsTable(): TableComponent {
    return new TableComponent(this.page.locator('.oxd-table:has(.oxd-table-th:text-is("Qualifications"))'), ['Company', 'Job Title', 'From', 'To', 'Comment', 'Actions'], 'Qualifications (table)');
  }

  /** Qualifications (table) */
  // UNSTABLE: 5 elements on this page resolve to this same locator — it needs scoping to one of them
  get qualificationsTable2(): TableComponent {
    return new TableComponent(this.page.locator('.oxd-table:has(.oxd-table-th:text-is("Qualifications"))'), ['Level', 'Year', 'GPA/Score', 'Actions'], 'Qualifications (table)');
  }

  /** Qualifications (table) */
  // UNSTABLE: 5 elements on this page resolve to this same locator — it needs scoping to one of them
  get qualificationsTable3(): TableComponent {
    return new TableComponent(this.page.locator('.oxd-table:has(.oxd-table-th:text-is("Qualifications"))'), ['Skill', 'Years of Experience', 'Actions'], 'Qualifications (table)');
  }

  /** Qualifications (table) */
  // UNSTABLE: 5 elements on this page resolve to this same locator — it needs scoping to one of them
  get qualificationsTable4(): TableComponent {
    return new TableComponent(this.page.locator('.oxd-table:has(.oxd-table-th:text-is("Qualifications"))'), ['Language', 'Fluency', 'Competency', 'Comments', 'Actions'], 'Qualifications (table)');
  }

  /** Qualifications (table) */
  // UNSTABLE: 5 elements on this page resolve to this same locator — it needs scoping to one of them
  get qualificationsTable5(): TableComponent {
    return new TableComponent(this.page.locator('.oxd-table:has(.oxd-table-th:text-is("Qualifications"))'), ['License Type', 'Issued Date', 'Expiry Date', 'Actions'], 'Qualifications (table)');
  }
}
