// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-pim-viewSalaryList-empNumber-id
// Your own methods belong in SalaryListPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/viewSalaryList/empNumber/{id} */
export abstract class SalaryListPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/viewSalaryList/empNumber/{id}';

  constructor(page: Page) {
    super(page, SalaryListPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** PIM (text) */
  get pimHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'PIM');
  }

  /** Automation QE (text) */
  get automationQeHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Automation QE');
  }

  /** Assigned Salary Components (text) */
  get assignedSalaryComponentsHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Assigned Salary Components');
  }

  /** Attachments (text) */
  get attachmentsHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Attachments');
  }

  /** Records (table) */
  get recordsTable(): TableComponent {
    return new TableComponent(this.page.locator('.oxd-table:has(.oxd-table-th:text-is("Salary Component"))'), ['Salary Component', 'Amount', 'Currency', 'Pay Frequency', 'Direct Deposit Amount', 'File Name', 'Description', 'Size', 'Type', 'Date Added', 'Added By', 'Actions'], 'Records (table)');
  }
}
