// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: pim_employee_tax_exemption
// Your own methods belong in UsTaxExemptionsPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/pim/viewUsTaxExemptions/empNumber/{empNumber} */
export abstract class UsTaxExemptionsPageGenerated extends BasePage {
  static readonly path = '/web/index.php/pim/viewUsTaxExemptions/empNumber/{empNumber}';

  constructor(page: Page) {
    super(page, UsTaxExemptionsPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Status (dropdown) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get statusDropdown(): DropdownComponent {
    return new DropdownComponent(this.page.locator('.oxd-input-group:has(label:text-is("Status")) .oxd-select-text'), 'Status (dropdown)');
  }

  /** Exemptions (input) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get exemptionsInput(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Exemptions")) input'), 'Exemptions (input)');
  }

  /** State (dropdown) */
  get stateDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'State');
  }

  /** Status (dropdown) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get statusDropdown2(): DropdownComponent {
    return new DropdownComponent(this.page.locator('.oxd-input-group:has(label:text-is("Status")) .oxd-select-text'), 'Status (dropdown)');
  }

  /** Exemptions (input) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get exemptionsInput2(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Exemptions")) input'), 'Exemptions (input)');
  }

  /** Unemployment State (dropdown) */
  get unemploymentStateDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Unemployment State');
  }

  /** Work State (dropdown) */
  get workStateDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Work State');
  }

  /** Save (button) */
  get saveButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Save');
  }
}
