// Shared machinery for the four scaffold languages (Java, Python, C#, JavaScript).
//
// Each of them emits the same three things: the idiomatic folder tree, the
// project file, and a BasePage / BaseComponent pair so the architecture is
// visible from the first commit. Page-object generation from the application
// map is implemented for TypeScript only; `renderPage` returning null is how an
// adapter says so, and generate.ts reports it instead of failing.

import type { GenerationContext, LanguageAdapter, ScaffoldDefinition } from '../types.js';

/** Build an adapter from a language-specific definition. */
export function makeScaffold(def: ScaffoldDefinition): LanguageAdapter {
  return {
    id: def.id,
    extension: def.extension,
    emptyDirs: () => def.emptyDirs,
    staticFiles: (context) => [
      ...def.files(context),
      { path: 'README.md', contents: scaffoldReadme(def, context), kind: 'generated' },
      { path: '.env.example', contents: envExample(context), kind: 'protected' },
    ],
    renderPage: () => null,
    renderTest: () => null,
  };
}

function envExample(context: GenerationContext): string {
  return `# Copy to .env and fill in. Never commit .env.
BASE_URL=${context.config.baseUrl}
APP_USERNAME=
APP_PASSWORD=
`;
}

function scaffoldReadme(def: ScaffoldDefinition, context: GenerationContext): string {
  const { model, config } = context;
  return `# ${config.projectName}

Playwright ${def.displayName} framework scaffold, generated by \`framework-generator\`.

## Status

The folder structure, project file, and base classes are generated. **Page objects
are not generated for ${def.displayName} yet** — only the TypeScript adapter reads the
application map today. The map is ready and waiting: ${model.pages.length} page(s),
${model.stats.elementsRead} element(s) in \`${config.mapDir}\`.

To generate working page objects now, set \`language: typescript\` in
\`generator-config.yaml\` and re-run. To add ${def.displayName} support, implement
\`renderPage\` in \`scripts/framework-generator/languages/${def.id}.mjs\` — the orchestrator
needs no changes.

## Layout

${def.layoutNotes}

## Getting started

\`\`\`
${def.gettingStarted}
\`\`\`
`;
}
