// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Admin/Job Title'.
// Your own methods belong in AdminJobTitleClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetAJobTitleResponse, UpdateAJobTitleRequest, UpdateAJobTitleResponse, ListAllJobTitlesResponse, CreateAJobTitleRequest, CreateAJobTitleResponse } from '../../data/testData/AdminJobTitle.types.generated';

export abstract class AdminJobTitleClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/admin/job-titles/{id} */
  async getAJobTitle(id: number): Promise<APIResponse> {
    return this.get(`/api/v2/admin/job-titles/${id}`);
  }

  /** PUT /api/v2/admin/job-titles/{id} */
  async updateAJobTitle(id: number, body: UpdateAJobTitleRequest): Promise<APIResponse> {
    return this.put(`/api/v2/admin/job-titles/${id}`, body);
  }

  /** GET /api/v2/admin/job-titles */
  async listAllJobTitles(query: { activeOnly?: boolean; sortField?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/admin/job-titles` + queryString(query));
  }

  /** POST /api/v2/admin/job-titles */
  async createAJobTitle(body: CreateAJobTitleRequest): Promise<APIResponse> {
    return this.post(`/api/v2/admin/job-titles`, body);
  }

  /** DELETE /api/v2/admin/job-titles */
  async deleteJobTitles(): Promise<APIResponse> {
    return this.delete(`/api/v2/admin/job-titles`);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
