// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Admin/Nationality'.
// Your own methods belong in AdminNationalityClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetANationalityResponse, UpdateANationalityRequest, UpdateANationalityResponse, ListAllNationalitiesResponse, CreateANationalityRequest, CreateANationalityResponse } from '../../data/testData/AdminNationality.types.generated';

export abstract class AdminNationalityClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/admin/nationalities/{id} */
  async getANationality(id: number): Promise<APIResponse> {
    return this.get(`/api/v2/admin/nationalities/${id}`);
  }

  /** PUT /api/v2/admin/nationalities/{id} */
  async updateANationality(id: number, body: UpdateANationalityRequest): Promise<APIResponse> {
    return this.put(`/api/v2/admin/nationalities/${id}`, body);
  }

  /** GET /api/v2/admin/nationalities */
  async listAllNationalities(query: { sortField?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/admin/nationalities` + queryString(query));
  }

  /** POST /api/v2/admin/nationalities */
  async createANationality(body: CreateANationalityRequest): Promise<APIResponse> {
    return this.post(`/api/v2/admin/nationalities`, body);
  }

  /** DELETE /api/v2/admin/nationalities */
  async deleteNationalities(): Promise<APIResponse> {
    return this.delete(`/api/v2/admin/nationalities`);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
