// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Admin/LDAP User Sync'.
// Your own methods belong in AdminLdapUserSyncClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetUserSyncDetailsResponse, SyncLdapUserResponse } from '../../data/testData/AdminLdapUserSync.types.generated';

export abstract class AdminLdapUserSyncClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/admin/ldap/user-sync */
  async getUserSyncDetails(): Promise<APIResponse> {
    return this.get(`/api/v2/admin/ldap/user-sync`);
  }

  /** POST /api/v2/admin/ldap/user-sync */
  async syncLdapUser(): Promise<APIResponse> {
    return this.post(`/api/v2/admin/ldap/user-sync`);
  }
}
