// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Admin/Modules'.
// Your own methods belong in AdminModulesClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { ListAllModulesResponse, UpdateAModuleRequest, UpdateAModuleResponse } from '../../data/testData/AdminModules.types.generated';

export abstract class AdminModulesClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/admin/modules */
  async listAllModules(): Promise<APIResponse> {
    return this.get(`/api/v2/admin/modules`);
  }

  /** PUT /api/v2/admin/modules */
  async updateAModule(body: UpdateAModuleRequest): Promise<APIResponse> {
    return this.put(`/api/v2/admin/modules`, body);
  }
}
