// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Admin/Email Subscription'.
// Your own methods belong in AdminEmailSubscriptionClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetAllEmailSubscriptionsResponse, UpdateEmailSusbcriptionRequest, UpdateEmailSusbcriptionResponse } from '../../data/testData/AdminEmailSubscription.types.generated';

export abstract class AdminEmailSubscriptionClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/admin/email-subscriptions */
  async getAllEmailSubscriptions(query: { sortField?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/admin/email-subscriptions` + queryString(query));
  }

  /** PUT /api/v2/admin/email-subscriptions/{id} */
  async updateEmailSusbcription(id: number, body: UpdateEmailSusbcriptionRequest): Promise<APIResponse> {
    return this.put(`/api/v2/admin/email-subscriptions/${id}`, body);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
