// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Attendance/Attendance Record'.
// Your own methods belong in AttendanceAttendanceRecordClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { ListAnAttendanceRecordResponse, UpdateAnAttendanceRecordRequest, UpdateAnAttendanceRecordResponse, GetTheLatestAttendanceRecordResponse } from '../../data/testData/AttendanceAttendanceRecord.types.generated';

export abstract class AttendanceAttendanceRecordClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/attendance/records/{id} */
  async listAnAttendanceRecord(id: number): Promise<APIResponse> {
    return this.get(`/api/v2/attendance/records/${id}`);
  }

  /** PUT /api/v2/attendance/records/{id} */
  async updateAnAttendanceRecord(id: number, body: UpdateAnAttendanceRecordRequest): Promise<APIResponse> {
    return this.put(`/api/v2/attendance/records/${id}`, body);
  }

  /** GET /api/v2/attendance/records/latest */
  async getTheLatestAttendanceRecord(query: { empNumber?: number } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/attendance/records/latest` + queryString(query));
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
