// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Attendance/Timezones'.
// Your own methods belong in AttendanceTimezonesClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { ListTimezonesResponse } from '../../data/testData/AttendanceTimezones.types.generated';

export abstract class AttendanceTimezonesClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/attendance/timezones */
  async listTimezones(query: { timezoneName?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/attendance/timezones` + queryString(query));
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
