// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Buzz/Comment Likes'.
// Your own methods belong in BuzzCommentLikesClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { ListLikesOnACommentResponse, LikeACommentResponse, UnlikeALikedCommentResponse } from '../../data/testData/BuzzCommentLikes.types.generated';

export abstract class BuzzCommentLikesClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/buzz/comments/{commentId}/likes */
  async listLikesOnAComment(commentId: number, query: { sortField?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/buzz/comments/${commentId}/likes` + queryString(query));
  }

  /** POST /api/v2/buzz/comments/{commentId}/likes */
  async likeAComment(commentId: number): Promise<APIResponse> {
    return this.post(`/api/v2/buzz/comments/${commentId}/likes`);
  }

  /** DELETE /api/v2/buzz/comments/{commentId}/likes */
  async unlikeALikedComment(commentId: number): Promise<APIResponse> {
    return this.delete(`/api/v2/buzz/comments/${commentId}/likes`);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
