// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Buzz/Comments'.
// Your own methods belong in BuzzCommentsClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetACommentOnAPostResponse, EditACommentOnAPostRequest, EditACommentOnAPostResponse, DeleteACommentOnAPostResponse, ListAllCommentsOnAPostResponse, CommentOnAPostRequest, CommentOnAPostResponse } from '../../data/testData/BuzzComments.types.generated';

export abstract class BuzzCommentsClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/buzz/shares/{shareId}/comments/{commentId} */
  async getACommentOnAPost(shareId: number, commentId: number, query: { model?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/buzz/shares/${shareId}/comments/${commentId}` + queryString(query));
  }

  /** PUT /api/v2/buzz/shares/{shareId}/comments/{commentId} */
  async editACommentOnAPost(shareId: number, commentId: number, body: EditACommentOnAPostRequest, query: { model?: string } = {}): Promise<APIResponse> {
    return this.put(`/api/v2/buzz/shares/${shareId}/comments/${commentId}` + queryString(query), body);
  }

  /** DELETE /api/v2/buzz/shares/{shareId}/comments/{commentId} */
  async deleteACommentOnAPost(shareId: number, commentId: number): Promise<APIResponse> {
    return this.delete(`/api/v2/buzz/shares/${shareId}/comments/${commentId}`);
  }

  /** GET /api/v2/buzz/shares/{shareId}/comments */
  async listAllCommentsOnAPost(shareId: number, query: { model?: string; sortField?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/buzz/shares/${shareId}/comments` + queryString(query));
  }

  /** POST /api/v2/buzz/shares/{shareId}/comments */
  async commentOnAPost(shareId: number, body: CommentOnAPostRequest, query: { model?: string } = {}): Promise<APIResponse> {
    return this.post(`/api/v2/buzz/shares/${shareId}/comments` + queryString(query), body);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
