// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Buzz/Share Likes'.
// Your own methods belong in BuzzShareLikesClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { ListLikesOnASharePostResponse, LikeASharePostResponse, UnlikeALikedSharePostResponse } from '../../data/testData/BuzzShareLikes.types.generated';

export abstract class BuzzShareLikesClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/buzz/shares/{shareId}/likes */
  async listLikesOnASharePost(shareId: number, query: { sortField?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/buzz/shares/${shareId}/likes` + queryString(query));
  }

  /** POST /api/v2/buzz/shares/{shareId}/likes */
  async likeASharePost(shareId: number): Promise<APIResponse> {
    return this.post(`/api/v2/buzz/shares/${shareId}/likes`);
  }

  /** DELETE /api/v2/buzz/shares/{shareId}/likes */
  async unlikeALikedSharePost(shareId: number): Promise<APIResponse> {
    return this.delete(`/api/v2/buzz/shares/${shareId}/likes`);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
