// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Buzz/Shares'.
// Your own methods belong in BuzzSharesClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { ListAllSharesOfAPostResponse, ShareAPostRequest, ShareAPostResponse, EditAShareRequest, EditAShareResponse, DeleteAShareResponse } from '../../data/testData/BuzzShares.types.generated';

export abstract class BuzzSharesClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/buzz/posts/{id}/shares */
  async listAllSharesOfAPost(id: number, query: { sortField?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/buzz/posts/${id}/shares` + queryString(query));
  }

  /** POST /api/v2/buzz/shares */
  async shareAPost(body: ShareAPostRequest): Promise<APIResponse> {
    return this.post(`/api/v2/buzz/shares`, body);
  }

  /** PUT /api/v2/buzz/shares/{id} */
  async editAShare(id: number, body: EditAShareRequest): Promise<APIResponse> {
    return this.put(`/api/v2/buzz/shares/${id}`, body);
  }

  /** DELETE /api/v2/buzz/shares/{id} */
  async deleteAShare(id: number): Promise<APIResponse> {
    return this.delete(`/api/v2/buzz/shares/${id}`);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
