// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Buzz/Post'.
// Your own methods belong in BuzzPostClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { PostTextPhotosOrVideoRequest, PostTextPhotosOrVideoResponse, GetAPostResponse, EditAPostRequest, EditAPostResponse } from '../../data/testData/BuzzPost.types.generated';

export abstract class BuzzPostClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** POST /api/v2/buzz/posts */
  async postTextPhotosOrVideo(body: PostTextPhotosOrVideoRequest): Promise<APIResponse> {
    return this.post(`/api/v2/buzz/posts`, body);
  }

  /** GET /api/v2/buzz/posts/{id} */
  async getAPost(id: number, query: { model?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/buzz/posts/${id}` + queryString(query));
  }

  /** PUT /api/v2/buzz/posts/{id} */
  async editAPost(id: number, body: EditAPostRequest, query: { model?: string } = {}): Promise<APIResponse> {
    return this.put(`/api/v2/buzz/posts/${id}` + queryString(query), body);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
