// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Core/About Organization'.
// Your own methods belong in CoreAboutOrganizationClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetBasicOrganizationDetailsResponse } from '../../data/testData/CoreAboutOrganization.types.generated';

export abstract class CoreAboutOrganizationClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/core/about */
  async getBasicOrganizationDetails(): Promise<APIResponse> {
    return this.get(`/api/v2/core/about`);
  }
}
