// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Leave/Employee Bulk Leave'.
// Your own methods belong in LeaveEmployeeBulkLeaveClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { BulkApproveCancelRejectLeavesRequest, BulkApproveCancelRejectLeavesResponse } from '../../data/testData/LeaveEmployeeBulkLeave.types.generated';

export abstract class LeaveEmployeeBulkLeaveClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** PUT /api/v2/leave/leaves/bulk */
  async bulkApproveCancelRejectLeaves(body: BulkApproveCancelRejectLeavesRequest): Promise<APIResponse> {
    return this.put(`/api/v2/leave/leaves/bulk`, body);
  }
}
