// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Leave/Leave Period'.
// Your own methods belong in LeaveLeavePeriodClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetCurrentLeavePeriodResponse, UpdateLeavePeriodRequest, UpdateLeavePeriodResponse, ListAllLeavePeriodsResponse } from '../../data/testData/LeaveLeavePeriod.types.generated';

export abstract class LeaveLeavePeriodClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/leave/leave-period */
  async getCurrentLeavePeriod(): Promise<APIResponse> {
    return this.get(`/api/v2/leave/leave-period`);
  }

  /** PUT /api/v2/leave/leave-period */
  async updateLeavePeriod(body: UpdateLeavePeriodRequest): Promise<APIResponse> {
    return this.put(`/api/v2/leave/leave-period`, body);
  }

  /** GET /api/v2/leave/leave-periods */
  async listAllLeavePeriods(): Promise<APIResponse> {
    return this.get(`/api/v2/leave/leave-periods`);
  }
}
