// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Leave/Leaves'.
// Your own methods belong in LeaveLeavesClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { ListAllLeavesInALeaveRequestResponse, UpdateALeaveRequest, UpdateALeaveResponse } from '../../data/testData/LeaveLeaves.types.generated';

export abstract class LeaveLeavesClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/leave/leave-requests/{leaveRequestId}/leaves */
  async listAllLeavesInALeaveRequest(leaveRequestId: number): Promise<APIResponse> {
    return this.get(`/api/v2/leave/leave-requests/${leaveRequestId}/leaves`);
  }

  /** PUT /api/v2/leave/leaves/{leaveId} */
  async updateALeave(leaveId: number, body: UpdateALeaveRequest): Promise<APIResponse> {
    return this.put(`/api/v2/leave/leaves/${leaveId}`, body);
  }
}
