// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Leave/Leave Report'.
// Your own methods belong in LeaveLeaveReportClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetLeaveReportResponse, GetLeaveReportDataResponse } from '../../data/testData/LeaveLeaveReport.types.generated';

export abstract class LeaveLeaveReportClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/leave/reports */
  async getLeaveReport(query: { name: string }): Promise<APIResponse> {
    return this.get(`/api/v2/leave/reports` + queryString(query));
  }

  /** GET /api/v2/leave/reports/data */
  async getLeaveReportData(query: { name: string; empNumber?: number; fromDate?: string; toDate?: string; includeEmployees?: string }): Promise<APIResponse> {
    return this.get(`/api/v2/leave/reports/data` + queryString(query));
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
