// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Leave/My Leave Request'.
// Your own methods belong in LeaveMyLeaveRequestClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetMyLeaveRequestResponse, UpdateMyLeaveRequestRequest, UpdateMyLeaveRequestResponse, ListMyLeaveRequestsResponse, ApplyForLeaveRequest, ApplyForLeaveResponse } from '../../data/testData/LeaveMyLeaveRequest.types.generated';

export abstract class LeaveMyLeaveRequestClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/leave/leave-requests/{leaveRequestId} */
  async getMyLeaveRequest(leaveRequestId: number, query: { model?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/leave/leave-requests/${leaveRequestId}` + queryString(query));
  }

  /** PUT /api/v2/leave/leave-requests/{leaveRequestId} */
  async updateMyLeaveRequest(leaveRequestId: number, body: UpdateMyLeaveRequestRequest, query: { model?: string } = {}): Promise<APIResponse> {
    return this.put(`/api/v2/leave/leave-requests/${leaveRequestId}` + queryString(query), body);
  }

  /** GET /api/v2/leave/leave-requests */
  async listMyLeaveRequests(query: { leaveTypeId: number; fromDate: number; toDate: number; includeEmployees?: string; statuses?: number; sortField?: string }): Promise<APIResponse> {
    return this.get(`/api/v2/leave/leave-requests` + queryString(query));
  }

  /** POST /api/v2/leave/leave-requests */
  async applyForLeave(body: ApplyForLeaveRequest, query: { model?: string } = {}): Promise<APIResponse> {
    return this.post(`/api/v2/leave/leave-requests` + queryString(query), body);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
