// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Mobile/Menu Items'.
// Your own methods belong in MobileMenuItemsClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { ListMobileMenuItemsResponse } from '../../data/testData/MobileMenuItems.types.generated';

export abstract class MobileMenuItemsClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/mobile/menus */
  async listMobileMenuItems(): Promise<APIResponse> {
    return this.get(`/api/v2/mobile/menus`);
  }
}
