// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'OAuth/OAuth Clients'.
// Your own methods belong in OauthOauthClientsClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { ListAllOauthClientsResponse, CreateAnOauthClientRequest, CreateAnOauthClientResponse, GetAnOauthClientResponse, UpdateAnOauthClientRequest, UpdateAnOauthClientResponse } from '../../data/testData/OauthOauthClients.types.generated';

export abstract class OauthOauthClientsClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/admin/oauth-clients */
  async listAllOauthClients(query: { sortField?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/admin/oauth-clients` + queryString(query));
  }

  /** POST /api/v2/admin/oauth-clients */
  async createAnOauthClient(body: CreateAnOauthClientRequest): Promise<APIResponse> {
    return this.post(`/api/v2/admin/oauth-clients`, body);
  }

  /** DELETE /api/v2/admin/oauth-clients */
  async deleteOauthClients(): Promise<APIResponse> {
    return this.delete(`/api/v2/admin/oauth-clients`);
  }

  /** GET /api/v2/admin/oauth-client/{id} */
  async getAnOauthClient(id: number): Promise<APIResponse> {
    return this.get(`/api/v2/admin/oauth-client/${id}`);
  }

  /** PUT /api/v2/admin/oauth-client/{id} */
  async updateAnOauthClient(id: number, body: UpdateAnOauthClientRequest): Promise<APIResponse> {
    return this.put(`/api/v2/admin/oauth-client/${id}`, body);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
