// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'OpenIDConnect/openid-providers'.
// Your own methods belong in OpenIdconnectOpenidProvidersClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { ListAllOpenidProvidersResponse, CreateOpenidProviderRequest, CreateOpenidProviderResponse, ListAOpenidProviderResponse, UpdateAOpenidProviderRequest, UpdateAOpenidProviderResponse } from '../../data/testData/OpenIdconnectOpenidProviders.types.generated';

export abstract class OpenIdconnectOpenidProvidersClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/auth/openid-providers */
  async listAllOpenidProviders(query: { sortField?: string; status?: boolean; name?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/auth/openid-providers` + queryString(query));
  }

  /** POST /api/v2/auth/openid-providers */
  async createOpenidProvider(body: CreateOpenidProviderRequest): Promise<APIResponse> {
    return this.post(`/api/v2/auth/openid-providers`, body);
  }

  /** DELETE /api/v2/auth/openid-providers */
  async updateOpenidProvider(): Promise<APIResponse> {
    return this.delete(`/api/v2/auth/openid-providers`);
  }

  /** GET /api/v2/auth/openid-providers/{id} */
  async listAOpenidProvider(id: number): Promise<APIResponse> {
    return this.get(`/api/v2/auth/openid-providers/${id}`);
  }

  /** PUT /api/v2/auth/openid-providers/{id} */
  async updateAOpenidProvider(id: number, body: UpdateAOpenidProviderRequest): Promise<APIResponse> {
    return this.put(`/api/v2/auth/openid-providers/${id}`, body);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
