// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Performance/Review Evaluation by Employee'.
// Your own methods belong in PerformanceReviewEvaluationByEmployeeClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetTheEmployeesEvaluationInAReviewResponse, UpdateTheEmployeesEvaluationInAReviewRequest, UpdateTheEmployeesEvaluationInAReviewResponse } from '../../data/testData/PerformanceReviewEvaluationByEmployee.types.generated';

export abstract class PerformanceReviewEvaluationByEmployeeClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/performance/reviews/{reviewId}/evaluation/employee */
  async getTheEmployeesEvaluationInAReview(reviewId: number, query: { sortField?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/performance/reviews/${reviewId}/evaluation/employee` + queryString(query));
  }

  /** PUT /api/v2/performance/reviews/{reviewId}/evaluation/employee */
  async updateTheEmployeesEvaluationInAReview(reviewId: number, body: UpdateTheEmployeesEvaluationInAReviewRequest): Promise<APIResponse> {
    return this.put(`/api/v2/performance/reviews/${reviewId}/evaluation/employee`, body);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
