// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'PIM/Employment Contract'.
// Your own methods belong in PimEmploymentContractClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetAnEmployeesEmploymentContractResponse, UpdateAnEmployeesEmploymentContractRequest, UpdateAnEmployeesEmploymentContractResponse } from '../../data/testData/PimEmploymentContract.types.generated';

export abstract class PimEmploymentContractClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/pim/employees/{empNumber}/employment-contract */
  async getAnEmployeesEmploymentContract(empNumber: number): Promise<APIResponse> {
    return this.get(`/api/v2/pim/employees/${empNumber}/employment-contract`);
  }

  /** PUT /api/v2/pim/employees/{empNumber}/employment-contract */
  async updateAnEmployeesEmploymentContract(empNumber: number, body: UpdateAnEmployeesEmploymentContractRequest): Promise<APIResponse> {
    return this.put(`/api/v2/pim/employees/${empNumber}/employment-contract`, body);
  }
}
