// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'PIM/Employee Supervisor'.
// Your own methods belong in PimEmployeeSupervisorClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetAnEmployeesSupervisorResponse, ListAnEmployeesSupervisorsPimResponse, AddASupervisorToAnEmployeeRequest, AddASupervisorToAnEmployeeResponse } from '../../data/testData/PimEmployeeSupervisor.types.generated';

export abstract class PimEmployeeSupervisorClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/pim/employees/{empNumber}/supervisors/{id} */
  async getAnEmployeesSupervisor(empNumber: number, id: number): Promise<APIResponse> {
    return this.get(`/api/v2/pim/employees/${empNumber}/supervisors/${id}`);
  }

  /** GET /api/v2/pim/employees/{empNumber}/supervisors */
  async listAnEmployeesSupervisorsPim(empNumber: number, query: { sortField?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/pim/employees/${empNumber}/supervisors` + queryString(query));
  }

  /** POST /api/v2/pim/employees/{empNumber}/supervisors */
  async addASupervisorToAnEmployee(empNumber: number, body: AddASupervisorToAnEmployeeRequest): Promise<APIResponse> {
    return this.post(`/api/v2/pim/employees/${empNumber}/supervisors`, body);
  }

  /** DELETE /api/v2/pim/employees/{empNumber}/supervisors */
  async deleteAnEmployeesSupervisors(empNumber: number): Promise<APIResponse> {
    return this.delete(`/api/v2/pim/employees/${empNumber}/supervisors`);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
