// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'PIM/Employee Count'.
// Your own methods belong in PimEmployeeCountClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetTheNumberOfEmployeesResponse } from '../../data/testData/PimEmployeeCount.types.generated';

export abstract class PimEmployeeCountClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/pim/employees/count */
  async getTheNumberOfEmployees(query: { name?: string; nameOrId?: string; employeeId?: number; jobTitleId?: number; subunitId?: number; empStatusId?: number; locationId?: number; includeEmployees?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/pim/employees/count` + queryString(query));
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
