// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'PIM/Employee Work Shift'.
// Your own methods belong in PimEmployeeWorkShiftClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetAnEmployeesWorkShiftResponse } from '../../data/testData/PimEmployeeWorkShift.types.generated';

export abstract class PimEmployeeWorkShiftClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/pim/employees/{empNumber}/work-shift */
  async getAnEmployeesWorkShift(empNumber: number): Promise<APIResponse> {
    return this.get(`/api/v2/pim/employees/${empNumber}/work-shift`);
  }
}
