// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'PIM/Reporting Method Configuration'.
// Your own methods belong in PimReportingMethodConfigurationClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetAReportingMethodResponse, UpdateAReportingMethodRequest, UpdateAReportingMethodResponse, ListAllReportingMethodsResponse, CreateAReportingMethodRequest, CreateAReportingMethodResponse } from '../../data/testData/PimReportingMethodConfiguration.types.generated';

export abstract class PimReportingMethodConfigurationClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/pim/reporting-methods/{id} */
  async getAReportingMethod(id: number): Promise<APIResponse> {
    return this.get(`/api/v2/pim/reporting-methods/${id}`);
  }

  /** PUT /api/v2/pim/reporting-methods/{id} */
  async updateAReportingMethod(id: number, body: UpdateAReportingMethodRequest): Promise<APIResponse> {
    return this.put(`/api/v2/pim/reporting-methods/${id}`, body);
  }

  /** GET /api/v2/pim/reporting-methods */
  async listAllReportingMethods(query: { sortField?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/pim/reporting-methods` + queryString(query));
  }

  /** POST /api/v2/pim/reporting-methods */
  async createAReportingMethod(body: CreateAReportingMethodRequest): Promise<APIResponse> {
    return this.post(`/api/v2/pim/reporting-methods`, body);
  }

  /** DELETE /api/v2/pim/reporting-methods */
  async deleteReportingMethods(): Promise<APIResponse> {
    return this.delete(`/api/v2/pim/reporting-methods`);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
