// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'PIM/Update Password'.
// Your own methods belong in PimUpdatePasswordClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { UpdatePasswordRequest, UpdatePasswordResponse } from '../../data/testData/PimUpdatePassword.types.generated';

export abstract class PimUpdatePasswordClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** PUT /api/v2/pim/update-password */
  async updatePassword(body: UpdatePasswordRequest): Promise<APIResponse> {
    return this.put(`/api/v2/pim/update-password`, body);
  }
}
