// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Recruitment/Vacancy'.
// Your own methods belong in RecruitmentVacancyClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetAVacancyResponse, UpdateAVacancyRequest, UpdateAVacancyResponse, ListAllVacanciesResponse, CreateAVacancyRequest, CreateAVacancyResponse } from '../../data/testData/RecruitmentVacancy.types.generated';

export abstract class RecruitmentVacancyClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/recruitment/vacancies/{id} */
  async getAVacancy(id: number): Promise<APIResponse> {
    return this.get(`/api/v2/recruitment/vacancies/${id}`);
  }

  /** PUT /api/v2/recruitment/vacancies/{id} */
  async updateAVacancy(id: number, body: UpdateAVacancyRequest): Promise<APIResponse> {
    return this.put(`/api/v2/recruitment/vacancies/${id}`, body);
  }

  /** GET /api/v2/recruitment/vacancies */
  async listAllVacancies(query: { sortField?: string; jobTitleId?: number; hiringManagerId?: number; status?: boolean; name?: string; vacancyId?: number } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/recruitment/vacancies` + queryString(query));
  }

  /** POST /api/v2/recruitment/vacancies */
  async createAVacancy(body: CreateAVacancyRequest): Promise<APIResponse> {
    return this.post(`/api/v2/recruitment/vacancies`, body);
  }

  /** DELETE /api/v2/recruitment/vacancies */
  async deleteVacancies(): Promise<APIResponse> {
    return this.delete(`/api/v2/recruitment/vacancies`);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
