// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Time/Timesheet Action Log'.
// Your own methods belong in TimeTimesheetActionLogClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetATimesheetsActionLogsResponse } from '../../data/testData/TimeTimesheetActionLog.types.generated';

export abstract class TimeTimesheetActionLogClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/time/timesheets/{timesheetId}/action-logs */
  async getATimesheetsActionLogs(timesheetId: number, query: { sortField?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/time/timesheets/${timesheetId}/action-logs` + queryString(query));
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
