// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Time/Customers'.
// Your own methods belong in TimeCustomersClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { ListAllCustomersResponse, CreateACustomerRequest, CreateACustomerResponse, GetACustomerResponse, UpdateACustomerRequest, UpdateACustomerResponse } from '../../data/testData/TimeCustomers.types.generated';

export abstract class TimeCustomersClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/time/customers */
  async listAllCustomers(query: { name?: string; sortField?: string } = {}): Promise<APIResponse> {
    return this.get(`/api/v2/time/customers` + queryString(query));
  }

  /** POST /api/v2/time/customers */
  async createACustomer(body: CreateACustomerRequest): Promise<APIResponse> {
    return this.post(`/api/v2/time/customers`, body);
  }

  /** DELETE /api/v2/time/customers */
  async deleteCustomers(): Promise<APIResponse> {
    return this.delete(`/api/v2/time/customers`);
  }

  /** GET /api/v2/time/customers/{id} */
  async getACustomer(id: number): Promise<APIResponse> {
    return this.get(`/api/v2/time/customers/${id}`);
  }

  /** PUT /api/v2/time/customers/{id} */
  async updateACustomer(id: number, body: UpdateACustomerRequest): Promise<APIResponse> {
    return this.put(`/api/v2/time/customers/${id}`, body);
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
