// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Time/Timesheet Report'.
// Your own methods belong in TimeTimesheetReportClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetTimeReportsResponse, GetTimeReportDataResponse } from '../../data/testData/TimeTimesheetReport.types.generated';

export abstract class TimeTimesheetReportClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/time/reports */
  async getTimeReports(query: { name: string }): Promise<APIResponse> {
    return this.get(`/api/v2/time/reports` + queryString(query));
  }

  /** GET /api/v2/time/reports/data */
  async getTimeReportData(query: { name: string; projectId: string; limit?: number; fromDate?: string; toDate?: string }): Promise<APIResponse> {
    return this.get(`/api/v2/time/reports/data` + queryString(query));
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
