// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Time/Validation'.
// Your own methods belong in TimeValidationClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { ValidateProjectActivityUniquenessInTimesheetResponse, ValidateProjectNameUniquenessResponse, ValidateCustomerNameUniquenessResponse, ValidateProjectActivityNameUniquenessResponse } from '../../data/testData/TimeValidation.types.generated';

export abstract class TimeValidationClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/time/validation/{timesheetId}/project-activity */
  async validateProjectActivityUniquenessInTimesheet(timesheetId: number, query: { projectId: number; activityId: number }): Promise<APIResponse> {
    return this.get(`/api/v2/time/validation/${timesheetId}/project-activity` + queryString(query));
  }

  /** GET /api/v2/time/validation/project-name */
  async validateProjectNameUniqueness(query: { projectId?: number; projectName: string; customerId?: number }): Promise<APIResponse> {
    return this.get(`/api/v2/time/validation/project-name` + queryString(query));
  }

  /** GET /api/v2/time/validation/customer-name */
  async validateCustomerNameUniqueness(query: { customerId?: number; customerName: string }): Promise<APIResponse> {
    return this.get(`/api/v2/time/validation/customer-name` + queryString(query));
  }

  /** GET /api/v2/time/validation/activity-name/{id} */
  async validateProjectActivityNameUniqueness(id: number, query: { activityId?: number; activityName: string }): Promise<APIResponse> {
    return this.get(`/api/v2/time/validation/activity-name/${id}` + queryString(query));
  }
}

function queryString(params: Record<string, unknown>): string {
  const entries = Object.entries(params).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '';
  return `?${entries.map(([k, v]) => `${k}=${encodeURIComponent(String(v))}`).join('&')}`;
}
