// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Time/Timesheet Time Format'.
// Your own methods belong in TimeTimesheetTimeFormatClient.ts, which the generator never touches.

import type { APIRequestContext, APIResponse } from '@playwright/test';
import { ApiClient } from './ApiClient';
import type { GetTimesheetTimeFormatResponse } from '../../data/testData/TimeTimesheetTimeFormat.types.generated';

export abstract class TimeTimesheetTimeFormatClientGenerated extends ApiClient {
  constructor(request: APIRequestContext) {
    super(request);
  }

  /** GET /api/v2/time/config/time-format */
  async getTimesheetTimeFormat(): Promise<APIResponse> {
    return this.get(`/api/v2/time/config/time-format`);
  }
}
