// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('HelpPage', () => {
  test('loads', async ({ helpPage }) => {
    await helpPage.goto();
    await expect(helpPage.page).toHaveURL(new RegExp('/web/index\\.php/help/help'));
  });
});
