// The shared markdown writer. Every analysis file opens with the same provenance header —
// app path, commit, framework, timestamp — so a stale file is visible rather than silent.

import fs from 'node:fs';
import path from 'node:path';
import {loadProjectConfig, slugifyAppName} from '../project-config.js';
import {REPO_ROOT, gitSha, rel} from './util.js';
import type {CliArgs, DetectionResult} from './types.js';

/**
 * Every report for one app lands in `analysis/<app>/`, the app named in app-config.yaml —
 * so analyzing a second app adds a folder instead of overwriting the first one's reports.
 * `--app` names its own folder, keeping the folder honest about which clone was read.
 * Resolved per call rather than at import time: a pure-function test must not need a
 * project config on disk to import this module.
 */
export function analysisDir(args: CliArgs = {}): string {
  const name = args.app
    ? slugifyAppName(path.basename(path.resolve(REPO_ROOT, String(args.app))))
    : loadProjectConfig().appName;
  return path.join(REPO_ROOT, 'analysis', name);
}

export function escapeCell(value: unknown) {
  if (value === null || value === undefined || value === '') return '—';
  return String(value).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

export function table(headers: string[], rows: unknown[][]) {
  if (rows.length === 0) return '_No rows._\n';
  const lines = [
    `| ${headers.join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.map(escapeCell).join(' | ')} |`),
  ];
  return `${lines.join('\n')}\n`;
}

export function header(title: string, detection: DetectionResult, extra: string[] = []) {
  const backend = detection.backend
    ? `${detection.backend.label} (${detection.backend.method})`
    : 'not detected';
  return [
    `# ${title}`,
    '',
    '<!-- Generated by scripts/repo-analyzer — do not hand-edit; re-run the analyzer instead. -->',
    '',
    `- **App**: \`${detection.appPath}\` @ \`${gitSha(detection.appPath)}\``,
    `- **Frontend**: ${detection.frontend.label}${detection.frontend.version ? ` ${detection.frontend.version}` : ''} — \`${rel(detection.appPath, detection.frontend.sourceRoot) || '.'}\``,
    `- **Backend**: ${backend}`,
    `- **Generated**: ${new Date().toISOString()}`,
    ...extra.map((line) => `- ${line}`),
    '',
  ].join('\n');
}

/**
 * Write the markdown report and, when `data` is given, a JSON sidecar. The sidecar is what the
 * next analyzer in the chain reads — re-parsing a markdown table would be the fragile path.
 */
export function writeReport({outFile, body, data, dryRun}: {outFile: string; body: string; data?: unknown; dryRun?: boolean}): {written: string[]} {
  if (dryRun) {
    process.stdout.write(body);
    return {written: []};
  }
  fs.mkdirSync(path.dirname(outFile), {recursive: true});
  fs.writeFileSync(outFile, body, 'utf8');
  const written = [rel(REPO_ROOT, outFile)];
  if (data) {
    const jsonFile = outFile.replace(/\.md$/, '.json');
    fs.writeFileSync(jsonFile, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
    written.push(rel(REPO_ROOT, jsonFile));
  }
  return {written};
}

export function outPath(args: CliArgs, defaultName: string) {
  return args.out ? path.resolve(REPO_ROOT, String(args.out)) : path.join(analysisDir(args), defaultName);
}

export function reportWritten({written}: {written: string[]}, summaryLines: string[] = []) {
  for (const line of summaryLines) process.stderr.write(`${line}\n`);
  for (const file of written) process.stderr.write(`wrote ${file}\n`);
}
