// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';
import { assertShape } from '../../../src/utils/schema-assert';

test.describe('Performance/Trackers — list-all-employee-trackers', () => {
  test('GET /api/v2/performance/employees/trackers responds 200', async ({ performanceTrackersApi }) => {
    const response = await performanceTrackersApi.listAllEmployeeTrackers({});
    expect(response.status()).toBe(200);
    const body = await response.json();
    assertShape(body, {"kind":"object","properties":[{"name":"data","type":"unknown","required":false,"nullable":false},{"name":"meta","type":"unknown","required":false,"nullable":false}]});
  });
});
