// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('PIM/Employee Supervisor — delete-an-employees-supervisors', () => {
  test('DELETE /api/v2/pim/employees/{empNumber}/supervisors responds 200', async ({ pimEmployeeSupervisorApi }) => {
    const response = await pimEmployeeSupervisorApi.deleteAnEmployeesSupervisors('REPLACE_ME' as never);
    expect(response.status()).toBe(200);
  });
});
