// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('Admin/Locations — delete-locations', () => {
  test('DELETE /api/v2/admin/locations responds 200', async ({ adminLocationsApi }) => {
    const response = await adminLocationsApi.deleteLocations();
    expect(response.status()).toBe(200);
  });
});
