// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('Admin/Memberships — delete-memberships', () => {
  test('DELETE /api/v2/admin/memberships responds 200', async ({ adminMembershipsApi }) => {
    const response = await adminMembershipsApi.deleteMemberships();
    expect(response.status()).toBe(200);
  });
});
