import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const target = process.argv.includes('--opencode') ? 'opencode' : 'codexcli';
const client = target === 'opencode' ? 'OpenCode' : 'Codex';
const agentPath = target === 'opencode' ? '.opencode/agents/test-writer.md' : '.codex/agents/test-writer.toml';
const stage = await mkdtemp(join(tmpdir(), 'qa-agent-sync-'));
const cli = join(root, 'node_modules/rulesync/dist/cli/index.js');
const check = process.argv.includes('--check');
const run = (args) => execFileSync(process.execPath, [cli, ...args], { cwd: stage, stdio: 'inherit' });

try {
  await mkdir(join(stage, '.claude/agents'), { recursive: true });
  // .mcp.json is optional: this repo declares no MCP servers, and a checkout that
  // adds one should still sync. rulesync's `mcp` feature simply finds nothing.
  for (const path of ['CLAUDE.md', '.mcp.json', '.claude/settings.json', '.claude/skills']) {
    await cp(join(root, path), join(stage, path), { recursive: true, force: true })
      .catch((err) => { if (err.code !== 'ENOENT') throw err; });
  }
  // The other Markdown file is a shared, mutable reference table, not an agent.
  for (const name of ['test-preconditions', 'test-writer', 'test-runner']) {
    const source = await readFile(join(root, '.claude/agents', `${name}.md`), 'utf8');
    await writeFile(join(stage, '.claude/agents', `${name}.md`), source
      .replaceAll('`known-issues.md`, next to this file', '`.claude/agents/test-runner-known-issues.md`')
      .replaceAll('`test-writer.md`', `\`${agentPath}\``)
      + `\n\n${client}: Claude hooks do not automatically enforce ${client} writes. Follow the same rules in \`.claude/hooks/rules/\` and the client integration sections of \`AGENTS.md\`.\n`);
  }
  run(['import', '--targets', 'claudecode', '--features', 'rules,skills,subagents,mcp,hooks']);
  const rule = join(stage, '.rulesync/rules/CLAUDE.md');
  let instructions = await readFile(rule, 'utf8');
  instructions = instructions.replace('# CLAUDE.md', '# AGENTS.md')
    .replace('Claude Code (claude.ai/code)', 'Codex and OpenCode')
    .replace('via the Agent tool with `subagent_type: "test-preconditions"`', 'using the current client\'s subagent tool with the `test-preconditions` agent instructions')
    .replaceAll('Agent tool', 'subagent tool');
  instructions += '\n## Codex integration\n\n'
    + 'Generated by `npm run codex:sync` from `CLAUDE.md` and `.claude/`; edit those sources and regenerate. '
    + 'Skills are in `.agents/skills/`; invoke them as `$setup`, `$app-explorer`, and so on. '
    + 'Claude slash-command examples in the source mean the corresponding Codex skill. '
    + 'Custom agents are in `.codex/agents/*.toml` and inherit the session model. '
    + 'If named agents are unavailable in the current client, pass the matching TOML developer_instructions to its available subagent tool. '
    + 'Keep shared helper commands and the mutable known-issues table at their existing `.claude/` paths.\n\n'
    + 'The hook-enforced section above describes Claude Code enforcement. The Claude hooks accept Write/Edit/MultiEdit payloads, '
    + 'not Codex apply_patch or shell payloads, so they are not registered as Codex hooks. '
    + 'Their write and browser policies still apply as instructions: read `.claude/hooks/rules/` before editing generated-framework files '
    + 'and run `npm run hooks:test` when changing those policies. This is not automatic enforcement of Codex writes. '
    + 'Claude plugin enablement and scheduled-task state are client-specific and are not copied.\n';
  instructions += '\n## OpenCode integration\n\n'
    + 'Generated by `npm run opencode:sync` from the same Claude sources. Both refresh commands generate identical shared `AGENTS.md` instructions. '
    + 'OpenCode skills are in `.opencode/skills/`; ask to use the `setup` skill (or another skill by name) through the native `skill` tool. '
    + 'The `$skill-name` syntax above is Codex-specific; Claude slash-command examples mean loading the corresponding skill. '
    + 'OpenCode subagents are in `.opencode/agents/*.md`, run in subagent mode, and inherit the calling agent model. '
    + 'Delegate the test-preconditions → test-writer → test-runner chain with the Task tool; agents can also be mentioned by name with `@`. '
    + 'Shared helper commands and the mutable known-issues table remain at their `.claude/` paths. '
    + 'Claude hooks are not registered as OpenCode plugins: their payloads and tool-name matchers are Claude-specific. '
    + 'Follow the same write and browser policies as instructions; automatic hook enforcement is not provided. '
    + 'Claude plugin enablement and scheduled-task state are not copied.\n';
  await writeFile(rule, instructions);
  run(['generate', '--targets', target, '--features', 'rules,skills,subagents,mcp',
    '--output-roots', root, ...(check ? ['--check'] : [])]);
} finally {
  await rm(stage, { recursive: true, force: true });
}
