// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-time-displayAttendanceSummaryReportCriteria
// Your own methods belong in DisplayAttendanceSummaryReportCriteriaPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/time/displayAttendanceSummaryReportCriteria */
export abstract class DisplayAttendanceSummaryReportCriteriaPageGenerated extends BasePage {
  static readonly path = '/web/index.php/time/displayAttendanceSummaryReportCriteria';

  constructor(page: Page) {
    super(page, DisplayAttendanceSummaryReportCriteriaPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Timesheets (menuItem) */
  get timesheetsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Timesheets")'), 'Timesheets (menuItem)');
  }

  /** Attendance (menuItem) */
  get attendanceMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Attendance")'), 'Attendance (menuItem)');
  }

  /** Reports (menuItem) */
  get reportsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Reports")'), 'Reports (menuItem)');
  }

  /** Project Info (menuItem) */
  get projectInfoMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Project Info")'), 'Project Info (menuItem)');
  }

  /** Time (text) */
  get timeHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Time');
  }

  /** Attendance Total Summary Report (text) */
  get attendanceTotalSummaryReportHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Attendance Total Summary Report');
  }

  /** Employee Name (input) */
  get employeeNameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Employee Name');
  }

  /** Job Title (dropdown) */
  get jobTitleDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Job Title');
  }

  /** Sub Unit (dropdown) */
  get subUnitDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Sub Unit');
  }

  /** Employment Status (dropdown) */
  get employmentStatusDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Employment Status');
  }

  /** Date Range (input) */
  get dateRangeInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Date Range');
  }

  /** View (button) */
  get viewButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'View');
  }
}
