// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: time_activity_details_report
// Your own methods belong in DisplayProjectActivityDetailsReportPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { DropdownComponent } from '../../components/DropdownComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/time/displayProjectActivityDetailsReport */
export abstract class DisplayProjectActivityDetailsReportPageGenerated extends BasePage {
  static readonly path = '/web/index.php/time/displayProjectActivityDetailsReport';

  constructor(page: Page) {
    super(page, DisplayProjectActivityDetailsReportPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Back (button) */
  get backButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Back');
  }

  /** Project Name (input) */
  get projectNameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Project Name');
  }

  /** Activity Name (dropdown) */
  get activityNameDropdown(): DropdownComponent {
    return DropdownComponent.byLabel(this.page, 'Activity Name');
  }

  /** Project Date Range (input) */
  get projectDateRangeInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Project Date Range');
  }

  /** View (button) */
  get viewButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'View');
  }
}
