// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-time-viewEmployeeTimesheet
// Your own methods belong in EmployeeTimesheetPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { ImageComponent } from '../../components/ImageComponent';
import { InputComponent } from '../../components/InputComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TableComponent } from '../../components/tables/TableComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/time/viewEmployeeTimesheet */
export abstract class EmployeeTimesheetPageGenerated extends BasePage {
  static readonly path = '/web/index.php/time/viewEmployeeTimesheet';

  constructor(page: Page) {
    super(page, EmployeeTimesheetPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Claim img (image) */
  // UNSTABLE: no accessible name; scoped to nearest named ancestor
  get claimImgImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('link', { name: 'Claim', exact: true }).getByRole('img'), 'Claim img (image)');
  }

  /** Time (text) */
  get timeHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Time', exact: true }), 'Time (text)');
  }

  /** / Timesheets (text) */
  get timesheetsHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: '/ Timesheets', exact: true }), '/ Timesheets (text)');
  }

  /** profile picture (image) */
  get profilePictureImage(): ImageComponent {
    return new ImageComponent(this.page.getByRole('img', { name: 'profile picture', exact: true }), 'profile picture (image)');
  }

  /** Select Employee (text) */
  get selectEmployeeHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Select Employee', exact: true }), 'Select Employee (text)');
  }

  /** Type for hints... (input) */
  get typeForHintsInput(): InputComponent {
    return new InputComponent(this.page.getByRole('textbox', { name: 'Type for hints...', exact: true }), 'Type for hints... (input)');
  }

  /** View (button) */
  // UNSTABLE: no accessible name or unique ancestor scope; positional index used
  get viewButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button').nth(3), 'View (button)');
  }

  /** Timesheets Pending Action (text) */
  get timesheetsPendingActionHeading(): TextComponent {
    return new TextComponent(this.page.getByRole('heading', { name: 'Timesheets Pending Action', exact: true }), 'Timesheets Pending Action (text)');
  }

  /** table (table) */
  // UNSTABLE: table has no accessible name; positional index used
  get tableTable(): TableComponent {
    return new TableComponent(this.page.getByRole('table').nth(0), [], 'table (table)');
  }

  /** Elements revealed by opening 'Surya king'. Open the trigger first. */
  readonly suryaKingOpen = new EmployeeTimesheetPageSuryaKingOpen(this.page);
}

/** Only present while 'Surya king' is open. */
export class EmployeeTimesheetPageSuryaKingOpen {
  constructor(private readonly page: Page) {}

  /** About (menuItem) */
  get aboutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'About', exact: true }), 'About (menuItem)');
  }

  /** Support (menuItem) */
  get supportMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Support', exact: true }), 'Support (menuItem)');
  }

  /** Change Password (menuItem) */
  get changePasswordMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Change Password', exact: true }), 'Change Password (menuItem)');
  }

  /** Logout (menuItem) */
  get logoutMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.getByRole('menuitem', { name: 'Logout', exact: true }), 'Logout (menuItem)');
  }
}
