// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: web-index.php-time-viewMyTimesheet
// Your own methods belong in MyTimesheetPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { MenuItemComponent } from '../../components/MenuItemComponent';
import { TextComponent } from '../../components/TextComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/time/viewMyTimesheet */
export abstract class MyTimesheetPageGenerated extends BasePage {
  static readonly path = '/web/index.php/time/viewMyTimesheet';

  constructor(page: Page) {
    super(page, MyTimesheetPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Timesheets (menuItem) */
  get timesheetsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Timesheets")'), 'Timesheets (menuItem)');
  }

  /** Attendance (menuItem) */
  get attendanceMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Attendance")'), 'Attendance (menuItem)');
  }

  /** Reports (menuItem) */
  get reportsMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Reports")'), 'Reports (menuItem)');
  }

  /** Project Info (menuItem) */
  get projectInfoMenuItem(): MenuItemComponent {
    return new MenuItemComponent(this.page.locator('.oxd-topbar-body-nav-tab-item:has-text("Project Info")'), 'Project Info (menuItem)');
  }

  /** Time (text) */
  get timeHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'Time');
  }

  /** My Timesheet (text) */
  get myTimesheetHeading(): TextComponent {
    return TextComponent.byHeading(this.page, 'My Timesheet');
  }

  /** Edit (button) */
  get editButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Edit');
  }

  /** Submit (button) */
  get submitButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Submit');
  }
}
