// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: time_edit_project
// Your own methods belong in SaveProjectPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { ButtonComponent } from '../../components/ButtonComponent';
import { InputComponent } from '../../components/InputComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/time/saveProject/{id} (also reachable at /web/index.php/time/saveProject) */
export abstract class SaveProjectPageGenerated extends BasePage {
  static readonly path = '/web/index.php/time/saveProject/{id}';
  static readonly aliases = ['/web/index.php/time/saveProject'] as const;

  constructor(page: Page) {
    super(page, SaveProjectPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Name (input) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get nameInput(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Name")) input'), 'Name (input)');
  }

  /** Add Customer (button) */
  get addCustomerButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Add Customer');
  }

  /** Description (longInput) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get descriptionLongInput(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Description")) textarea'), 'Description (longInput)');
  }

  /** Add another (button) */
  get addAnotherButton(): ButtonComponent {
    return ButtonComponent.byLabel(this.page, 'Add another');
  }

  /** Cancel (button) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get cancelButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Cancel', exact: true }), 'Cancel (button)');
  }

  /** Customer Name (input) */
  get customerNameInput(): InputComponent {
    return InputComponent.byLabel(this.page, 'Customer Name');
  }

  /** Save (button) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get saveButton(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Save', exact: true }), 'Save (button)');
  }

  /** Name (input) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get nameInput2(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Name")) input'), 'Name (input)');
  }

  /** Description (longInput) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get descriptionLongInput2(): InputComponent {
    return new InputComponent(this.page.locator('.oxd-input-group:has(label:text-is("Description")) textarea'), 'Description (longInput)');
  }

  /** Cancel (button) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get cancelButton2(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Cancel', exact: true }), 'Cancel (button)');
  }

  /** Save (button) */
  // UNSTABLE: 2 elements on this page resolve to this same locator — it needs scoping to one of them
  get saveButton2(): ButtonComponent {
    return new ButtonComponent(this.page.getByRole('button', { name: 'Save', exact: true }), 'Save (button)');
  }
}
