// Generated once from analysis.json (56e23b3b09) on 2026-09-15.
// This file is yours now. Nothing regenerates it.

import type { APIRequestContext } from '@playwright/test';
import { ApiClient, idOf } from './ApiClient.ts';
import { BASE_URL } from '../config/constants.ts';
import { AboutApi } from './AboutApi.ts';
import { ActionSummaryApi } from './ActionSummaryApi.ts';
import { ActivityNameApi } from './ActivityNameApi.ts';
import { AnniversaryApi } from './AnniversaryApi.ts';
import { AttachmentApi } from './AttachmentApi.ts';
import { BulkApi } from './BulkApi.ts';
import { CandidateApi } from './CandidateApi.ts';
import { CommentApi } from './CommentApi.ts';
import { ConfigApi } from './ConfigApi.ts';
import { CountApi } from './CountApi.ts';
import { CsvImportApi } from './CsvImportApi.ts';
import { CurrentDatetimeApi } from './CurrentDatetimeApi.ts';
import { CustomerApi } from './CustomerApi.ts';
import { CustomerNameApi } from './CustomerNameApi.ts';
import { CustomFieldApi } from './CustomFieldApi.ts';
import { DatumApi } from './DatumApi.ts';
import { DefaultApi } from './DefaultApi.ts';
import { DefinedApi } from './DefinedApi.ts';
import { EducationApi } from './EducationApi.ts';
import { EligibleApi } from './EligibleApi.ts';
import { EmailConfigurationApi } from './EmailConfigurationApi.ts';
import { EmailSubscriptionApi } from './EmailSubscriptionApi.ts';
import { EmployeeApi } from './EmployeeApi.ts';
import { EmployeeOnLeaveTodayApi } from './EmployeeOnLeaveTodayApi.ts';
import { EmploymentStatusApi } from './EmploymentStatusApi.ts';
import { EventApi } from './EventApi.ts';
import { FeedApi } from './FeedApi.ts';
import { GroupApi } from './GroupApi.ts';
import { HiringManagerApi } from './HiringManagerApi.ts';
import { HolidayApi } from './HolidayApi.ts';
import { InterviewApi } from './InterviewApi.ts';
import { InterviwerApi } from './InterviwerApi.ts';
import { JobCategoryApi } from './JobCategoryApi.ts';
import { JobTitleApi } from './JobTitleApi.ts';
import { KpisApi } from './KpisApi.ts';
import { LanguageApi } from './LanguageApi.ts';
import { LatestApi } from './LatestApi.ts';
import { LdapConfigApi } from './LdapConfigApi.ts';
import { LdapTestConnectionApi } from './LdapTestConnectionApi.ts';
import { LeaveApi } from './LeaveApi.ts';
import { LeaveBalanceApi } from './LeaveBalanceApi.ts';
import { LeaveEntitlementApi } from './LeaveEntitlementApi.ts';
import { LeavePeriodApi } from './LeavePeriodApi.ts';
import { LeaveRequestApi } from './LeaveRequestApi.ts';
import { LeaveTypeApi } from './LeaveTypeApi.ts';
import { LicensApi } from './LicensApi.ts';
import { LinkApi } from './LinkApi.ts';
import { ListApi } from './ListApi.ts';
import { LocalizationApi } from './LocalizationApi.ts';
import { LocationApi } from './LocationApi.ts';
import { MembershipApi } from './MembershipApi.ts';
import { MenusApi } from './MenusApi.ts';
import { ModuleApi } from './ModuleApi.ts';
import { MyselfApi } from './MyselfApi.ts';
import { NationalityApi } from './NationalityApi.ts';
import { OauthClientApi } from './OauthClientApi.ts';
import { OpenidProviderApi } from './OpenidProviderApi.ts';
import { OptionalFieldApi } from './OptionalFieldApi.ts';
import { OrganizationApi } from './OrganizationApi.ts';
import { OverlapApi } from './OverlapApi.ts';
import { OverlapLeaveApi } from './OverlapLeaveApi.ts';
import { PayGradeApi } from './PayGradeApi.ts';
import { PostApi } from './PostApi.ts';
import { PreviewApi } from './PreviewApi.ts';
import { ProjectApi } from './ProjectApi.ts';
import { ProjectAdminApi } from './ProjectAdminApi.ts';
import { ProjectNameApi } from './ProjectNameApi.ts';
import { PunchInOverlapApi } from './PunchInOverlapApi.ts';
import { PunchOutOverlapApi } from './PunchOutOverlapApi.ts';
import { PurgeApi } from './PurgeApi.ts';
import { RecordApi } from './RecordApi.ts';
import { RegistrationApi } from './RegistrationApi.ts';
import { ReportApi } from './ReportApi.ts';
import { ReportingMethodApi } from './ReportingMethodApi.ts';
import { RequestApi } from './RequestApi.ts';
import { ReviewApi } from './ReviewApi.ts';
import { ReviewerApi } from './ReviewerApi.ts';
import { ShareApi } from './ShareApi.ts';
import { ShortcutApi } from './ShortcutApi.ts';
import { SkillApi } from './SkillApi.ts';
import { StatusApi } from './StatusApi.ts';
import { SubunitApi } from './SubunitApi.ts';
import { SummaryApi } from './SummaryApi.ts';
import { SupervisorApi } from './SupervisorApi.ts';
import { TerminationReasonApi } from './TerminationReasonApi.ts';
import { TestApi } from './TestApi.ts';
import { ThemeApi } from './ThemeApi.ts';
import { TimeAtWorkApi } from './TimeAtWorkApi.ts';
import { TimeFormatApi } from './TimeFormatApi.ts';
import { TimesheetApi } from './TimesheetApi.ts';
import { TimeSheetPeriodApi } from './TimeSheetPeriodApi.ts';
import { TimezoneApi } from './TimezoneApi.ts';
import { TrackerApi } from './TrackerApi.ts';
import { TrackersApi } from './TrackersApi.ts';
import { TranslationApi } from './TranslationApi.ts';
import { TypeApi } from './TypeApi.ts';
import { UniqueApi } from './UniqueApi.ts';
import { UpdatePasswordApi } from './UpdatePasswordApi.ts';
import { UserApi } from './UserApi.ts';
import { UserNameApi } from './UserNameApi.ts';
import { UserSyncApi } from './UserSyncApi.ts';
import { VacancyApi } from './VacancyApi.ts';
import { ValidationApi } from './ValidationApi.ts';
import { WorkShiftApi } from './WorkShiftApi.ts';
import { WorkweekApi } from './WorkweekApi.ts';

/** Every resource the API declares, on one object. */
export class Api {
  readonly http: ApiClient;
  readonly about: AboutApi;
  readonly actionSummary: ActionSummaryApi;
  readonly activityName: ActivityNameApi;
  readonly anniversary: AnniversaryApi;
  readonly attachment: AttachmentApi;
  readonly bulk: BulkApi;
  readonly candidate: CandidateApi;
  readonly comment: CommentApi;
  readonly config: ConfigApi;
  readonly count: CountApi;
  readonly csvImport: CsvImportApi;
  readonly currentDatetime: CurrentDatetimeApi;
  readonly customer: CustomerApi;
  readonly customerName: CustomerNameApi;
  readonly customField: CustomFieldApi;
  readonly datum: DatumApi;
  readonly default: DefaultApi;
  readonly defined: DefinedApi;
  readonly education: EducationApi;
  readonly eligible: EligibleApi;
  readonly emailConfiguration: EmailConfigurationApi;
  readonly emailSubscription: EmailSubscriptionApi;
  readonly employee: EmployeeApi;
  readonly employeeOnLeaveToday: EmployeeOnLeaveTodayApi;
  readonly employmentStatus: EmploymentStatusApi;
  readonly event: EventApi;
  readonly feed: FeedApi;
  readonly group: GroupApi;
  readonly hiringManager: HiringManagerApi;
  readonly holiday: HolidayApi;
  readonly interview: InterviewApi;
  readonly interviwer: InterviwerApi;
  readonly jobCategory: JobCategoryApi;
  readonly jobTitle: JobTitleApi;
  readonly kpis: KpisApi;
  readonly language: LanguageApi;
  readonly latest: LatestApi;
  readonly ldapConfig: LdapConfigApi;
  readonly ldapTestConnection: LdapTestConnectionApi;
  readonly leave: LeaveApi;
  readonly leaveBalance: LeaveBalanceApi;
  readonly leaveEntitlement: LeaveEntitlementApi;
  readonly leavePeriod: LeavePeriodApi;
  readonly leaveRequest: LeaveRequestApi;
  readonly leaveType: LeaveTypeApi;
  readonly licens: LicensApi;
  readonly link: LinkApi;
  readonly list: ListApi;
  readonly localization: LocalizationApi;
  readonly location: LocationApi;
  readonly membership: MembershipApi;
  readonly menus: MenusApi;
  readonly module: ModuleApi;
  readonly myself: MyselfApi;
  readonly nationality: NationalityApi;
  readonly oauthClient: OauthClientApi;
  readonly openidProvider: OpenidProviderApi;
  readonly optionalField: OptionalFieldApi;
  readonly organization: OrganizationApi;
  readonly overlap: OverlapApi;
  readonly overlapLeave: OverlapLeaveApi;
  readonly payGrade: PayGradeApi;
  readonly post: PostApi;
  readonly preview: PreviewApi;
  readonly project: ProjectApi;
  readonly projectAdmin: ProjectAdminApi;
  readonly projectName: ProjectNameApi;
  readonly punchInOverlap: PunchInOverlapApi;
  readonly punchOutOverlap: PunchOutOverlapApi;
  readonly purge: PurgeApi;
  readonly record: RecordApi;
  readonly registration: RegistrationApi;
  readonly report: ReportApi;
  readonly reportingMethod: ReportingMethodApi;
  readonly request: RequestApi;
  readonly review: ReviewApi;
  readonly reviewer: ReviewerApi;
  readonly share: ShareApi;
  readonly shortcut: ShortcutApi;
  readonly skill: SkillApi;
  readonly status: StatusApi;
  readonly subunit: SubunitApi;
  readonly summary: SummaryApi;
  readonly supervisor: SupervisorApi;
  readonly terminationReason: TerminationReasonApi;
  readonly test: TestApi;
  readonly theme: ThemeApi;
  readonly timeAtWork: TimeAtWorkApi;
  readonly timeFormat: TimeFormatApi;
  readonly timesheet: TimesheetApi;
  readonly timeSheetPeriod: TimeSheetPeriodApi;
  readonly timezone: TimezoneApi;
  readonly tracker: TrackerApi;
  readonly trackers: TrackersApi;
  readonly translation: TranslationApi;
  readonly type: TypeApi;
  readonly unique: UniqueApi;
  readonly updatePassword: UpdatePasswordApi;
  readonly user: UserApi;
  readonly userName: UserNameApi;
  readonly userSync: UserSyncApi;
  readonly vacancy: VacancyApi;
  readonly validation: ValidationApi;
  readonly workShift: WorkShiftApi;
  readonly workweek: WorkweekApi;

  constructor(request: APIRequestContext, baseUrl = BASE_URL, headers: Record<string, string> = {}) {
    this.http = new ApiClient(request, baseUrl, headers);
    this.about = new AboutApi(this.http);
    this.actionSummary = new ActionSummaryApi(this.http);
    this.activityName = new ActivityNameApi(this.http);
    this.anniversary = new AnniversaryApi(this.http);
    this.attachment = new AttachmentApi(this.http);
    this.bulk = new BulkApi(this.http);
    this.candidate = new CandidateApi(this.http);
    this.comment = new CommentApi(this.http);
    this.config = new ConfigApi(this.http);
    this.count = new CountApi(this.http);
    this.csvImport = new CsvImportApi(this.http);
    this.currentDatetime = new CurrentDatetimeApi(this.http);
    this.customer = new CustomerApi(this.http);
    this.customerName = new CustomerNameApi(this.http);
    this.customField = new CustomFieldApi(this.http);
    this.datum = new DatumApi(this.http);
    this.default = new DefaultApi(this.http);
    this.defined = new DefinedApi(this.http);
    this.education = new EducationApi(this.http);
    this.eligible = new EligibleApi(this.http);
    this.emailConfiguration = new EmailConfigurationApi(this.http);
    this.emailSubscription = new EmailSubscriptionApi(this.http);
    this.employee = new EmployeeApi(this.http);
    this.employeeOnLeaveToday = new EmployeeOnLeaveTodayApi(this.http);
    this.employmentStatus = new EmploymentStatusApi(this.http);
    this.event = new EventApi(this.http);
    this.feed = new FeedApi(this.http);
    this.group = new GroupApi(this.http);
    this.hiringManager = new HiringManagerApi(this.http);
    this.holiday = new HolidayApi(this.http);
    this.interview = new InterviewApi(this.http);
    this.interviwer = new InterviwerApi(this.http);
    this.jobCategory = new JobCategoryApi(this.http);
    this.jobTitle = new JobTitleApi(this.http);
    this.kpis = new KpisApi(this.http);
    this.language = new LanguageApi(this.http);
    this.latest = new LatestApi(this.http);
    this.ldapConfig = new LdapConfigApi(this.http);
    this.ldapTestConnection = new LdapTestConnectionApi(this.http);
    this.leave = new LeaveApi(this.http);
    this.leaveBalance = new LeaveBalanceApi(this.http);
    this.leaveEntitlement = new LeaveEntitlementApi(this.http);
    this.leavePeriod = new LeavePeriodApi(this.http);
    this.leaveRequest = new LeaveRequestApi(this.http);
    this.leaveType = new LeaveTypeApi(this.http);
    this.licens = new LicensApi(this.http);
    this.link = new LinkApi(this.http);
    this.list = new ListApi(this.http);
    this.localization = new LocalizationApi(this.http);
    this.location = new LocationApi(this.http);
    this.membership = new MembershipApi(this.http);
    this.menus = new MenusApi(this.http);
    this.module = new ModuleApi(this.http);
    this.myself = new MyselfApi(this.http);
    this.nationality = new NationalityApi(this.http);
    this.oauthClient = new OauthClientApi(this.http);
    this.openidProvider = new OpenidProviderApi(this.http);
    this.optionalField = new OptionalFieldApi(this.http);
    this.organization = new OrganizationApi(this.http);
    this.overlap = new OverlapApi(this.http);
    this.overlapLeave = new OverlapLeaveApi(this.http);
    this.payGrade = new PayGradeApi(this.http);
    this.post = new PostApi(this.http);
    this.preview = new PreviewApi(this.http);
    this.project = new ProjectApi(this.http);
    this.projectAdmin = new ProjectAdminApi(this.http);
    this.projectName = new ProjectNameApi(this.http);
    this.punchInOverlap = new PunchInOverlapApi(this.http);
    this.punchOutOverlap = new PunchOutOverlapApi(this.http);
    this.purge = new PurgeApi(this.http);
    this.record = new RecordApi(this.http);
    this.registration = new RegistrationApi(this.http);
    this.report = new ReportApi(this.http);
    this.reportingMethod = new ReportingMethodApi(this.http);
    this.request = new RequestApi(this.http);
    this.review = new ReviewApi(this.http);
    this.reviewer = new ReviewerApi(this.http);
    this.share = new ShareApi(this.http);
    this.shortcut = new ShortcutApi(this.http);
    this.skill = new SkillApi(this.http);
    this.status = new StatusApi(this.http);
    this.subunit = new SubunitApi(this.http);
    this.summary = new SummaryApi(this.http);
    this.supervisor = new SupervisorApi(this.http);
    this.terminationReason = new TerminationReasonApi(this.http);
    this.test = new TestApi(this.http);
    this.theme = new ThemeApi(this.http);
    this.timeAtWork = new TimeAtWorkApi(this.http);
    this.timeFormat = new TimeFormatApi(this.http);
    this.timesheet = new TimesheetApi(this.http);
    this.timeSheetPeriod = new TimeSheetPeriodApi(this.http);
    this.timezone = new TimezoneApi(this.http);
    this.tracker = new TrackerApi(this.http);
    this.trackers = new TrackersApi(this.http);
    this.translation = new TranslationApi(this.http);
    this.type = new TypeApi(this.http);
    this.unique = new UniqueApi(this.http);
    this.updatePassword = new UpdatePasswordApi(this.http);
    this.user = new UserApi(this.http);
    this.userName = new UserNameApi(this.http);
    this.userSync = new UserSyncApi(this.http);
    this.vacancy = new VacancyApi(this.http);
    this.validation = new ValidationApi(this.http);
    this.workShift = new WorkShiftApi(this.http);
    this.workweek = new WorkweekApi(this.http);
  }
}

export { idOf };
