// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('Admin/Languages — delete-language-records', () => {
  test('DELETE /api/v2/admin/languages responds 200', async ({ adminLanguagesApi }) => {
    const response = await adminLanguagesApi.deleteLanguageRecords();
    expect(response.status()).toBe(200);
  });
});
