#!/usr/bin/env node
// Rebuilds ui-map-results/component-inventory.md from the application map.
//
//   node scripts/framework-generator/inventory.mjs [path/to/map-dir]
//
// Run from the repo root. This replaces the inventory the deleted crawler used to
// write as a side effect of crawling; the map files are now the only source, so the
// inventory can be regenerated at any time without touching a browser.

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import yaml from 'js-yaml';
import { fromMap, toYamlInline } from './locator-spec.mjs';
import { labelFromComment } from './map-reader.mjs';

const MAP_DIR = process.argv[2] ?? join('ui-map-results', 'application-map');
const OUT = join('ui-map-results', 'component-inventory.md');

/** Every element in a map file, page elements first then each state's, as inventory rows. */
function rowsFromFile(path, page) {
  const raw = yaml.load(readFileSync(path, 'utf8'));
  if (!raw || typeof raw !== 'object') return [];

  const rows = [];
  const collect = (list) => {
    for (const e of Array.isArray(list) ? list : []) {
      if (!e?.name || !e.component || !e.locator) continue;
      rows.push({
        component: e.component,
        page,
        accName: labelFromComment(String(e.comment ?? ''), e.component),
        locator: fromMap(e.locator),
      });
    }
  };

  collect(raw.elements);
  for (const state of Array.isArray(raw.states) ? raw.states : []) collect(state.elements);
  return rows;
}

function render(rows) {
  const byType = new Map();
  for (const r of rows) {
    if (!byType.has(r.component)) byType.set(r.component, []);
    byType.get(r.component).push(r);
  }

  let sb = '# Component inventory\n\n';
  sb += '_Generated by `scripts/framework-generator/inventory.mjs` from `ui-map-results/application-map`._\n\n';
  for (const type of [...byType.keys()].sort()) {
    sb += `## ${type}\n\n`;
    sb += '| Component | Page | Accessible name | Locator | Tier | Notes |\n';
    sb += '|---|---|---|---|---|---|\n';
    for (const r of byType.get(type)) {
      const notes = r.locator.unstable ? (r.locator.unstableReason ?? 'unstable') : '';
      sb += `| ${r.component} | ${r.page} | ${r.accName} | \`${toYamlInline(r.locator)}\``
          + ` | ${r.locator.strategy} | ${notes} |\n`;
    }
    sb += '\n';
  }
  return sb;
}

const files = readdirSync(MAP_DIR).filter((f) => f.endsWith('.yaml')).sort();
if (files.length === 0) throw new Error(`No *.yaml files found in ${MAP_DIR}.`);

const rows = files.flatMap((f) => rowsFromFile(join(MAP_DIR, f), f.replace(/\.yaml$/, '')));
writeFileSync(OUT, render(rows));

const types = new Set(rows.map((r) => r.component));
console.log(`[inventory] ${OUT}: ${rows.length} element(s), ${types.size} component type(s), from ${files.length} map file(s).`);
