// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Admin/Employment Status'.

export type GetOneEmploymentStatusResponse = { data?: unknown; meta?: unknown; };

export type UpdateAnEmploymentStatusRequest = { name: string; };

export type UpdateAnEmploymentStatusResponse = { data?: unknown; meta?: unknown; };

export type ListAllEmploymentStatusesResponse = { data?: unknown; meta?: unknown; };

export type CreateAnEmploymentStatusRequest = { name: string; };

export type CreateAnEmploymentStatusResponse = { data?: unknown; meta?: unknown; };
