// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Admin/Organization'.

export type GetOrganizationDetailsResponse = { data?: unknown; meta?: unknown; };

export type UpdateOrganizationDetailsRequest = { name: string; registrationNumber?: string; taxId?: string; phone?: string; fax?: string; email?: string; country?: string; province?: string; city?: string; zipCode?: string; street1?: string; street2?: string; note?: string; };

export type UpdateOrganizationDetailsResponse = { data?: unknown; meta?: unknown; };
