// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Admin/Email Subscription'.

export type GetAllEmailSubscriptionsResponse = { data?: unknown; meta?: unknown; };

export type UpdateEmailSusbcriptionRequest = { enabled: boolean; };

export type UpdateEmailSusbcriptionResponse = { data?: unknown; meta?: unknown; };
