// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Admin/Email Configuration'.

export type GetEmailConfigurationResponse = { data?: unknown; meta?: unknown; };

export type UpdateEmailConfigurationRequest = { mailType?: string; sentAs?: string; smtpHost?: string; smtpPort?: number; smtpUsername?: string; smtpPassword?: string; smtpAuthType?: string; smtpSecurityType?: string; testEmailAddress?: string; };

export type UpdateEmailConfigurationResponse = { data?: unknown; meta?: unknown; };
