// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Admin/Pay Grade'.

export type ListAllPayGradesResponse = { data?: unknown; meta?: unknown; };

export type CreateAPayGradeRequest = { name: string; };

export type CreateAPayGradeResponse = { data?: unknown; meta?: unknown; };

export type GetAPayGradeResponse = { data?: unknown; meta?: unknown; };

export type UpdateAPayGradeRequest = { name: string; };

export type UpdateAPayGradeResponse = { data?: unknown; meta?: unknown; };
