// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Attendance/Timezones'.

export type ListTimezonesResponse = { data?: unknown; meta?: unknown; };
