// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Buzz/Feed'.

export type ListTheBuzzFeedResponse = { data?: unknown; meta?: unknown; };
