// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Buzz/Comment Likes'.

export type ListLikesOnACommentResponse = { data?: unknown; meta?: unknown; };

export type LikeACommentResponse = { data?: unknown; meta?: unknown; };

export type UnlikeALikedCommentResponse = { data?: unknown; };
