// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Claim/My Requests'.

export type ListMyClaimRequestsResponse = { data?: unknown; meta?: unknown; };

export type CreateMyClaimRequestRequest = { claimEventId: number; currencyId?: string; remarks?: string; };

export type CreateMyClaimRequestResponse = { data?: unknown; meta?: unknown; };

export type GetMyClaimRequestResponse = { data?: unknown; meta?: unknown; };
