// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Claim/Expense Types'.

export type ListAllExpenseTypesResponse = { data?: unknown; meta?: unknown; };

export type CreateAnExpenseTypeRequest = { name: string; description?: string; status?: boolean; };

export type CreateAnExpenseTypeResponse = { data?: unknown; meta?: unknown; };

export type GetAnExpenseTypeResponse = { data?: unknown; meta?: unknown; };

export type UpdateAnExpenseTypeRequest = { name?: string; description?: string; status?: boolean; };

export type UpdateAnExpenseTypeResponse = { data?: unknown; meta?: unknown; };
