// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Directory/Employees'.

export type GetAnEmployeeDirectoryListingResponse = { data?: unknown; meta?: unknown; };

export type GetTheEmployeeDirectoryResponse = { data?: unknown; meta?: unknown; };
