// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Leave/Leave Request Comment'.

export type ListCommentsForALeaveRequestResponse = { data?: unknown; meta?: unknown; };

export type CommentOnALeaveRequestRequest = { comment?: string; };

export type CommentOnALeaveRequestResponse = { data?: unknown; meta?: unknown; };
