// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Leave/Work Week'.

export type GetWorkWeekResponse = { data?: unknown; meta?: unknown; };

export type UpdateWorkWeekRequest = { monday: number; tuesday: number; wednesday: number; thursday: number; friday: number; saturday: number; sunday: number; };

export type UpdateWorkWeekResponse = { data?: unknown; meta?: unknown; };
