// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Leave/Leaves'.

export type ListAllLeavesInALeaveRequestResponse = { data?: unknown; meta?: unknown; };

export type UpdateALeaveRequest = { action?: string; };

export type UpdateALeaveResponse = { data?: unknown; meta?: unknown; };
