// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Maintenance/Purge Employee'.

export type PurgeEmployeeRequest = { empNumber: number; };

export type PurgeEmployeeResponse = { data?: unknown; meta?: unknown; };
