// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Mobile/Menu Items'.

export type ListMobileMenuItemsResponse = { data?: unknown; meta?: unknown; };
