// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'OAuth/OAuth Clients'.

export type ListAllOauthClientsResponse = { data?: unknown; meta?: unknown; };

export type CreateAnOauthClientRequest = { name?: string; redirectUri?: string; enabled?: boolean; };

export type CreateAnOauthClientResponse = { data?: unknown; meta?: unknown; };

export type GetAnOauthClientResponse = { data?: unknown; meta?: unknown; };

export type UpdateAnOauthClientRequest = { name?: string; redirectUri?: string; enabled?: boolean; };

export type UpdateAnOauthClientResponse = { data?: unknown; meta?: unknown; };
