// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Performance/Trackers'.

export type ListAllEmployeeTrackersResponse = { data?: unknown; meta?: unknown; };

export type GetAnEmployeeTrackerResponse = { data?: unknown; meta?: unknown; };

export type ListMyPerformanceTrackersResponse = { data?: unknown; meta?: unknown; };
