// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Performance/KPI Configuration'.

export type GetAKpiResponse = { data?: unknown; meta?: unknown; };

export type UpdateAKpiRequest = { title: string; jobTitleId: number; minRating: number; maxRating: number; isDefault?: boolean; };

export type UpdateAKpiResponse = { data?: unknown; meta?: unknown; };

export type ListAllKpisResponse = { data?: unknown; meta?: unknown; };

export type CreateAKpiRequest = { title: string; jobTitleId: number; minRating: number; maxRating: number; isDefault?: boolean; };

export type CreateAKpiResponse = { data?: unknown; meta?: unknown; };
