// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Performance/Review Evaluation by Employee'.

export type GetTheEmployeesEvaluationInAReviewResponse = { data?: unknown; meta?: unknown; };

export type UpdateTheEmployeesEvaluationInAReviewRequest = { reviewers: unknown; generalComment?: string; complete: boolean; };

export type UpdateTheEmployeesEvaluationInAReviewResponse = { data?: unknown; meta?: unknown; };
