// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'PIM/Employee Contact Details'.

export type GetAnEmployeesContactDetailsResponse = { data?: unknown; meta?: unknown; };

export type UpdateAnEmployeesContactDetailsRequest = { street1?: string; street2?: string; city?: string; province?: string; zipCode?: string; countryCode?: string; homeTelephone?: string; workTelephone?: string; mobile?: string; workEmail?: string; otherEmail?: string; };

export type UpdateAnEmployeesContactDetailsResponse = { data?: unknown; meta?: unknown; };
