// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'PIM/Employee Email Validation'.

export type ValidateAnEmployeesWorkEmailResponse = { data?: unknown; meta?: unknown; };

export type ValidateAnEmployeeOtherEmailResponse = { data?: unknown; meta?: unknown; };
