// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'PIM/Employee Count'.

export type GetTheNumberOfEmployeesResponse = { data?: unknown; meta?: unknown; };
