// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'PIM/Employee'.

export type GetAnEmployeeResponse = { data?: unknown; meta?: unknown; };

export type ListAllEmployeesResponse = { data?: unknown; meta?: unknown; };

export type CreateAnEmployeeRequest = { lastName: string; firstName: string; middleName?: string; employeeId?: string; empPicture?: unknown; };

export type CreateAnEmployeeResponse = { data?: unknown; meta?: unknown; };

export type GetMyDetailsResponse = { data?: unknown; };
