// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Recruitment/Hiring Managers'.

export type ListAvailableEmployeesForHiringManagerResponse = { data?: unknown; meta?: unknown; };
