// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Recruitment/Candidate Workflow'.

export type GetAllowedActionsForCandidateResponse = { data?: unknown; meta?: unknown; };

export type HireCandidateRequest = { note?: string; };

export type HireCandidateResponse = { data?: unknown; meta?: unknown; };

export type ScheduleInterviewForACandidateRequest = { interviewName: string; interviewDate: string; interviewTime?: string; note?: string; interviewerEmpNumbers: unknown; };

export type ScheduleInterviewForACandidateResponse = { data?: unknown; meta?: unknown; };

export type OfferJobToCandidateRequest = { note?: string; };

export type OfferJobToCandidateResponse = { data?: unknown; meta?: unknown; };

export type MarkCandidateInterviewAsFailedRequest = { note?: string; };

export type MarkCandidateInterviewAsFailedResponse = { data?: unknown; meta?: unknown; };

export type MarkCandidateInterviewAsPassedRequest = { note?: string; };

export type MarkCandidateInterviewAsPassedResponse = { data?: unknown; meta?: unknown; };

export type DeclineJobOfferForCandidateRequest = { note?: string; };

export type DeclineJobOfferForCandidateResponse = { data?: unknown; meta?: unknown; };

export type RejectCandidateRequest = { note?: string; };

export type RejectCandidateResponse = { data?: unknown; meta?: unknown; };

export type ShortlistCandidateRequest = { note?: string; };

export type ShortlistCandidateResponse = { data?: unknown; meta?: unknown; };
