// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Time/Timesheet Time Format'.

export type GetTimesheetTimeFormatResponse = { data?: unknown; meta?: unknown; };
