// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Time/My Timesheet'.

export type ListMyTimesheetsResponse = { data?: unknown; meta?: unknown; };

export type CreateMyTimesheetRequest = { date: string; };

export type CreateMyTimesheetResponse = { data?: unknown; meta?: unknown; };

export type UpdateMyTimesheetRequest = { action?: string; comment?: string; };

export type UpdateMyTimesheetResponse = { data?: unknown; meta?: unknown; };

export type ListMyTimesheetEntriesResponse = { data?: unknown; meta?: unknown; };

export type UpdateMyTimesheetEntriesRequest = { entries?: unknown; };

export type UpdateMyTimesheetEntriesResponse = { data?: unknown; meta?: unknown; };
