// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Time/Validation'.

export type ValidateProjectActivityUniquenessInTimesheetResponse = { data?: unknown; meta?: unknown; };

export type ValidateProjectNameUniquenessResponse = { data?: unknown; meta?: unknown; };

export type ValidateCustomerNameUniquenessResponse = { data?: unknown; meta?: unknown; };

export type ValidateProjectActivityNameUniquenessResponse = { data?: unknown; meta?: unknown; };
