// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Time/Timesheet Report'.

export type GetTimeReportsResponse = { data?: unknown; meta?: unknown; };

export type GetTimeReportDataResponse = { data?: unknown; meta?: unknown; };
