// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: openapi api-map for 'Time/Customers'.

export type ListAllCustomersResponse = { data?: unknown; meta?: unknown; };

export type CreateACustomerRequest = { name: string; description?: string; };

export type CreateACustomerResponse = { data?: unknown; meta?: unknown; };

export type GetACustomerResponse = { data?: unknown; meta?: unknown; };

export type UpdateACustomerRequest = { name: string; description?: string; };

export type UpdateACustomerResponse = { data?: unknown; meta?: unknown; };
