// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('Claim/Expenses — remove-an-expense-from-a-claim', () => {
  test('DELETE /api/v2/claim/requests/{requestId}/expenses responds 200', async ({ claimExpensesApi }) => {
    const response = await claimExpensesApi.removeAnExpenseFromAClaim('REPLACE_ME' as never);
    expect(response.status()).toBe(200);
  });
});
