// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
//
// Logs in once before the suite and saves the session, so specs start authenticated.

import { chromium, type FullConfig } from '@playwright/test';
import { login, STORAGE_STATE } from './auth-fixtures';

export default async function globalSetup(config: FullConfig): Promise<void> {
  const { baseURL } = config.projects[0].use;
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({ baseURL });
    await login(page);
    await page.context().storageState({ path: STORAGE_STATE });
  } finally {
    await browser.close();
  }
}
