// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
//
// Hand-written fixtures go in extra-fixtures.ts, which is written once and never
// touched again; the test object below is re-exported from there so a spec only
// ever imports from './fixtures'.
export { test } from './extra-fixtures';
export { expect } from '@playwright/test';
export type { PageObjects } from './page-fixtures';
export { login, STORAGE_STATE } from './auth-fixtures';
export { ApiClient } from '../api/clients/ApiClient';
export { expectResponse, expectJson } from '../utils/network';
export { uniqueSuffix, uniqueUsername, uniqueEmail, uniqueName } from '../utils/testData';
