// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
//
// One fixture per page object. Playwright builds only the ones a test asks for,
// so declaring all of them costs nothing at run time.

import { test as base } from '@playwright/test';
import { AdminPage } from '../pages/admin/AdminPage';
import { SystemUsersPage } from '../pages/admin/SystemUsersPage';
import { BuzzPage } from '../pages/buzz/BuzzPage';
import { AssignClaimPage } from '../pages/claim/AssignClaimPage';
import { DashboardPage } from '../pages/dashboard/DashboardPage';
import { DirectoryPage } from '../pages/directory/DirectoryPage';
import { LeaveListPage } from '../pages/leave/LeaveListPage';
import { MaintenancePage } from '../pages/maintenance/MaintenancePage';
import { SearchEvaluatePerformanceReviewPage } from '../pages/performance/SearchEvaluatePerformanceReviewPage';
import { ContactDetailsPage } from '../pages/pim/ContactDetailsPage';
import { DependentsPage } from '../pages/pim/DependentsPage';
import { EmergencyContactsPage } from '../pages/pim/EmergencyContactsPage';
import { EmployeeListPage } from '../pages/pim/EmployeeListPage';
import { ImmigrationPage } from '../pages/pim/ImmigrationPage';
import { JobDetailsPage } from '../pages/pim/JobDetailsPage';
import { MembershipsPage } from '../pages/pim/MembershipsPage';
import { MyDetailsPage } from '../pages/pim/MyDetailsPage';
import { PimPage } from '../pages/pim/PimPage';
import { QualificationsPage } from '../pages/pim/QualificationsPage';
import { ReportToDetailsPage } from '../pages/pim/ReportToDetailsPage';
import { SalaryListPage } from '../pages/pim/SalaryListPage';
import { CandidatesPage } from '../pages/recruitment/CandidatesPage';
import { RecruitmentPage } from '../pages/recruitment/RecruitmentPage';
import { TimePage } from '../pages/time/TimePage';

export type PageObjects = {
  adminPage: AdminPage;
  systemUsersPage: SystemUsersPage;
  buzzPage: BuzzPage;
  assignClaimPage: AssignClaimPage;
  dashboardPage: DashboardPage;
  directoryPage: DirectoryPage;
  leaveListPage: LeaveListPage;
  maintenancePage: MaintenancePage;
  searchEvaluatePerformanceReviewPage: SearchEvaluatePerformanceReviewPage;
  contactDetailsPage: ContactDetailsPage;
  dependentsPage: DependentsPage;
  emergencyContactsPage: EmergencyContactsPage;
  employeeListPage: EmployeeListPage;
  immigrationPage: ImmigrationPage;
  jobDetailsPage: JobDetailsPage;
  membershipsPage: MembershipsPage;
  myDetailsPage: MyDetailsPage;
  pimPage: PimPage;
  qualificationsPage: QualificationsPage;
  reportToDetailsPage: ReportToDetailsPage;
  salaryListPage: SalaryListPage;
  candidatesPage: CandidatesPage;
  recruitmentPage: RecruitmentPage;
  timePage: TimePage;
};

export const test = base.extend<PageObjects>({
  adminPage: async ({ page }, use) => { await use(new AdminPage(page)); },
  systemUsersPage: async ({ page }, use) => { await use(new SystemUsersPage(page)); },
  buzzPage: async ({ page }, use) => { await use(new BuzzPage(page)); },
  assignClaimPage: async ({ page }, use) => { await use(new AssignClaimPage(page)); },
  dashboardPage: async ({ page }, use) => { await use(new DashboardPage(page)); },
  directoryPage: async ({ page }, use) => { await use(new DirectoryPage(page)); },
  leaveListPage: async ({ page }, use) => { await use(new LeaveListPage(page)); },
  maintenancePage: async ({ page }, use) => { await use(new MaintenancePage(page)); },
  searchEvaluatePerformanceReviewPage: async ({ page }, use) => { await use(new SearchEvaluatePerformanceReviewPage(page)); },
  contactDetailsPage: async ({ page }, use) => { await use(new ContactDetailsPage(page)); },
  dependentsPage: async ({ page }, use) => { await use(new DependentsPage(page)); },
  emergencyContactsPage: async ({ page }, use) => { await use(new EmergencyContactsPage(page)); },
  employeeListPage: async ({ page }, use) => { await use(new EmployeeListPage(page)); },
  immigrationPage: async ({ page }, use) => { await use(new ImmigrationPage(page)); },
  jobDetailsPage: async ({ page }, use) => { await use(new JobDetailsPage(page)); },
  membershipsPage: async ({ page }, use) => { await use(new MembershipsPage(page)); },
  myDetailsPage: async ({ page }, use) => { await use(new MyDetailsPage(page)); },
  pimPage: async ({ page }, use) => { await use(new PimPage(page)); },
  qualificationsPage: async ({ page }, use) => { await use(new QualificationsPage(page)); },
  reportToDetailsPage: async ({ page }, use) => { await use(new ReportToDetailsPage(page)); },
  salaryListPage: async ({ page }, use) => { await use(new SalaryListPage(page)); },
  candidatesPage: async ({ page }, use) => { await use(new CandidatesPage(page)); },
  recruitmentPage: async ({ page }, use) => { await use(new RecruitmentPage(page)); },
  timePage: async ({ page }, use) => { await use(new TimePage(page)); },
});

export { expect } from '@playwright/test';
