// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
//
// One fixture per page object, plus `api` for the setup, teardown and
// assertions that do not need a browser. Playwright builds only the ones a
// test asks for, so declaring all of them costs nothing at run time.

import { test as base } from '@playwright/test';
import { ApiClient } from '../api/clients/ApiClient';
import { AssignClaimPage } from '../pages/claim/AssignClaimPage';
import { SaveEventsPage } from '../pages/claim/SaveEventsPage';
import { SaveExpensePage } from '../pages/claim/SaveExpensePage';
import { SubmitClaimPage } from '../pages/claim/SubmitClaimPage';
import { ClaimAssignClaimPage } from '../pages/claim/ClaimAssignClaimPage';
import { ClaimPage } from '../pages/claim/ClaimPage';
import { EventsPage } from '../pages/claim/EventsPage';
import { ExpensePage } from '../pages/claim/ExpensePage';
import { AddEmployeePage } from '../pages/pim/AddEmployeePage';
import { ContactDetailsPage } from '../pages/pim/ContactDetailsPage';
import { DefinedPredefinedReportsPage } from '../pages/pim/DefinedPredefinedReportsPage';
import { EmployeeListPage } from '../pages/pim/EmployeeListPage';
import { PersonalDetailsPage } from '../pages/pim/PersonalDetailsPage';

export type PageObjects = {
  api: ApiClient;
  assignClaimPage: AssignClaimPage;
  saveEventsPage: SaveEventsPage;
  saveExpensePage: SaveExpensePage;
  submitClaimPage: SubmitClaimPage;
  claimAssignClaimPage: ClaimAssignClaimPage;
  claimPage: ClaimPage;
  eventsPage: EventsPage;
  expensePage: ExpensePage;
  addEmployeePage: AddEmployeePage;
  contactDetailsPage: ContactDetailsPage;
  definedPredefinedReportsPage: DefinedPredefinedReportsPage;
  employeeListPage: EmployeeListPage;
  personalDetailsPage: PersonalDetailsPage;
};

export const test = base.extend<PageObjects>({
  api: async ({ request }, use) => { await use(new ApiClient(request)); },
  assignClaimPage: async ({ page }, use) => { await use(new AssignClaimPage(page)); },
  saveEventsPage: async ({ page }, use) => { await use(new SaveEventsPage(page)); },
  saveExpensePage: async ({ page }, use) => { await use(new SaveExpensePage(page)); },
  submitClaimPage: async ({ page }, use) => { await use(new SubmitClaimPage(page)); },
  claimAssignClaimPage: async ({ page }, use) => { await use(new ClaimAssignClaimPage(page)); },
  claimPage: async ({ page }, use) => { await use(new ClaimPage(page)); },
  eventsPage: async ({ page }, use) => { await use(new EventsPage(page)); },
  expensePage: async ({ page }, use) => { await use(new ExpensePage(page)); },
  addEmployeePage: async ({ page }, use) => { await use(new AddEmployeePage(page)); },
  contactDetailsPage: async ({ page }, use) => { await use(new ContactDetailsPage(page)); },
  definedPredefinedReportsPage: async ({ page }, use) => { await use(new DefinedPredefinedReportsPage(page)); },
  employeeListPage: async ({ page }, use) => { await use(new EmployeeListPage(page)); },
  personalDetailsPage: async ({ page }, use) => { await use(new PersonalDetailsPage(page)); },
});

export { expect } from '@playwright/test';
