// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('AddThemePage', () => {
  test('loads', async ({ addThemePage }) => {
    await addThemePage.goto();
    await expect(addThemePage.page).toHaveURL(new RegExp('/web/index\\.php/admin/addTheme'));
  });
});
