// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('JobSpecificationPage', () => {
  test('loads', async ({ jobSpecificationPage }) => {
    await jobSpecificationPage.goto();
    await expect(jobSpecificationPage.page).toHaveURL(new RegExp('/web/index\\.php/admin/viewJobSpecification/attachId/\\{attachId\\}'));
  });
});
