// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('JobTitleListPage', () => {
  test('loads', async ({ jobTitleListPage }) => {
    await jobTitleListPage.goto();
    await expect(jobTitleListPage.page).toHaveURL(new RegExp('/web/index\\.php/admin/viewJobTitleList'));
  });
});
