// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('LocationsPage', () => {
  test('loads', async ({ locationsPage }) => {
    await locationsPage.goto();
    await expect(locationsPage.page).toHaveURL(new RegExp('/web/index\\.php/admin/viewLocations'));
  });
});
