// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('SaveEmploymentStatusPage', () => {
  test('loads', async ({ saveEmploymentStatusPage }) => {
    await saveEmploymentStatusPage.goto();
    await expect(saveEmploymentStatusPage.page).toHaveURL(new RegExp('/web/index\\.php/admin/saveEmploymentStatus/\\{id\\}'));
  });
});
