// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('SaveWorkShiftsPage', () => {
  test('loads', async ({ saveWorkShiftsPage }) => {
    await saveWorkShiftsPage.goto();
    await expect(saveWorkShiftsPage.page).toHaveURL(new RegExp('/web/index\\.php/admin/saveWorkShifts/\\{id\\}'));
  });
});
