// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('OpenIdCredentialsPage', () => {
  test('loads', async ({ openIdCredentialsPage }) => {
    await openIdCredentialsPage.goto();
    await expect(openIdCredentialsPage.page).toHaveURL(new RegExp('/web/index\\.php/openidauth/openIdCredentials/\\{providerId\\}'));
  });
});
