// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';
import { assertShape } from '../../../src/utils/schema-assert';

test.describe('Time/Timesheet Comment — update-a-timesheet-comment', () => {
  test('PUT /api/v2/time/timesheets/{timesheetId}/entries/comment responds 200', async ({ timeTimesheetCommentApi }) => {
    // TODO: fill in a valid request body.
    const response = await timeTimesheetCommentApi.updateATimesheetComment('REPLACE_ME' as never, {} as never);
    expect(response.status()).toBe(200);
    const body = await response.json();
    assertShape(body, {"kind":"object","properties":[{"name":"data","type":"unknown","required":false,"nullable":false},{"name":"meta","type":"unknown","required":false,"nullable":false}]});
  });
});
