// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Source: view_help_support
// Your own methods belong in SupportPage.ts, which the generator never touches.

import type { Page } from '@playwright/test';
import { BasePage } from '../base/BasePage';
import { LinkComponent } from '../../components/LinkComponent';
import { NavigationBar } from '../../components/navigation/NavigationBar';

/** /web/index.php/help/support */
export abstract class SupportPageGenerated extends BasePage {
  static readonly path = '/web/index.php/help/support';

  constructor(page: Page) {
    super(page, SupportPageGenerated.path);
  }

  /** Chrome shared by every page: top bar and side menu. */
  readonly navigation = new NavigationBar(this.page);

  /** Should you experience any issues, please do not hesitate to contact us on (link) */
  get shouldYouExperienceAnyIssuesPleaseDoNotHesitateToContactUsOnLink(): LinkComponent {
    return LinkComponent.byLabel(this.page, 'Should you experience any issues, please do not hesitate to contact us on');
  }
}
