// AUTO-GENERATED by framework-generator. Do not edit — every run overwrites this file.
// Add real scenarios in sibling spec files; those are yours to keep.

import { test, expect } from '../../../src/fixtures';

test.describe('Time/Project Activity — delete-a-projects-activities', () => {
  test('DELETE /api/v2/time/project/{projectId}/activities responds 200', async ({ timeProjectActivityApi }) => {
    const response = await timeProjectActivityApi.deleteAProjectsActivities('REPLACE_ME' as never);
    expect(response.status()).toBe(200);
  });
});
